### ISSUE TITLE
server did not acknowledge the last chunk. (No e-tag were present)

### ISSUE THREAD

**Issue by toadhall** [owncloud/core#12725]
Environment: root server
Server: Debian Wheezy
Database: SQLite
Client: Debian Testing
OC-Version: 7.0.3
PHP-Version: 5.4.35-0

Since updating to 7.0.3 I keep on getting this error:

The item is not synced because of previous errors: The server did not acknowledge the last chunk. (No e-tag were present)

Worked fine in version 7.0.2.1 and only started appearing on random files (all of the small, between 40 and 70kb) in version 7.0.3.

Please let me know if there is anything else you need from me (specific logs, etc.)

Many thanks in advance!

**Comment by viorel-anghel** [comment]
I have the same problem on Ubuntu and I was wondering maybe it's a client-only problem. BEsides the trick with rename, i have discovered this behaviour: if I copy the files one by one, it is working ok. If I try to copy more than 3 files at once, it start to give the error "server did not acknowledge the last chunk. (No e-tag were present)" and it is never recovering from this error unless you rename one file, wait for sync, rename it back.

**Comment by simonspa** [comment]
Same problem here, running ownCloud 7.0.4 on Debian stable, Server nginx with encryption enabled. The missing e-tag appears randomly, I managed to upload several thousand files (8 GB inn total) and it appeared only a couple of dozens of times. However, for those files it is persistent.

**Comment by PVince81** [comment]
CC @schiesbn 

Do you guys all see messages like "share key is missing" or "something.key" is missing related to the broken files ?

**Comment by simonspa** [comment]
Yes, I see messages like this in my owncloud log, and the files are exactly the problematic ones:

```
{"app":"encryption library","message":"No keys available to decrypt the file: username\/filename.ext.ocTransferId1897145941.part","level":3,"time":"2015-01-06T20:49:05+00:00"}
```

**Comment by ianbmacdonald** [comment]
This issue is persistent..  I don't have any "No keys available" errors in my logs.   Here is the latest example, currently jamming up client notifications on my desktop right now. 

This is an excerpt from the logs from the initial creation of new folders and files that led to the "The server did not acknowledge the last chunk. (No e-tag were present)" issue on my own 1.7.1 ubuntu client appearing every minute now.  

The relevant part on the server side logs, I believe begins with the "OC\\Files\\Cache\\Scanner","message" message. 

I'd be happy to share larger sections of logs directly with developers.  It would be nice to get rid of the log file permission errors and webdav auth errors too, but I expect they are just loose ends from the packaging permissions and use of LDAP for authentication and not causing issues to my knowledge. 

{"reqId":"54aec9285ff7b","app":"PHP","message":"rename(\/var\/log\/owncloud.log,\/var\/log\/owncloud.log.1): Permission denied at \/var\/www\/owncloud\/lib\/private\/log\/rotate.php#31","level":3,"time":"January 08, 2015 13:15:04","method":"--","url":"--"}
{"reqId":"54aec9285ff7b","app":"OC\\Log\\Rotate","message":"Log file \"\/var\/log\/owncloud.log\" was over 1 bytes, moved to \"\/var\/log\/owncloud.log.1\"","level":2,"time":"January 08, 2015 13:15:04","method":"--","url":"--"}
{"reqId":"54aec9801795b","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"January 08, 2015 13:16:32","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"54aec9d21b2ce","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"January 08, 2015 13:17:54","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"54aecab083815","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"January 08, 2015 13:21:36","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"54aecaca46dba","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"January 08, 2015 13:22:02","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"54aecbcfcf887","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'Huawei Doc Reader\/Hedex Lite' !!! \ncache: Array\n(\n    [displayname_owner] => admin\n    [path] => Huawei Doc Reader\/Hedex Lite\n    [uid_owner] => admin\n    [permissions] => 31\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1420741583\n    [size] => -1\n    [etag] => 54aecbcfcbac1\n    [storage_mtime] => 1420741583\n    [permissions] => 31\n    [parent] => 31931\n)\n","level":0,"time":"January 08, 2015 13:26:23","method":"MKCOL","url":"\/remote.php\/webdav\/Corp_Software\/Huawei%20Doc%20Reader\/Hedex%20Lite\/"}
{"reqId":"54aecbd909cda","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'Huawei Doc Reader\/Hedex Lite\/bin' !!! \ncache: Array\n(\n    [displayname_owner] => admin\n    [path] => Huawei Doc Reader\/Hedex Lite\/bin\n    [uid_owner] => admin\n    [permissions] => 31\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1420741592\n    [size] => -1\n    [etag] => 54aecbd9018b7\n    [storage_mtime] => 1420741592\n    [permissions] => 31\n    [parent] => 54714\n)\n","level":0,"time":"January 08, 2015 13:26:33","method":"MKCOL","url":"\/remote.php\/webdav\/Corp_Software\/Huawei%20Doc%20Reader\/Hedex%20Lite\/bin\/"}
{"reqId":"54aecbddd071e","app":"remote","message":"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `permissions`, `parent`, `path_hash`, `path`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-192aa4a6fccb1e073ee2bc783bf903dc' for key 'fs_storage_path_hash'","level":4,"time":"January 08, 2015 13:26:37","method":"PUT","url":"\/remote.php\/webdav\/Corp_Software\/Huawei%20Doc%20Reader\/Hedex%20Lite\/bin\/HedExLite.exe"}
{"reqId":"54aecbddd071e","app":"PHP","message":"Session has been closed - no further changes to the session as allowed at \/var\/www\/owncloud\/lib\/private\/session\/memory.php#80","level":3,"time":"January 08, 2015 13:26:37","method":"PUT","url":"\/remote.php\/webdav\/Corp_Software\/Huawei%20Doc%20Reader\/Hedex%20Lite\/bin\/HedExLite.exe"}

**Comment by maste9** [comment]
@PVince81 In my case it's been only brand new files. All existing files could be altered and overwritten without failure. I today tried to create and sync two simple text-files in main folder and subfolder which worked properly. I then tried to copy two image-files simultanouesly into subfolder which suprisingly again worked.
So at the moment I cannot willingly reproduce failure and will report if this changes again ...

**Comment by tflidd** [comment]
I also experienced it with a new file. I copied some files into a folder before Christmas but one file failed (error with last chunk). In the client-log I have this message:
````
01-09 14:47:44:227 0x76beba8 socketapi.cpp:382 void Mirall::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, Mirall::SocketType*) "F:\ownCloud\folder\File Name 08.DOC"
01-09 14:47:44:227 0x76beba8 socketapi.cpp:584 Mirall::SyncFileStatus Mirall::SocketApi::fileStatus(Mirall::Folder*, const QString&, c_strlist_t*) Could not determine state for file "folder/File Name 08.DOC" will set STATUS_NEW
01-09 14:47:44:227 0x76beba8 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:NEW:F:\ownCloud\folder\File Name 08.DOC"
01-09 14:47:46:551 0xa3db87c csync_walker: file: F:\ownCloud\folder\File Name 08.DOC [inode=115589 size=20992]
01-09 14:47:46:551 0xa3db87c _csync_detect_update: Checking for rename based on inode # 115589
01-09 14:47:46:551 0xa3db87c _csync_detect_update: file: folder/File Name 08.DOC, instruction: INSTRUCTION_NEW <<=
````
All files perfectly synced except this one. It contains some spaces in the name. I removed the spaces, then the file synced, I renamed it back to it's initial name and it was renamed.

I still have the original file. I recopied it to a new folder, tried also some testfiles but I couldn't reproduce this error.

I'm also using the encryption-app -> issues/11405

**Comment by simonspa** [comment]
@PVince81 hm, I can't completely exclude concurrent file access since there are two clients that sync from this account. None of the folders where shared with other users though, all private.

Since it happens randomly at some (new) files I can't really come up with a reproducible procedure. If I manage, I will let you know.

**Comment by ianbmacdonald** [comment]
On my issue "the duplicate entry issue again" .. is that something that can be fixed or merged from a previous patch?

**Comment by PVince81** [comment]
Unfortunately no. It's a mysterious issue that popped up many times. See https://github.com/owncloud/core/issues/2566 and linked tickets.

**Comment by JohnnyricoMC** [comment]
We're experiencing similar issues. I've tried to get as many details as possible from the affected user, but I fear what I can contribute is rather sparse:

### Steps to reproduce
Affected user tries to add new file via web interface or desktop client, 
When using the web-interface, the user received a message (translated this): Cannot decrypt this file, it is probably a shared file. Ask the owner to share the file with you again. Original text: ```Kan dit bestand niet ontcijferen, waarschijnlijk is het een gedeeld bestand, Vraag de eigenaar om het bestand opnieuw met u te delen.```
When using the desktop client the message ``` Dir1/Dir2/Dir3/Dir4/index.css: The server did not acknowledge the last chunk. (No e-tag were present)``` appeared in the client.

### Server configuration:
* OS: Debian 7 "Wheezy"
* Web Server: Apache 2.2.22
* Database: mysql  Ver 14.14 Distrib 5.5.40, for debian-linux-gnu (x86_64) using readline 6.2
* PHP version: PHP 5.4.35-0+deb7u2
* Owncloud Version: 7.0.4
* Updated from an older owncloud or fresh install: yes, originally from OC 5.0.14 -> OC 6 -> OC 7.0
* config/config.php:
```<?php
$CONFIG = array (
  'passwordsalt' => 'OMITTED',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud_mysql',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud_mysql',
  'dbpassword' => 'OMITTED',
  'installed' => true,
  'instanceid' => 'OMITTED',
  'loglevel' => '0',
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'subdomain.domain1.tld',
    1 => 'subdomain.domain2.tld',
  ),
  'share_folder' => '/Shared',
  'secret' => 'OMITTED',
);
```
* Are you using external storage, if yes which one: no
* All files and folders in /var/www/owncloud are currently owned by www-data

### Client configuration
Browsers: Google Chrome
Owncloud Desktop app in Windows 8.1
### Activated apps:
* Activity 1.1.23
* Bookmarks 0.4
* Deleted files 0.6.2
* Encryption 0.6.1
* ownCloud dependencies info 0.02
* PDF Viewer 0.5
* Pictures 0.5.4
* Share Files 0.5.3
* Text Editor 0.4
* Updater 0.4
* Versions 1.0.5
### Logs

#### Web server error log

No entries appeared while reproducing issue

#### Owncloud log
 The first line seems unrelated, I only included it because it appears to concern the same file:
```
{"reqId":"54b8e1474947c","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'thumbnails\/120676' is not readable !!!","level":0,"time":"2015-01-16T10:00:39+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FUsername%2FDir1%2FDir2%2FDir3%2FDir4%2Findex.css&c=54b8e11f71032&x=36&y=36&forceIcon=0"}

{"reqId":"54b8e15979ada","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/Username\/Dir1\/Dir2\/Dir3\/Dir4\/index.css' !!! \ncache: Array\n(\n    [fileid] => 137599\n    [storage] => home::Username\n    [path] => files\/Username\/Dir1\/Dir2\/Dir3\/Dir4\/index.css\n    [parent] => 137064\n    [name] => index.css\n    [mimetype] => text\/css\n    [mimepart] => text\n    [size] => 0\n    [mtime] => 1421402399\n    [storage_mtime] => 1421402399\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54b8e11f71032\n    [permissions] => 27\n)\n \ndata: Array\n(\n    [mimetype] => text\/css\n    [mtime] => 1421402457\n    [size] => 0\n    [etag] => 54b8e15979649\n    [storage_mtime] => 1421402457\n    [permissions] => 27\n    [parent] => 137064\n)\n","level":0,"time":"2015-01-16T10:00:57+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php"}
```

**Comment by zo0ok** [comment]
I got this one too.
I have been running 7.0.2. Upgrade to 7.0.4 did not fix the problem.
Server is Debian Stable on PowerPC, with apache/mysql.
Encryption is activated.

Error behaviours:
Trying to download file with webbrowser: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you. 
The downloading desktop client (Mac OS X): produces a 0-byte file with correct filename.
The uploading client (Ubuntu), when "touch" the file to trigger re-upload: The server did not acknowledge the last chunk. (No e-tag were present)

Renaming the file on the uploading system fixes the problem.

To, me this happened to ~10 out of ~20 .tgz-files with sizes 30kb-10mb when I moved them all into a directory. The first ~10 files where fine, the last not fine, alphabetically.

I was worried this could have happened to random files and be difficult to discover until far too late. But since the desktop client creates a 0-byte file, it is quite easy to search for such files in the owncloud directory. On my Mac OS X client:
$ find ~/owncloud -size 0

**Comment by PVince81** [comment]
The only way I found to reproduce a similar issue was with concurrency:
1. Move a folder into or out of a shared folder
2. While the folder is being moved, rename the source or target folder

See https://github.com/owncloud/core/issues/13330

**Comment by Avalanchediver** [comment]
I am having the same error "The item is not synced because of previous errors: The server did not acknowledge the last chunk. (No e-tag were present)" only for me it is only on larger files.  I am a more elementary user and do not understand a lot of what is posted in the thread above.  Can anyone give me some simple suggestions to resolve my error.  I happens on large video files and a 6GB outlook.pst file I would like to have backed up.

**Comment by guruz** [comment]
@Avalanchediver There is a "Retry sync" button in the settings dialog.

**Comment by viorel-anghel** [comment]
this bug is affecting the core functionality of the product so i have decided to investigate alternatives. found this on the web: http://blog.patshead.com/2014/09/self-hosted-cloud-storage-comparison-2014-edition.html

**Comment by zo0ok** [comment]
@viorel-anghel, I reluctantly keep using ownCloud. I disabled encryption (and decrypted all files, not a process that gave me very much confidence). As it seems to me, encryption is a non-mandatory module, and the problem seems to be with it. So someone might argue that it is not a core functionality. But I agree with you. And I consider alternatives.

**Comment by PVince81** [comment]
It seems you're all using SQLite3 ? And @maste9 had the "database is locked" issue.

The ones of you who are using SQLite on OC 7, please try applying this patch:
https://github.com/owncloud/core/commit/234f33e01e630f763f34c51114d25986bae02b42.patch

**Comment by PVince81** [comment]
Ok some are using MySQL too, not sure about that one.

**Comment by Avalanchediver** [comment]
I have tried re-syncing many times.  The only solution to get it to sync so far has been to move my larger video files out of my folders that are synced.  I know there is no problem with the files as they sync on One-drive just fine.

**Comment by legrx** [comment]
same issue here:

Debian Squeeze-LTS
Owncloud 7.0.4-3
PHP 5.3.3-7+squeeze19
Nginx 1.6.2 w/ Fast-CGI and MySQL-Server

Encryption is on. I would say it's since the Update from 7.0.2-7.0.3:

Files get randomly (don't see a connection by size or file extension) not synced, because users get an E-Tag Error (server did not acknowledge last chunk). It seems to affect users with the windows client. If they try to upload them by web-interface, it says that the file is already there. Which is in fact true, but it's only 8192bytes in size plus dozens of *.parts files. And if they try to overwrite them, owncloud says afterwards, that it can't decrypt it, because the file was previously shared.

It's very weird, i started to disable encryption for now to see if this changes something. i'll see.

**Comment by tflidd** [comment]
I have this error again right now. OS X client (1.7.0). On apache with php module, OC 7.0.4 (encryption enabled).
Client throws error: The server did no acknowledge the last junk. From the client logs (to be found several times):
````
02-05 11:27:01:784 0x104a0eca0 folder.cpp:856   ** error Strings:  (“path/to/file/12_42_16.843.mat: The server did not acknowledge the last chunk. (No e-tag were present)")

02-05 11:27:01:951 0x104a0eca0 socketapi.cpp:372 void Mirall::SocketApi::command_RETRIEVE_FILE_STATUS(const QString &, SocketType *) “/local/path/to/file/12_42_16.843.mat"
02-05 11:27:01:951 0x104a0eca0 socketapi.cpp:572 Mirall::SyncFileStatus Mirall::SocketApi::fileStatus(Mirall::Folder *, const QString &, c_strlist_t *) Could not determine state for file "path/to/file/12_42_16.843.mat" will set STATUS_NEW
02-05 11:27:01:951 0x104a0eca0 socketapi.cpp:320 SocketApi:  Sending message:  "STATUS:NEW:/local/path/to/file/12_42_16.843.mat
````
In the apache-logfile I find:
````
x.x.x.x - user [05/Feb/2015:10:32:50 +0000] "PUT /owncloud/remote.php/webdav/path/to/file/12_42_16.843.mat HTTP/1.1" 302 982 "-" "Mozilla/5.0 (Macintosh) mirall/1.7.0"
```
No php-errors. Restart of client and server, turned off OPCache, nothing helped.
The *.mat is a matlab file containing some data (8 KB). I have similar files in the same folder which already synced without problems. 

I'm still in the state of this error and could provide more information if this can help you...

**Comment by viorel-anghel** [comment]
it seems like my problems were solved by the migration to mysql from sqlite. the good thing is that onwcloud has tools to make this migration very easy: 
http://doc.owncloud.org/server/8.0/admin_manual/maintenance/convert_db.html

**Comment by sleepysmurf** [comment]
I am also have this problem on OwnCloud 7 .4 using the owncloud sync tool on windows version 1.7.1 - E Tag missing.  This is a brand new install on CentOS (nothing else running but the required dependencies)

**Comment by PVince81** [comment]
"E-Tag missing" is the same as "generic server error". Please always include the matching snippet from your "owncloud.log" to see what specific error appeared on the server.
Thanks.

**Comment by sleepysmurf** [comment]
Error	PHP	Session has been closed - no further changes to the session as allowed at /var/www/html/owncloud/lib/private/session/memory.php#80	2015-02-06T05:55:23+00:00
Fatal	remote	An exception occurred while executing 'UPDATE "oc_filecache" SET "size"=? WHERE "fileid" = ?': SQLSTATE[HY000]: General error: 5 database is locked

**Comment by PVince81** [comment]
Aha! "Database is locked": please try the following patches:
- https://github.com/owncloud/core/pull/13832
- https://github.com/owncloud/core/pull/13831

If anyone in this thread is also using SQLite, please also try with these patches. Thanks.

**Comment by RealRancor** [comment]
@sleepysmurf 
See this comment: https://github.com/owncloud/core/issues/12725#issuecomment-73228922

**Comment by tflidd** [comment]
Is there anything I can do with a mysql-database? There are no further errors in owncloud.log, only the clients complains about the last chunk not being acknowledged. The two situations I experienced this error, I was uploading a new folder via the client (once a few files, maybe 10 in Win7, the other one a bigger folder about 400 files and 2.2 GB in size in OS X).

**Comment by PVince81** [comment]
@tflidd it your case it might be a different issue.
Did you try setting "loglevel" to 0 in config.php ? With a bit of luck it will show more output in "owncloud.log" at the time the error happens.

**Comment by tflidd** [comment]
@PVince81 : It is already in the debug mode. Just for clarity, I put everything into the template:
### Steps to reproduce
Upload a new folder with some files in it via the oc-sync-client (Win or OS X)

### Expected behaviour
Sync all files.

### Actual behaviour
Syncs most of the files but at some it comes an error: Server did not acknowledge the last junk.
Now, the clients searches the folders regularly repeating this error over and over again. Restart of client or apache didn't help. I didn't move the file so far. I used the web-interface to upload the file to a different location (outside the sync-folder). This didn't cause any problems.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** Mysql 5.5.41

**PHP version:** 5.5.9

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**  - activity
 - admin_dependencies_chk
 - bookmarks
 - calendar
 - contacts
 - documents
 - external
 - files
 - files_encryption
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - gallery
 - news
 - shorty

**The content of config/config.php:**

````
<?php
define('DEBUG',true);
$CONFIG = array (
  'installed' => true,
  'dbtype' => 'mysql',
  'dbname' => 'xxxx',
  'dbuser' => 'xxxx',
  'dbpassword' => 'xxxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'forcessl' => true,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'trashbin_retention_obligation' => 30,
  'allow_user_to_change_display_name' => true,
  'updatechecker' => true,
  'has_internet_connection' => true,
  'enablebackup' => false,
  'datadirectory' => '/var/www/owncloud/data',
  'version' => '7.0.4.2',
  'installedat' => '1325006970.14',
  'lastupdatedat' => '1329928732.51',
  'loglevel' => '0',
  'logdateformat' => 'F d, Y H:i:s',
  'log_rotate_size' => 504857600,

  'instanceid' => '507effec80781',
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => 'xxxxx',
    1 => 'xxxxx',
  ),
  'appcodechecker' => false,
  'appstoreenabled' => false,
  'asset-pipeline.enabled' => false,
  'overwritewebroot' => '/owncloud',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxxx',
  'secret' => 'xxxx',
  'asset-pipeline.enabled' => true,
);
````

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

### Client configuration
**Operating system:**
I have seen this with the OC Client, latest version 1.7.0 in Windows and OS X. Actually it's the OS X, client hanging.

#### Client Log
https://github.com/owncloud/core/issues/12725#issuecomment-73027794

#### ownCloud log (data/owncloud.log)
nothing!

**Comment by asinteg-daehn** [comment]
Hi,

have the exactly same problem with small files (< 2MB) - and won't spam up the thread with a full report, just:
* Server: Debian Wheezy + PHP 5.4 + Apache 2 + ownCloud 7.0.4 with Encryption and local storage
* Client: Windows 8.1 Pro x64 + ownCloud Client 1.7.1

Is it right that even OC 8 won't bring any benefit / solution for this major problem?

**Comment by asinteg-daehn** [comment]
Update: 
Currently only found a WORKAROUND: Renaming of all affected files.

* open activity dialog of OC Client
* go to each affected file by double clicking on it's error message
* rename it by e.g. a prefix "_" -> "_myfile.txt"
* resync succeeds
* now rename it back
* resync should succeed, too

This is very annoying, but a simple workaround.

Seems, that the database already contains messed up entries for the files - independent from MySQL and SQLite.

**Comment by tflidd** [comment]
@asinteg-daehn Thank you for the hint with the database. I checked my database and in my filecache table, I found that the keyfile is already indexed but not the file itself. The filename is 12_42_16.843.mat. I checked the folder for the keyfiles and there is indeed a keyfile.
So I switched to the directory, and big surprise:
There are more than 1000 files like these two (picked randomly, the sync-client is running in the background all the time since yesterday):
````
-rw-r--r-- 1 www-data www-data  8192 Feb  5 14:05 12_42_16.843.mat.ocTransferId999399742.part
-rw-r--r-- 1 www-data www-data  8192 Feb  5 10:57 12_42_16.843.mat.ocTransferId999969193.part
````
I just compared two of these files and they are identical. They seem to be encrypted (they start with: HBEGIN:cipher:AES-256-CFB:HEND------)
The size of the original file:
````
8347880 24 -rwxrwxrwx   1 user  staff  8238 Jan 26  2012 12_42_16.843.mat
````
So the encrypted data can't contain the file. Would make sense with the problem of the last junk.

**Comment by RealRancor** [comment]
@asinteg-daehn 
> Is it right that even OC 8 won't bring any benefit / solution for this major problem?

See the comment here about this error: https://github.com/owncloud/core/issues/12725#issuecomment-73237082 and note that this is very likely not one "major problem" but rather many different problems resulting in the same error message.

**Comment by felikz3** [comment]
Is anyone at the owncloud company working on this? Because I am getting this error since I updated to the latest version on January and in my opinion it is a serious bug, since one of the core features of owncloud is to provide a secure and **reliable** file synchronization. Well, and unfortunately it is not reliable right now, as I (as well as other users, see above) experience from time to time files that are just not synchronized from one computer to another. And in my opinion, this is a major issue, maybe even the one with highest priority.

**Comment by PVince81** [comment]
This error message is too generic. Need more detail. Please post logs.
Thanks.

**Comment by sleepysmurf** [comment]
The solution seems to be to update the database to the non light version

**Comment by Avalanchediver** [comment]
This issue is making owncloud nearly unusable.  It simply does not synchronize "all" my files.  My only solution has been to eliminate folders from sync that have the files that will not sync. One drive has no issue syncing all my files...

**Comment by themagicm** [comment]
@PVince81  Logs have been attached, so if you want more, you need to be specific.  Having something not sync or just resync over and over and over when the file is clearly there is a bug.

**Comment by PVince81** [comment]
I meant everyone should post logs instead of complaining, because it is likely to be a different issue for everyone. For one it might be a missing etag in the database (did you actually check there?), for another one a failed final rename, for a third a wrong permission, etc, which could all cause the same error message to be displayed but be completely different bugs.

This is why I'd like the message to be changed to "Server error, please check server logs" instead of this misleading message making everyone believe they have the same issue.

If multiple people post their server logs and they do indeed look similar, then we have more data points to analyze the issue. Because so far this could not be reproduced locally (with OC 7.0.4+ and sync client 1.8.0). So the more information, the better.

If the logs are different then they need to be raised as separate tickets to be looked into separately, focusing on one issue at a time.

I hope you now understand why "I have the same issue" isn't useful, because it doesn't tell which of the X possible issues it could be.

Thank you.

**Comment by PVince81** [comment]
I quickly scrolled through (currently on mobile) and it seems that some can already split into
- sqlite with locking issues
- issues with missing encryption keys
- the rest (to be sorted further once info is provided)

These are already candidates to be moved to separate tickets later.

**Comment by RealRancor** [comment]
Maybe could be also added to the list:

* Using gzip on; in NginX is removing ETags completely

See https://github.com/owncloud/documentation/issues/344#issuecomment-77316150 for some infos

* mod_deflate changing etags

After doing some tests it also seems that mod_deflate is changing the e-tag: https://github.com/owncloud/core/issues/4783#issuecomment-77319167. Could this also be related to some of the reports here?

**Comment by PVince81** [comment]
- duplicate entry issue: due to race conditions / concurrency, see https://github.com/owncloud/core/issues/14701 which can also be fix hopefully one day with a proper lock system: https://github.com/owncloud/core/issues/11804
- SQLite cursor issue: also due to concurrency, fix would be to close cursors explicitly, go to here: https://github.com/owncloud/core/issues/10566

**Comment by themagicm** [comment]
@PVince81 ok...got it!  Makes sense.

The issue I have is, the file does get sync'd but for some reason, I still get the same error like the one in this thread.   The file gets sync'd over and over and over...  I'm running SQLite and OwnCloud 7.0.4.2 under CentOS Linux 6.6

I did try your patches #13832, #13831.

If you need more info, just ask, I'll provide.  Thank you for your time!

owncloud log shows:
{"reqId":"54fc573b38ceb","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-03-08T14:05:47+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}

**Comment by PVince81** [comment]
If you use SQLite it is likely that you will either get "database is locked" or "duplicate entry" when running parallel sync. I'd recommend to switch to MySQL, MariaDB or PostgreSQL if possible (there's a convert tool in OC 7: https://doc.owncloud.org/server/7.0/admin_manual/maintenance/convert_db.html)

If you don't, there are some potential fixes on the way to 8.0.3 (hopefully) that should significantly reduce the occurence of such race conditions.

**Comment by themagicm** [comment]
@PVince81 

well.. I went cold turkey and migrated to MySQL.   Then I moved everything from my Owncloud folder out so it can delete all files on the "cloud", then I'll put it all back.  I'll see if moving to MySQL fixed it.

Also..dunno if its just me..but it seems faster accessing owncloud thru the web interface.

**Comment by themagicm** [comment]
Ok..upgrading to MySQL so far has resolved it.  I do not get the problem where a certain file keeps getting sent over and over even though its been sent already.  Hopefully this fixed it.  I'll report back after a week of file syncs.

**Comment by felikz3** [comment]
what do you mean by fix it, @themagicm . that's just a workaround; in my the opinion the guys at owncloud still have to solve this problem.

**Comment by PVince81** [comment]
For SQLite "Database is locked" issues, go to: https://github.com/owncloud/core/issues/10566

**Comment by PatelParas** [comment]
I am facing same issue. I think this issue is related to e-tag calculation.
becoz
1) if i copy file with similar name like newfile.txt --> newfile_1.txt it don't work
2) if i rename file newfile_1.txt --> somethingnew.txt it works and don't give e-tag error.

might be this clue will helpful for developer. 
Thank you

**Comment by PVince81** [comment]
Are you guys still seeing issues with 7.0.7 ?
Many encryption issues were fixed since.

**Comment by PVince81** [comment]
@PatelParas the issue you described sounds like https://github.com/owncloud/core/issues/11127.
This was fixed a long time ago.

**Comment by PVince81** [comment]
Anyone still having issues with 8.1.3 ?

"Database is locked" issues should be gone

**Comment by themagicm** [comment]
I am not experiencing this anymore.

Thank you for the direct email asking, I appreciate it!

-Alex

--------------------------------------------
On Thu, 10/8/15, Vincent Petry <notifications@github.com> wrote:

 Subject: Re: [core] server did not acknowledge the last chunk. (No e-tag were present) (#12725)
 To: "owncloud/core" <core@noreply.github.com>
 Cc: "themagicm" <bartonekdragracing@yahoo.com>
 Date: Thursday, October 8, 2015, 7:58 AM
 
 Anyone still having issues with
 8.1.3 ?
 
 "Database is locked" issues should be gone
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by RealRancor** [comment]
@PVince81 Thats should be solved by the OC-ETag header introduced by oC 8.1.x

**Comment by jaqfneto** [comment]
I installed OC version 8.2.1 and i am unable to upload any file i put in my local folder.

I allways get the error "The server did not acknowledge the last chunk. (No e-tag were present)".

Via browser i have no problems to upload, and all uploaded files that way are automatically downloaded to the local folder in my desktop.

If i create a folder in my ownCloud local folder, the folder is also created in the server.

I am using OC Server v. 8.2.1 and OC client version 2.0.2 for windows

Thanks

**Comment by dsalvanes** [comment]
I am a Linux server Administrator and I use WHM & cPanel. In one account I have OwnCloud and I have this problem (The server did not acknowledge the last chunk). 

I can solve it. It is a problem with ModSecurity. I have activate in ModSecurity Vendors, OWASP ModSecurity Core Rule Set (provider is cPanel). I desactivate it and problem is solved.

I hope this can help to someone.

**Comment by 310TN** [comment]
2 years later:  

![image](https://cloud.githubusercontent.com/assets/18676939/14813142/017010f0-0ba9-11e6-9787-d4dc3088fbbc.png)

Any concrete solution, anyone?

**Comment by PVince81** [comment]
@310TN server logs please + OC version. This message can mean anything.

By the way, is anyone else still seeing such errors in v9.0.1 ?

**Comment by giuppi** [comment]
I'm getting this error.
Clean install v9.0.1

can create folders from both pc and android app
can upload files from web interface

this is the log when i try to upload something from the android app, nothing gets logged from the failed upload using the computer app

`Debug	webdav`

`Exception: {"Message":"HTTP\/1.1 404 File with name .somefile.backup could not be located","Exception":"Sabre\\DAV\\Exception\\NotFound","Code":0,"Trace":"#0 \/home\/user\/public_html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(79): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('.somefile.bac...', 0)\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/home\/user\/public_html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/home\/user\/public_html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#4 \/home\/user\/public_html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(251): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), false)\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpHead(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/home\/user\/public_html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/home\/user\/public_html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:HEAD', Array)\n#8 \/home\/user\/public_html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/home\/user\/public_html\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#10 \/home\/user\/public_html\/owncloud\/remote.php(138): require_once('\/home\/user\/...')\n#11 {main}","File":"\/home\/user\/public_html\/owncloud\/apps\/dav\/lib\/connector\/sabre\/objecttree.php","Line":168,"User":"admin"}`

**Comment by PVince81** [comment]
@giuppi this is a normal message. The Android app first checks whether the file exists by doing a PROPFIND. If the PROPFIND returns 404, then it knows that it can upload without conflict.

This doesn't look related to "server did not acknowledge the last chunk" which is a message from the desktop client, not mobile.

**Comment by PVince81** [comment]
I'm closing this huge ticket for now.

If anyone sees this issue again, please raise a **new** ticket and post all possible details using the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
But first, check the forums or http://owncloud.org/support because in most cases it is a problem in the server environment and not a bug.
Also note that many of the actual bugs that used to cause this error message have already been fixed.

Please always open a new ticket, unless an existing one contains the same exception or log entries from your owncloud.log, in which case the cause is the same.

Thank you!

**Comment by j4hangir** [comment]
For anyone who might still be tackling with this issue, in our setup `ownCloud 9.1.0` the culprit was **mod_security** which was filtering certain files.
