### ISSUE TITLE
Package upgrade failed going from 7.0.4 to 8.0

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13835]
### Steps to reproduce

1. Install and configure 7.0.4 using the package 

```
wget http://download.opensuse.org/repositories/isv:/ownCloud:community:7.0/xUbuntu_14.04/Release.key
sudo apt-key add - < Release.key
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/7.0/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud.list
sudo apt-get install owncloud
```

2. Complete configuration of owncloud by logging in.  I also created a user.

3. Upgrade to 8.0 using the package

```
wget --http-user=<un> --http-passwd=<pw> http://x.x.x.x/ee:/8.0/xUbuntu_14.04/Release.key
sudo apt-key add - < Release.key
sudo sh -c "echo 'deb http://<un>:<pw>@x.x.x.x/ee:/8.0/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud.list"
sudo apt-get upgrade owncloud

```

### Expected behaviour

Upgrade should be successful

### Actual behaviour

Upgrade fails with:

```

Errors were encountered while processing:
 /var/cache/apt/archives/owncloud-server_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-config-apache_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-activity_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-files-encryption_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-files-pdfviewer_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-files-trashbin_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-firstrunwizard_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-templateeditor_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-user-ldap_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-external_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-files-external_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-files-sharing_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-files-versions_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-gallery_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-updater_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-user-webdavauth_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-files-texteditor_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-files-videoviewer_8.0.0~RC1-1_amd64.deb
 /var/cache/apt/archives/owncloud-app-user-external_8.0.0~RC1-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)


```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud 7.0.4 (stable)

**Comment by MorrisJobke** [comment]
@jnweiger

**Comment by MorrisJobke** [comment]
@karlitschek @DeepDiver1975 This could become a showstopper.

**Comment by karlitschek** [comment]
agreed. showstopper

**Comment by jnweiger** [comment]
@jnfrmarks I dont see an error in the logs. dpkg only claims there is an error, but does not print anything helpful. Do you have the full log? Would a fresh install work?

**Comment by DeepDiver1975** [comment]
@jnfrmarks for more logs please have a look at:

/var/log/apt/term.log
/var/log/dpkg.log

**Comment by jnfrmarks** [comment]
This was from a fresh install.  I will go hunt out the logs and attach any relevant data.

**Comment by jnweiger** [comment]
Reproducing ...
<pre>
obs-docker-install isv:ownCloud:community:7.0 owncloud xUbuntu_14.04
docker run -ti owncloud-7.0.4-3-xubuntu_14.04
wget -nv http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/Release.key -O Release.key
apt-key add - < Release.key
echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0//xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud.list
apt-get update
apt-get upgrade owncloud
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  owncloud-app-activity owncloud-app-external owncloud-app-files-encryption
  owncloud-app-files-external owncloud-app-files-locking
  owncloud-app-files-pdfviewer owncloud-app-files-sharing
  owncloud-app-files-texteditor owncloud-app-files-trashbin
  owncloud-app-files-versions owncloud-app-files-videoviewer
  owncloud-app-firstrunwizard owncloud-app-gallery
  owncloud-app-provisioning-api owncloud-app-templateeditor
  owncloud-app-updater owncloud-app-user-external owncloud-app-user-ldap
  owncloud-app-user-webdavauth owncloud-config-apache owncloud-server
The following packages will be upgraded:
  owncloud
1 upgraded, 21 newly installed, 0 to remove and 0 not upgraded.
Need to get 12.0 MB of archives.
After this operation, 60.6 MB disk space will be freed.
Do you want to continue? [Y/n] y
Preparing to unpack .../owncloud-server_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-server (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-server_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/index.php', which is also in package owncloud 7.0.4-3
<pre>

There is the error message! 7.0.4 did not get uninstalled, and thus conflicts.

**Comment by jnweiger** [comment]
I don't understand comment https://github.com/owncloud/core/issue_comments/72638302 -- conflicts cannot happen on a fresh install, can only happen in update.

**Comment by MorrisJobke** [comment]
@jnweiger I guess @jnfrmarks meant that it was a fresh install of 7.0.4 and then she upgraded and this happened ;)

**Comment by jnfrmarks** [comment]
@MorrisJobke @jnweiger 

Correct - it was a fresh install of 7.0.4 then an upgrade to 8.0.0

Sounds like the error has been reproduced.

**Comment by jnweiger** [comment]
Fixed by commit #60 in isv:ownCloud:community:8.0 owncloud

**Comment by Raydiation** [comment]
As it seems this is fixed I'm closing this issue.

Reopen if problems are still present

**Comment by MorrisJobke** [comment]
It currently upgrades here ... let's see

**Comment by MorrisJobke** [comment]
```
apt-get install owncloud
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  owncloud-app-activity owncloud-app-external owncloud-app-files-encryption
  owncloud-app-files-external owncloud-app-files-locking
  owncloud-app-files-pdfviewer owncloud-app-files-sharing
  owncloud-app-files-texteditor owncloud-app-files-trashbin
  owncloud-app-files-versions owncloud-app-files-videoviewer
  owncloud-app-firstrunwizard owncloud-app-gallery
  owncloud-app-provisioning-api owncloud-app-templateeditor
  owncloud-app-updater owncloud-app-user-external owncloud-app-user-ldap
  owncloud-app-user-webdavauth owncloud-config-apache owncloud-server
Suggested packages:
  clamav clamav-daemon smbclient libreoffice-writer libav-tools ffmpeg
The following NEW packages will be installed:
  owncloud-app-activity owncloud-app-external owncloud-app-files-encryption
  owncloud-app-files-external owncloud-app-files-locking
  owncloud-app-files-pdfviewer owncloud-app-files-sharing
  owncloud-app-files-texteditor owncloud-app-files-trashbin
  owncloud-app-files-versions owncloud-app-files-videoviewer
  owncloud-app-firstrunwizard owncloud-app-gallery
  owncloud-app-provisioning-api owncloud-app-templateeditor
  owncloud-app-updater owncloud-app-user-external owncloud-app-user-ldap
  owncloud-app-user-webdavauth owncloud-config-apache owncloud-server
The following packages will be upgraded:
  owncloud
1 upgraded, 21 newly installed, 0 to remove and 2 not upgraded.
Need to get 12.0 MB of archives.
After this operation, 60.6 MB disk space will be freed.
Do you want to continue? [Y/n] 
Get:1 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-server 8.0.0~RC1-1 [8023 kB]
Get:2 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-config-apache 8.0.0~RC1-1 [3058 B]
Get:3 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-activity 8.0.0~RC1-1 [76.1 kB]
Get:4 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-files-encryption 8.0.0~RC1-1 [112 kB]
Get:5 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-files-pdfviewer 8.0.0~RC1-1 [1647 kB]
Get:6 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-files-trashbin 8.0.0~RC1-1 [38.0 kB]
Get:7 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-firstrunwizard 8.0.0~RC1-1 [39.5 kB]
Get:8 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-templateeditor 8.0.0~RC1-1 [21.8 kB]
Get:9 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-user-ldap 8.0.0~RC1-1 [189 kB]
Get:10 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-external 8.0.0~RC1-1 [25.7 kB]
Get:11 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-files-external 8.0.0~RC1-1 [525 kB]
Get:12 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-files-sharing 8.0.0~RC1-1 [103 kB]
Get:13 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-files-versions 8.0.0~RC1-1 [25.8 kB]
Get:14 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-gallery 8.0.0~RC1-1 [36.4 kB]
Get:15 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-updater 8.0.0~RC1-1 [163 kB]
Get:16 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-user-webdavauth 8.0.0~RC1-1 [18.5 kB]
Get:17 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-files-locking 8.0.0~RC1-1 [8662 B]
Get:18 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-files-texteditor 8.0.0~RC1-1 [748 kB]
Get:19 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-files-videoviewer 8.0.0~RC1-1 [165 kB]
Get:20 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-provisioning-api 8.0.0~RC1-1 [9074 B]
Get:21 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud-app-user-external 8.0.0~RC1-1 [5256 B]
Get:22 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/  owncloud 8.0.0~RC1-1 [1568 B]
Fetched 12.0 MB in 7min 51s (25.4 kB/s)                                        
Selecting previously unselected package owncloud-server.
(Reading database ... 28148 files and directories currently installed.)
Preparing to unpack .../owncloud-server_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-server (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-server_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/index.php', which is also in package owncloud 7.0.4-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package owncloud-config-apache.
Preparing to unpack .../owncloud-config-apache_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-config-apache (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-config-apache_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/.htaccess', which is also in package owncloud 7.0.4-3
Selecting previously unselected package owncloud-app-activity.
Preparing to unpack .../owncloud-app-activity_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-activity (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-activity_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/activity/appinfo/app.php', which is also in package owncloud 7.0.4-3
Selecting previously unselected package owncloud-app-files-encryption.
Preparing to unpack .../owncloud-app-files-encryption_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-files-encryption (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-files-encryption_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/files_encryption/files/error.php', which is also in package owncloud 7.0.4-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package owncloud-app-files-pdfviewer.
Preparing to unpack .../owncloud-app-files-pdfviewer_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-files-pdfviewer (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-files-pdfviewer_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/files_pdfviewer/appinfo/app.php', which is also in package owncloud 7.0.4-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package owncloud-app-files-trashbin.
Preparing to unpack .../owncloud-app-files-trashbin_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-files-trashbin (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-files-trashbin_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/files_trashbin/appinfo/app.php', which is also in package owncloud 7.0.4-3
Selecting previously unselected package owncloud-app-firstrunwizard.
Preparing to unpack .../owncloud-app-firstrunwizard_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-firstrunwizard (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-firstrunwizard_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/firstrunwizard/appinfo/app.php', which is also in package owncloud 7.0.4-3
Selecting previously unselected package owncloud-app-templateeditor.
Preparing to unpack .../owncloud-app-templateeditor_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-templateeditor (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-templateeditor_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/templateeditor/appinfo/app.php', which is also in package owncloud 7.0.4-3
Selecting previously unselected package owncloud-app-user-ldap.
Preparing to unpack .../owncloud-app-user-ldap_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-user-ldap (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-user-ldap_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/user_ldap/appinfo/app.php', which is also in package owncloud 7.0.4-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package owncloud-app-external.
Preparing to unpack .../owncloud-app-external_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-external (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-external_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/external/appinfo/app.php', which is also in package owncloud 7.0.4-3
Selecting previously unselected package owncloud-app-files-external.
Preparing to unpack .../owncloud-app-files-external_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-files-external (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-files-external_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/files_external/appinfo/app.php', which is also in package owncloud 7.0.4-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package owncloud-app-files-sharing.
Preparing to unpack .../owncloud-app-files-sharing_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-files-sharing (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-files-sharing_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/files_sharing/appinfo/app.php', which is also in package owncloud 7.0.4-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package owncloud-app-files-versions.
Preparing to unpack .../owncloud-app-files-versions_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-files-versions (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-files-versions_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/files_versions/appinfo/app.php', which is also in package owncloud 7.0.4-3
Selecting previously unselected package owncloud-app-gallery.
Preparing to unpack .../owncloud-app-gallery_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-gallery (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-gallery_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/gallery/appinfo/app.php', which is also in package owncloud 7.0.4-3
Selecting previously unselected package owncloud-app-updater.
Preparing to unpack .../owncloud-app-updater_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-updater (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-updater_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/updater/appinfo/app.php', which is also in package owncloud 7.0.4-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package owncloud-app-user-webdavauth.
Preparing to unpack .../owncloud-app-user-webdavauth_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-user-webdavauth (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-user-webdavauth_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/user_webdavauth/appinfo/app.php', which is also in package owncloud 7.0.4-3
Selecting previously unselected package owncloud-app-files-locking.
Preparing to unpack .../owncloud-app-files-locking_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-files-locking (8.0.0~RC1-1) ...
Selecting previously unselected package owncloud-app-files-texteditor.
Preparing to unpack .../owncloud-app-files-texteditor_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-files-texteditor (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-files-texteditor_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/files_texteditor/appinfo/app.php', which is also in package owncloud 7.0.4-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package owncloud-app-files-videoviewer.
Preparing to unpack .../owncloud-app-files-videoviewer_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-files-videoviewer (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-files-videoviewer_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/files_videoviewer/appinfo/app.php', which is also in package owncloud 7.0.4-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package owncloud-app-provisioning-api.
Preparing to unpack .../owncloud-app-provisioning-api_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-provisioning-api (8.0.0~RC1-1) ...
Selecting previously unselected package owncloud-app-user-external.
Preparing to unpack .../owncloud-app-user-external_8.0.0~RC1-1_amd64.deb ...
Unpacking owncloud-app-user-external (8.0.0~RC1-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-app-user-external_8.0.0~RC1-1_amd64.deb (--unpack):
 trying to overwrite '/var/www/owncloud/apps/user_external/appinfo/app.php', which is also in package owncloud 7.0.4-3
Preparing to unpack .../owncloud_8.0.0~RC1-1_all.deb ...
Unpacking owncloud (8.0.0~RC1-1) over (7.0.4-3) ...
dpkg: warning: unable to delete old directory '/etc/apache2/conf.d': Directory not empty
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I just installed oc 7 like @jnfrmarks  and then changed the repo path (replace 7 by 8) and loaded the new key. -> still a problem

cc @jnweiger

**Comment by RealRancor** [comment]
@MorrisJobke 
Seems the fix by @jnweiger wasn't included yet when you have tried that.

Its only fixed in owncloud_8.0.0~RC1-2_all but not in owncloud_8.0.0~RC1-1_all which was used in your case:

https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.0/owncloud/debian.changelog?expand=1

**Comment by MorrisJobke** [comment]
@RealRancor Yes. Thanks for pointing our. Now it worked :+1:

**Comment by jnweiger** [comment]
My reproducer now also succeeds.  Confirmed fixed! Yeah!
Tested with Ubuntu 14.04 CentOS-6 openSUSE-13.2
