### ISSUE TITLE
ownCloud upgrade 5.0.14 to 7.04 

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#13957]
#### Expected behavior
1. Manual upgrade path of Owncloud 5.0.14->5.0.18->6.0.6->7.0.4. 
2. In testing, upgrade worked flawlessly. 
3. In production, upgrade was successful and most users were happy 
4. Next day we received complaints that some users could not see their files. I regenerated the file_cache and this resolved their issues
5. We then received reports that some shares for some users are not accessible.

The problem is with the oc_storages database and an inconsistency in how the id value is generated and searched. 

In our oc_storages table, some users have an id value that looks like an md5 hash and some have an entry of the form "home::<GUID>". For example, my oc_storage entry is:
```
+----------------------------------+------------+
| id | numeric_id |
+----------------------------------+------------+
| da8d001d43de3e426e30f22ef14b251d | 5 |
+----------------------------------+------------+
```
And a user with the issue has 
```
+--------------------------------------------+------------+
| id | numeric_id |
+--------------------------------------------+------------+
| home::F10E0A54-3E55-4987-AAAF-F3FB7C6D95E9 | 483 |
+--------------------------------------------+------------+
```
After the upgrade, the user with numeric_id was allocated a new storage at
```
+----------------------------------+------------+
| id | numeric_id |
+----------------------------------+------------+
|d405b43cd27c23342fd7ed378455707a | 766 |
+----------------------------------+------------+
```
Yet they could still access their files on storage id 483 and the oc_filecache for 766 only had 3 entries. 

The real problem occurs when a user tries to access a share. The search for the mount point in this case does a search on the hash d405b43cd27c23342fd7ed378455707a instead of home:: F10E0A54-3E55-4987-AAAF-F3FB7C6D95E9 and gets a storage ID of 766 but all of the shares point to fields with storage 483.

 This generates the error {"app":"files_sharing","message":"Unable to get mount for shared storage '483' user 'F10E0A54-3E55-4987-AAAF-F3FB7C6D95E9'","level":3,"time":"2015-02-05T19:06:14+00:00"}. 

As soon as the entry for 766 is removed everything starts functioning again.

Owncloud has been in production for several days and quite active so reverting to a backup and earlier version at this point is not an option but I do still have the backups that I have been using for my investigations. To compound the problem, some students have discovered that recreating shares works so we now have a mix of shares pointing to files with the old storage id and new storage id. 

I need to be able to reconcile the new IDs with the old IDs to fix the problem but need to know a few things before a script can be generated:

1. How is the hash generated? What string format is used to generate the storage hash? This will help me line up the home::<GUID> with the new IDs
2. What would happen if I changed the storage in the oc_filecache from new storage to old storage? The tree should be fine except that a user will now have two parent nodes. Those need to be reconciled somehow. 
3. Which id is supposed to be used in the oc_storages? The existence of the two types of IDs is concerning to me because inconsistency is what causes problems like this. It masked our testing because our tests were using accounts and shares with the hash instead of home::<GUID>.

#### Actual behavior
every user should able to share/view  folder

#### Steps to reproduce
 This issue is  ongoing upgrade issue 
####  Server configuration
Operating system: Ubuntu 12.04.5 LTS

Web server: 2.2.22-1ubuntu1.7

Database: MySQL 5.5.41-0ubuntu0.12.04.1

PHP version: 5.3.10-1ubuntu3.15

ownCloud version: 7.0.4 (stable)

Storage backend: Local storage ext4 filesystem - VMware raw disk mapped LUN on SAN

Client configuration:

Client version: Varied - web interface and all sync clients affected

Operating system: Windows, Linux, Mac, Android, iPad

OS language: Varied but mostly English

Installation path of client: default
#### Log
Log can be found at S3/shared/ownCloud/support/github-issue/core/13957

**Comment by DeepDiver1975** [comment]
duplicate of the ldap uid issue most probably @blizzz

**Comment by iliyasbasir** [comment]
@MorrisJobke : customer place new pseudo code  need intimidate help ..can you please look this asap
thank you in advanced for help

**Comment by blizzz** [comment]
Sounds like dup of https://github.com/owncloud/core/issues/12801 fix discussed here https://github.com/owncloud/core/pull/13865

( @DeepDiver1975 the uid thing was assumed, but in facts it's user backends not being enabled on upgrade)

**Comment by butonic** [comment]
Similar to https://github.com/owncloud/core/issues/12801. Running "occ files:scan --all" in this case killed all shares. Now the customer did send useful information: three very specific questions and a pseudocode version of what he intends to do. @blizzz @PVince81 please have a look:
```
uuid_list := select owncloud_name from oc_ldap_user_mapping

foreach uuid in uuid_list	
// get the oc_storage ID of form home::<uuid>
home_id := select id from oc_storages where id like 'home::<uuid>'
if home_id exists
then
home_numeric_id := select numeric_id from oc_storages where id like 'home::<uuid>'
// create the storage hash that was generated for the ID
hash := md5(/var/www/owncloud-enterprise/data/<uuid>/)
//check and see if a numeric_id exists for this UUID's storage hash
hash_numeric_id := select numeric_id from oc_storages where id like '<hash>'
if hash_numeric_id exists
// this one is a duplicate, find which id is the smallest because that will be the one that we want to keep
if home_numeric_id < hash_numeric_id then
id_to_remove := hash_numeric_id
id_to_keep := home_numeric_id
else
id_to_remove := home_numeric_id
id_to_keep := hash_numeric_id
endif

// find the root nodes of the storage ids
root_to_remove := select fileid from oc_filecache where storage = <id_to_remove> and parent = -1;
root_to_keep := select fileid from oc_filecache where storage = <id_to_keep> and parent = -1;
// change all of the file cache entries to the id to keep 
execute query update oc_filecache set storage = <id_to_keep> where storage = <id_to_remove> and parent != -1
// change the parents of the file entries below the root nodes
execute query update oc_filecache set parent= <root_to_keep> where parent = <root_to_remove> 

// all oc_filecache entries to old storage should be gone except for the root node. This can
// be a good assertion to check if wanting to test.
execute query delete from oc_filecache where storage = <id_to_remove> and parent = -1
execute query delete from oc_storages where numeric_id = <id_to_remove>	
endif
endif
end foreach
```

The question is no longer what caused this but how we can fix the broken storages. First let us try to answer his three questions.

@iliyasbasir I think this code is dangerous, as it will likely create duplicate entries for files in the same storage. 

@PVince81 @blizzz I don't know where the md5 storage ids come from (shares? shouldn't they be prefixed withe `share::`, why don't they have a prefix in the first place?) I would leave out the second part of his script and only use the home:: storage. Throw away the new fileids and shares that have been created in the last two days. They xill either loose old shares or new shares ... I'd go with the latter. Opinions, other solutions?

**Comment by PVince81** [comment]
I think the easiest would be to change the numeric_id in oc_storages to whatever is expected and not touch the oc_filecache table at all. (the numeric_id isn't used elsewhere AFAIK and this is how our repair step does it).

Yes, they will lose either the shares of the old storage or of the new storage, there is no reliable way of keeping both.

The md5 storage id has nothing to do with shares. It is only used whenever the length of real storage id > 64. Basically: if len(storage_id) > 64 then storage_id = md5(storage_id). See https://github.com/owncloud/core/blob/master/lib/private/files/cache/cache.php#L49

It should be md5('local::/var/www/owncloud-enterprise/data/<uuid>/') (the "local::" prefix is missing).
One thing I don't understand in the script above is it seems that it's always using md5() for the "local::" based storage. It should normally first check if len('local::/var/www/owncloud-enterprise/data/<uuid>/') > 64 before using the md5.

**Comment by iliyasbasir** [comment]
@PVince81 @blizzz @butonic 
1. I can confirm there are duplicate entries for some users. is any  way to reconcile those by examining the path and seeing if there is a duplicate. My concern here are the versions.
2. This was  first idea but  cannot change the numeric_id of the new id because the numeric_id is the primary key: 

+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| id         | varchar(64) | YES  | UNI | NULL    |                |
| numeric_id | int(11)     | NO   | PRI | NULL    | auto_increment |
+------------+-------------+------+-----+---------+----------------+

3. they already lost the shares. they plan keep both

**Comment by iliyasbasir** [comment]
@butonic @PVince81 @MorrisJobke 
#### help request
I have customer test few query here is result and is concerns ....

Here are the results of the two permission select queries although I am not sure what information these are supposed to give us to resolve the issue other than scope of the size of the filecache and possibly the state of it:

SELECT permissions, count(*) FROM oc_storages AS s JOIN oc_filecache AS fc ON s.numeric_id = fc.storage WHERE s.id LIKE 'local%' GROUP BY permissions;
+-------------+----------+
| permissions | count(*) |
+-------------+----------+
|           0 |      206 |
|          27 |       14 |
|          31 |       22 |
+-------------+----------+
3 rows in set (0.00 sec)

SELECT permissions, count(*) FROM oc_storages AS s JOIN oc_filecache AS fc ON s.numeric_id = fc.storage WHERE s.id LIKE 'home%' GROUP BY permissions;
+-------------+----------+
| permissions | count(*) |
+-------------+----------+
|           0 |    83449 |
|           3 |       17 |
|           7 |      370 |
|          11 |        1 |
|          17 |     1206 |
|          23 |        5 |
|          25 |        4 |
|          27 |    13921 |
|          31 |     4623 |
+-------------+----------+
9 rows in set (0.68 sec)

This still does not encapsulate all users, though, because a good number have an id that is an md5 hash which is not found by your queries. 

The rest of the selects (and selects that the delete statements act upon) yield empty sets. 

As stated in my example before:

==== Start Example ====
The problem is with the oc_storages database and an inconsistency in how the id value is generated and searched. 

In our oc_storages table, some users have an id value that looks like an md5 hash and some have an entry of the form "home::<GUID>".  For example, my oc_storage entry (which has no issue) is:
+----------------------------------+------------+
| id                               | numeric_id |
+----------------------------------+------------+
| da8d001d43de3e426e30f22ef14b251d |          5 |
+----------------------------------+------------+

And a user with the issue has 

+--------------------------------------------+------------+
| id                                         | numeric_id |
+--------------------------------------------+------------+
| home::F10E0A54-3E55-4987-AAAF-F3FB7C6D95E9 |        483 |
+--------------------------------------------+------------+

After the upgrade, the user with id numeric_id was allocated a new storage at
+----------------------------------+------------+
| id                               | numeric_id |
+----------------------------------+------------+
|d405b43cd27c23342fd7ed378455707a  |        766 |
+----------------------------------+------------+

Yet they could still access their files on storage id 483 and the oc_filecache for 766 only had 3 entries. 

The real problem occurs when a user tries to access a share. The search for the mount point in this case does a search on the hash d405b43cd27c23342fd7ed378455707a instead of home:: F10E0A54-3E55-4987-AAAF-F3FB7C6D95E9 and gets a storage ID of 766 but all of the shares point to fields with storage 483. This generates the error {"app":"files_sharing","message":"Unable to get mount for shared storage '483' user 'F10E0A54-3E55-4987-AAAF-F3FB7C6D95E9'","level":3,"time":"2015-02-05T19:06:14+00:00"}. 

As soon as the entry for 766 is removed everything starts functioning again.
==== end example ====

Perhaps I was not clear enough on what our issue is to begin with. 

Before the upgrade, User F10E0A54-3E55-4987-AAAF-F3FB7C6D95E9 had only one storage with numeric_id=483. After the upgrade, this user now has two storages 

+--------------------------------------------+------------+
| id                                         | numeric_id |
+--------------------------------------------+------------+
| home::F10E0A54-3E55-4987-AAAF-F3FB7C6D95E9 |        483 |
|d405b43cd27c23342fd7ed378455707a  |        766 |
+--------------------------------------------+------------+

and the second one is the one that is searched for when detecting user shares because it is the hash of local::/var/www/owncloud-enterprise/data/F10E0A54-3E55-4987-AAAF-F3FB7C6D95E9/ which maps to d405b43cd27c23342fd7ed378455707a  and gives a numeric_id of 766 but all of the shares are to files that are on storage 483 so no shares are shown.  This is indicated in the mysql logs and Owncloud logs that I sent earlier. 

All files in oc_filecache belong to a storage, it's just that some files for a user belong to one storage and some files for the same user belong to the second, newly created storage because it has been actively used now and a file sync has been done. What we need to do is move the files from the newly created storage numeric_id to the original storage numeric_id and remove the parent node with numeric_id of the new storage. This will potentially cause duplicates which we will need a way to remediate.  

### So, in point form here is the problem:

1. SOME users (not all) now have two storages for the same local storage
2. When trying to mount the shares, the mount code searches for and only gets the newer storage, not the older one, and cannot mount the older shares
3. Users have been using the system for a few days until the issue was reported so some newly created files (and shares) have the new storage IDs in addition to the original IDs.

### And here is what we need:

1. A way to move all of the newly created files from the new storage to the old storage (or vice-versa)  
2. Remove any duplicates that were created in this move. 
3. Remove the newly created storages.

**Comment by LukasReschke** [comment]
@iliyasbasir I formatted the report. Please use ``` in the future for code blocks. For some markdown introduction see https://guides.github.com/features/mastering-markdown/#examples

**Comment by iliyasbasir** [comment]
@LukasReschke  Thank you...

**Comment by PVince81** [comment]
@iliyasbasir a few points:

- You are saying that the user already had a storage "home::xxx" but after the upgrade a new one appeared. This is the problem number 2) here: https://github.com/owncloud/enterprise/issues/525#issuecomment-74068468 (there are steps how to fix it without rolling back, CC @bboule)

- the md5 hash is actually the md5(real_storage_id). This means that to find the storage id of every user, you need to take the user name of every user and then do
   - md5("local::$datadir/" + userId) (for the old style storages)
   - md5("home::" + userId) (for the new style storages)

Yes... this is so messy...

**Comment by PVince81** [comment]
@iliyasbasir have they ever moved the "datadir" ? If yes, does "oc_storages" contain any entry like "local::$oldDataDir/$user" with a data dir that doesn't match with the one in config.php ?
If yes, then it's bug 1) here https://github.com/owncloud/enterprise/issues/525#issuecomment-74068468

But the symptoms you describe seem to match case 2). These only happened after the 6.0.6->7.0.4 upgrade, right ? And the data dir wasn't moved/renamed ? If yes, then it's definitely case 2) here 
https://github.com/owncloud/enterprise/issues/525#issuecomment-74068468

**Comment by DeepDiver1975** [comment]
moving to 7.0.6 - 7.0.5 is almost shipped

**Comment by iliyasbasir** [comment]
Hope Fully ...7.0.5 will resolved issue 

Thank you
-iliyas

**Comment by gig13** [comment]
Continuing to see share file display issues.

1. Yes. A good example in the data provided are shares with ids 2147-2149,2181-2195.
2. It isn't when he enters the name, just when he views who the folder is shared with. I have requested a screenshot from Dave so that you can see the exact behaviour and will forward it on when I receive it.
3. Dave created the folders and shares. It was not a matter of re-sharing. The shares show up in oc_share but they do not show up as shares in his Owncloud user interface. Those shares are 2181-2195.

Also see screenshots and database extracts from: 
https://s3.owncloud.com/owncloud/index.php/apps/files/?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F14835

**Comment by PVince81** [comment]
@MorrisJobke does your script also detect orphaned shares ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke does your script also detect orphaned shares ?

No

**Comment by gig13** [comment]
@PVince81 
Do you need any additional information?

**Comment by PVince81** [comment]
Can you elaborate on "do not show up as shares in his Owncloud user interface" ?
Do you mean:
- in the share dropdown ?
- in the files app (All files)
- in the "Shared with you" or "Shared with others" section ?

Or do you mean the files are shared with others (the user is the owner) but when opening the share dropdown, nothing shows up as if the file did not have any outgoing shares ?

**Comment by PVince81** [comment]
I'm asking this detail because these sections are using different APIs, so if only one is defect then it could be a bug in the specific API.

**Comment by gig13** [comment]
@PVince81 
They are denied access in some cases (just timesout in the web).

**Comment by PVince81** [comment]
Hmmm... denied access in the form of a timeout ?
Or are they going to "Shared with you", see the share there, then click, it redirects to "All files" but land in the root ?

**Comment by MorrisJobke** [comment]
I would say this is the same stuff we experienced and fixed with #15332. The symptoms looks similiar.

**Comment by craigpg** [comment]
Clearing milestone assignment since we think it's fixed in #15332.

**Comment by MorrisJobke** [comment]
@gig13 Can you test this again with the upcoming 7.0.6? Thanks :)

**Comment by cmonteroluque** [comment]
@gig13 please test so we can determine next steps

**Comment by bboule** [comment]
@cmonteroluque

This is still a problem.  Let me describe what I did:

From 5.0.19 which I connected to LDAP and took two user creates and created some files and some shares
Took the stable 6 nightly and popped that over and processed an upgrade (at this point shares are gone along with files)
Then I upgraded to what I grabbed from Stable7 from the download internal site (nightly) 
Processed an upgrade from there still not file still no shares

I am not sure if I grabbed the wrong code?  Happy to walk through what I did in greater detail?

Bob

**Comment by blizzz** [comment]
> Took the stable 6 nightly and popped that over

as in copied it over the OC 5 stuff? This is the wrong and not supported way of a major release upgrade, because it is error prone. You might end up with old, un-removed files that might be included instead of new valid ones. Undeterminable side effects. See [Upgrade to OC 6](https://doc.owncloud.org/server/6.0/admin_manual/maintenance/update.html#upgrade) and [Upgrade to OC 7](https://doc.owncloud.org/server/7.0/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure)

**Comment by cmonteroluque** [comment]
@bboule @MorrisJobke thoughts?

**Comment by MorrisJobke** [comment]
> @bboule @MorrisJobke thoughts?

First of all we need to verify that the upgrade was done in a proper way (copy over stuff, but remove old and unzip new code)

**Comment by bboule** [comment]
Hey Guys... sorry for the delay...  Let me tell you what I did...

From a 5.0.9 instance, I copied in the the code from stable 6 to the ownCloud sever
Copy the config file and data directory from the OC 5 instance over to the OC6 instance
Named the folders (5 became owncloud_bak 6 became owncloud)
Hit the log in page (no one is on this box it is my VM) and kicked of the upgrade
upgrade starts and completes
When I login shares are no longer available (can't be see from files app)
Move forward with the same process as I jump from 6 to 7 again grabbing the 7 code from the nightly build
Upgrade is processed but shares are still not visible to the user

Let me know if I need to do something different here in terms of a test happy to adjust

**Comment by cmonteroluque** [comment]
@blizzz anything wrong with @bboule upgrade description?

**Comment by blizzz** [comment]
How the upgrade was done sounds OK.

>  When I login shares are no longer available (can't be see from files app)

In that case we have an issue on the upgrade from 5 to 6 already.

#15332 would not help in this case as it only goes into stable7. We could try to backport it to stable6 (if it makes sense at all). OTOH it's a big change and stable6 is on security-patch-only mode.

**Comment by cmonteroluque** [comment]
@bboule, ok from GCX?

**Comment by SergioBertolinSG** [comment]
Using oC 7.0.7 with LDAP server well configured, after stopping the ldap server oC keeps trying to connect forever. No warning messages shown.
