### ISSUE TITLE
Files app missing in repositories

### ISSUE THREAD

**Issue by twouters** [owncloud/core#13991]
Looks like the files app isn't installed if you install owncloud from the opensuse build repo's.
At least on Debian and Ubuntu. I haven't checked other setups.

See issue:13903 (contains related PHP error)

    PHP Fatal error:  Class 'OCA\Files\App' not found in /var/www/owncloud/apps/files_sharing/appinfo/app.php on line 37

There is no `/var/www/owncloud/apps/files` directory.

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by twouters** [comment]
owncloud-app-files is not listed as a dependency for owncloud.

~~~
# apt-cache show owncloud
Package: owncloud
Version: 8.0.0-1
Architecture: all
Maintainer: Jürgen Weigert <jw@owncloud.com>
Installed-Size: 25
Depends: owncloud-server, owncloud-config-apache, owncloud-3rdparty, owncloud-app-activity, owncloud-app-files-encryption, owncloud-app-files-pdfviewer, owncloud-app-files-trashbin, owncloud-app-firstrunwizard, owncloud-app-templateeditor, owncloud-app-user-ldap, owncloud-app-external, owncloud-app-files-external, owncloud-app-files-sharing, owncloud-app-files-versions, owncloud-app-gallery, owncloud-app-updater, owncloud-app-user-webdavauth, owncloud-app-files-locking, owncloud-app-files-texteditor, owncloud-app-files-videoviewer, owncloud-app-provisioning-api, owncloud-app-user-external
Recommends: mysql-server, curl, exim4 | mail-transport-agent, php5-apcu | php5-apc
Suggests: clamav | clamav-daemon, smbclient, libreoffice-writer
Conflicts: owncloud-fhs

**Comment by twouters** [comment]
Just checked https://build.opensuse.org/package/show/isv:ownCloud:community/owncloud and only Ubuntu and Debian seem to be affected (all OS versions)

**Comment by LukasReschke** [comment]
@jnweiger Any chance we can get this fixed soon? – We get flooded by reports of the same issue ;-)

cc @karlitschek @DeepDiver1975  FYI ownCloud 8 packages are completely broken on Debian and Ubuntu.

**Comment by MoSpuddy** [comment]
$ sudo -u www-data php occ upgrade
Turned on maintenance mode
Checked database schema update
Updated database
PHP Fatal error:  Class 'OCA\Files\App' not found in /var/www/owncloud/apps/files_sharing/appinfo/app.php on line 37

**Comment by jnweiger** [comment]
The package owncloud-app-files is missing in debian.control file.

**Comment by karlitschek** [comment]
:-( Would be great to have this fixed soon.

**Comment by kulve** [comment]
Is is possible to just copy some files to the missing directory and install the proper package later?

**Comment by jnweiger** [comment]
Fixed in OBS. Committed revision 79. Next rebuild should have version 8.0.0-2 

Thanks for the qualified report! I hope, this solves some of the unclear blank page issues.

**Comment by jnweiger** [comment]
@kulve you can manually install https://api.opensuse.org/build/isv:ownCloud:community:8.0/xUbuntu_14.04/x86_64/owncloud/owncloud-app-files_8.0.0-2_amd64.deb

The mirrors should have it in an hour or so.

**Comment by kulve** [comment]
Thank you, seems to work!

**Comment by twouters** [comment]
issue can be closed, mirrors are up to date.

**Comment by randy-jr-olive** [comment]
I am still getting an error, although not the same one:
Unpacking owncloud-config-apache (8.0.0-1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-config-apache_8.0.0-1_amd64.deb (--unpack):
 trying to overwrite '/etc/apache2/conf-available/owncloud.conf', which is also in package owncloud 8.0.0-1
Errors were encountered while processing:
 /var/cache/apt/archives/owncloud-config-apache_8.0.0-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

any suggestions?

**Comment by kulve** [comment]
Does it help if you purge owncloud and owncloud-config-apache packages and install them back?

**Comment by randy-jr-olive** [comment]
will that erase all my configurations?

**Comment by koehn** [comment]
Still not seeing the 8.0.0-2 when I `apt-get update` on Ubuntu 14.04 (for owncloud or owncloud*) ...

`# dpkg -l owncloud`
`ii  owncloud                                           8.0.0-1                        all                            ownCloud Server - Private file sync and share server`

**Comment by kulve** [comment]
"dpkg -l" shows only installed packages, try "apt-cache policy owncloud". I at least see the Debian 7.0 packages.

randy-jr-olive: You can try also to force the installation: sudo dpkg --force-all -i /var/cache/apt/archives/owncloud-config-apache_8.0.0-1_amd64.deb

(or 8.0.0-2 if you see the new versions already).

**Comment by jnweiger** [comment]
@randy-jr-olive That is a different issue: please follow up over there, https://github.com/owncloud/core/issues/13992

@koehn should be there any minute now. :-)

I just succeeded on ubuntu-14.04:

    apt-get update
    apt-get install owncloud-app-files
    Get:1 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0//xUbuntu_14.04/  owncloud-app-files 8.0.0-2 [181 kB]
    Fetched 181 kB in 0s (862 kB/s)          
    ...
    

I see my files through the web interface now. I am closing here.

**Comment by kusmierz** [comment]
I had to add manually package `owncloud-app-files` via apt - even in v8.0.0-2.

**Comment by MoSpuddy** [comment]
I'm good. Thanks for the quick fix.

**Comment by jnweiger** [comment]
@kusmierz
I am testing the dependencies like this, they look good:

    apt-cache show owncloud | grep owncloud-app-files,
    Depends: owncloud-server, owncloud-config-apache, owncloud-3rdparty, owncloud-app-activity, owncloud-app-files, owncloud-app-files-encryption, owncloud-app-files-pdfviewer, owncloud-app-files-trashbin, owncloud-app-firstrunwizard, owncloud-app-templateeditor, owncloud-app-user-ldap, owncloud-app-external, owncloud-app-files-external, owncloud-app-files-sharing, owncloud-app-files-versions, owncloud-app-gallery, owncloud-app-updater, owncloud-app-user-webdavauth, owncloud-app-files-locking, owncloud-app-files-texteditor, owncloud-app-files-videoviewer, owncloud-app-provisioning-api, owncloud-app-user-external

Note the trialing comma trick, and note that owncloud-app-files is in the list.

**Comment by Akhenaton** [comment]
Still doesn't see any "owncloud-app-files" package in the repos.....

**Comment by jnweiger** [comment]
@Akhenaton E.g. here http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/amd64/

With 8.0.0-3 it will move from amd64 to all.  Sorry for this confusion. But apt-get should handle it nevertheless.

**Comment by ergatides** [comment]
I have the same issue with CentOS.

```bash
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-6/noarch/owncloud-app-files-8.0.2-13.1.noarch.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
```

**Comment by jnweiger** [comment]
I get a 404 from suse.lagis.at today, when I try the URL from @ergatides --

**Comment by jnweiger** [comment]
see also https://github.com/owncloud/core/issues/15096

**Comment by flotho** [comment]
Hy,

Working on CentOS7, I had the same issue.
I solved it by disabling the gpg check in the repo.

regards

**Comment by jnweiger** [comment]
Fixed! The issue was found in the scanner that feeds the opensuse mirrorbrain.
Please try again and reopen if you still have issues.

**Comment by chaud245** [comment]
Hi,
I hate to post on an issue that's technically closed, but I'm having a very similar issue.

http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community/CentOS_CentOS-7/noarch/owncloud-app-user_ldap-8.0.2-16.1.noarch.rpm
