### ISSUE TITLE
Apps Missing after Upgrade to OC 8

### ISSUE THREAD

**Issue by sebhof** [owncloud/core#14033]
Hi,

after upgrade to OC 8 (Debian Package) are at least the apps "contacts" and "calendar" completely missing. I get some exceptions in the log:

{"reqId":"3391bb61027070ccd004e9ffcb69aa4d","remoteAddr":"192.168.124.1","app":"core","message":"Unable to parse OCS content for app 166049","level":4,"time":"2015-02-10T09:09:18+00:00"}
{"reqId":"3391bb61027070ccd004e9ffcb69aa4d","remoteAddr":"192.168.124.1","app":"core","message":"Unable to parse OCS content for app 166051","level":4,"time":"2015-02-10T09:09:18+00:00"}
{"reqId":"3391bb61027070ccd004e9ffcb69aa4d","remoteAddr":"192.168.124.1","app":"core","message":"Unable to parse OCS content for app 166056","level":4,"time":"2015-02-10T09:09:18+00:00"}
{"reqId":"3391bb61027070ccd004e9ffcb69aa4d","remoteAddr":"192.168.124.1","app":"core","message":"Unable to parse OCS content for app 166061","level":4,"time":"2015-02-10T09:09:18+00:00"}
{"reqId":"3391bb61027070ccd004e9ffcb69aa4d","remoteAddr":"192.168.124.1","app":"core","message":"Unable to parse OCS content for app 166046","level":4,"time":"2015-02-10T09:09:18+00:00"}
{"reqId":"3391bb61027070ccd004e9ffcb69aa4d","remoteAddr":"192.168.124.1","app":"core","message":"Unable to parse OCS content for app 166053","level":4,"time":"2015-02-10T09:09:18+00:00"}
{"reqId":"0db92c45f8df37c0331644f79691305c","remoteAddr":"192.168.124.1","app":"PHP","message":"require_once(\/appinfo\/remote.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/remote.php#54","level":3,"time":"2015-02-10T09:20:22+00:00"}
{"reqId":"0db92c45f8df37c0331644f79691305c","remoteAddr":"192.168.124.1","app":"PHP","message":"require_once(): Failed opening required '\/appinfo\/remote.php' (include_path='\/var\/www\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/var\/www\/owncloud\/3rdparty\/pear\/pear_exception:\/var\/www\/owncloud\/3rdparty\/pear\/archive_tar:\/var\/www\/owncloud\/lib\/private:\/var\/www\/owncloud\/config:\/var\/www\/owncloud\/3rdparty:\/var\/www\/owncloud\/apps:\/var\/www\/owncloud\/lib:.:\/usr\/share\/php:\/usr\/share\/pear:\/var\/www\/owncloud') at \/var\/www\/owncloud\/remote.php#54","level":3,"time":"2015-02-10T09:20:22+00:00"}
and so on...

But these messages do not seem to affect the contacts or calendar app!? Also the apps are not listed in directory apps:

$ sudo ls -l apps/
insgesamt 80
drwxr-xr-x 11 root root 4096 Feb 10 09:27 activity
drwxr-xr-x 10 root root 4096 Feb 10 09:27 external
drwxr-xr-x 13 root root 4096 Feb 10 09:27 files
drwxr-xr-x 14 root root 4096 Feb 10 09:27 files_encryption
drwxr-xr-x 12 root root 4096 Feb 10 09:27 files_external
drwxr-xr-x  6 root root 4096 Feb 10 09:27 files_locking
drwxr-xr-x  9 root root 4096 Feb 10 09:27 files_pdfviewer
drwxr-xr-x 12 root root 4096 Feb 10 09:27 files_sharing
drwxr-xr-x  8 root root 4096 Feb 10 09:27 files_texteditor
drwxr-xr-x 11 root root 4096 Feb 10 09:27 files_trashbin
drwxr-xr-x 10 root root 4096 Feb 10 09:27 files_versions
drwxr-xr-x  7 root root 4096 Feb 10 09:27 files_videoviewer
drwxr-xr-x 10 root root 4096 Feb 10 09:27 firstrunwizard
drwxr-xr-x  9 root root 4096 Feb 10 09:27 gallery
drwxr-xr-x  6 root root 4096 Feb 10 09:27 provisioning_api
drwxr-xr-x 12 root root 4096 Feb 10 09:27 templateeditor
drwxr-xr-x 11 root root 4096 Feb 10 09:27 updater
drwxr-xr-x  5 root root 4096 Feb 10 09:27 user_external
drwxr-xr-x 13 root root 4096 Feb 10 09:27 user_ldap
drwxr-xr-x  6 root root 4096 Feb 10 09:27 user_webdavauth

There are also no dependencies in the Debian package to contacts or calendar... Please fix as soon as possible. Thanks in advance...

Regards
Sebastian

**Comment by MorrisJobke** [comment]
This is intended. Go to the apps managment page and install calendar and contacts again. All your data is still there.

**Comment by sebhof** [comment]
Hi,

thanks for reply. But unfortunately the apps are also not listed in the app manager. Not in "active", not in "not active" and the "recommended" section shows a blank page. No way to install the apps...

Sebastian

**Comment by MorrisJobke** [comment]
@sebhof It should be on the recommended page. Your issue with the blank page could be caused by #14022

**Comment by sebhof** [comment]
This might be the problem, but I dont see the error in the log. Is there a way to test it?

**Comment by MorrisJobke** [comment]
@sebhof I have nothing in mind. @LukasReschke Do you know a way to test the HTTPS connection from a server?

**Comment by JB1985** [comment]
Same here. Upgrade from 8.0.0-4 to 8.0.0-5 Debian.

Error-Log:
PHP Fatal error:  require_once(): Failed opening required '/var/www/owncloud/apps/calendar/appinfo/remote.php' (include_path='/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:/var/www/owncloud/lib:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/remote.php on line 54

Only Calandar and Contact Apps are missing.

**Comment by LukasReschke** [comment]
@sebhof @MorrisJobke 

First: Check if the appstore is not disabled in config/config.php

If it is not disabled you can check it the SSL state with cURL yourself:

```
➜  /tmp  wget http://curl.haxx.se/ca/cacert.pem
# Should not work
➜  /tmp  curl --cacert ./cacert.pem  https://api.owncloud.com
➜  /tmp  curl https://api.owncloud.com
# Should work
➜  /tmp  curl -k https://api.owncloud.com
```

The first two commands should not work – can you confirm?

**Comment by LukasReschke** [comment]
`curl --cacert ./cacert.pem  https://api.owncloud.com` might work depending though on OS etc ;-)

**Comment by LukasReschke** [comment]
Also which PHP version are you using?

**Comment by JB1985** [comment]
/tmp# curl --cacert /tmp/cacert.pem  https://api.owncloud.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

:/tmp# curl https://api.owncloud.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

/tmp# curl --cacert cacert.pem https://api.owncloud.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

PHP Version 5.4.36-0+deb7u3 with suPHP

**Comment by sebhof** [comment]
Same here...
appstore is not disabled.
The curl commands did not work as expected.
PHP ist version 5.4.36-0+deb7u3

**Comment by LukasReschke** [comment]
` curl -k https://api.owncloud.com` works though?

**Comment by sebhof** [comment]
yes

**Comment by JB1985** [comment]
Me too.

**Comment by LukasReschke** [comment]
Thanks. Let's see if the new certificate configuration will help then. – Unfortunately the responsible person for the server is not located in Europe and so most likely not yet awake ;-)

I added a todo in https://github.com/owncloud/core/issues/14022 and will ping you once we have the server properly setup to retest. Thanks for your help!

**Comment by JB1985** [comment]
Any idea to download manually the apps? Because all Clients cant work in the moment.

**Comment by LukasReschke** [comment]
@JB1985 You can download them manually from apps.owncloud.com and put them into your `apps/` folder.

**Comment by LukasReschke** [comment]
https://apps.owncloud.com/content/show.php/Contacts+8.0?content=168708 and https://apps.owncloud.com/content/show.php/Calendar+8.0?content=168707

**Comment by JB1985** [comment]
wget --no-check-certificate https://apps.owncloud.com/CONTENT/content-files/168707-calendar.zip
unzip 168707-calendar.zip
cp -aR calendar/ /var/www/owncloud/apps/

Workaround!

**Comment by chihoko** [comment]
Why has this been closed, what is the solution?

**Comment by dragetd** [comment]
So the issue is a missconfigured SSL certificate on api.owncloud.com, and once the *single* person responsible for this fixes this, the apps will reappear under 'recommended'?

What component is checking the appstore? Why does it not give a propper error message?
Is 'Fatal	core	Unable to parse OCS content for app 166054' related to that issue?

**Comment by sebhof** [comment]
I am not sure if it is a good idea to apply the -k switch to the curl call since it disables the certificate validation at all. The main problem seems to be that the GoDaddy certificate authorities are not trusted by the Debians curl version... I tried downloading all the GoDaddy-CA-Files, appended them to a single pem and tried the curl call again. This works. So the solution for the call of the appstore might be to provide the trusted certificates by the application instaed of trusting the OS?

**Comment by RealRancor** [comment]
According to https://www.ssllabs.com/ssltest/analyze.html?d=apps.owncloud.com the problem is the intermediate cert of godaddy which needs an "extra download". This confirms the comment of @sebhof above.

@chihoko 
The workaround was posted one above your comment.

**Comment by danimo** [comment]
@RealRancor Fixed now.

**Comment by bioxz** [comment]
@danimo Many thanks, it's working now.

**Comment by sebhof** [comment]
Works also for me. Thanks a lot...

**Comment by ynicolaus** [comment]
Hi All, I'm new to GitHub and fairly new to OwnCloud.  I have upgraded to OC 8.0.7 (php 5.5.17) through softaculous on my webhost.  I still don't see anything on my recommended apps, blank page.

Any suggestions?

**Comment by dragetd** [comment]
AFAIK downloading and extracting them under app manually will result in the exact same as using the internal app manager. I.e. download https://apps.owncloud.com/CONTENT/content-files/168707-calendar.zip (and for contacts is also on apps.owncloud.com ) and unzip them in your apps folder, and you will be have OC working again.

As for the apps page… check your log and try maybe again tomorrow.

**Comment by steckerhalter** [comment]
In the official tarball https://download.owncloud.org/community/owncloud-8.0.0.tar.bz2 (advertised on https://owncloud.org/install/#instructions-server) contacts and calender apps are missing (and possibly others):

```
$ ls -la apps/
total 32
drwxr-xr-x 22 user user 4096 Feb  7 03:33 .
drwxr-xr-x 11 user user 4096 Feb  7 03:33 ..
drwxr-xr-x 11 user user  148 Feb  7 03:33 activity
drwxr-xr-x 10 user user  132 Feb  7 03:32 external
drwxr-xr-x 13 user user 4096 Feb  7 03:31 files
drwxr-xr-x 14 user user 4096 Feb  7 03:31 files_encryption
drwxr-xr-x 12 user user 4096 Feb  7 03:31 files_external
drwxr-xr-x  6 user user   52 Feb  7 03:33 files_locking
drwxr-xr-x  9 user user   97 Feb  7 03:32 files_pdfviewer
drwxr-xr-x 12 user user 4096 Feb  7 03:31 files_sharing
drwxr-xr-x  8 user user   71 Feb  7 03:32 files_texteditor
drwxr-xr-x 11 user user  124 Feb  7 03:31 files_trashbin
drwxr-xr-x 10 user user  112 Feb  7 03:31 files_versions
drwxr-xr-x  7 user user   59 Feb  7 03:32 files_videoviewer
drwxr-xr-x 10 user user  114 Feb  7 03:33 firstrunwizard
drwxr-xr-x  9 user user  120 Feb  7 03:32 gallery
drwxr-xr-x  6 user user   52 Feb  7 03:31 provisioning_api
drwxr-xr-x 12 user user  149 Feb  7 03:33 templateeditor
drwxr-xr-x 11 user user 4096 Feb  7 03:32 updater
drwxr-xr-x  5 user user   42 Feb  7 03:33 user_external
drwxr-xr-x 13 user user 4096 Feb  7 03:31 user_ldap
drwxr-xr-x  6 user user  102 Feb  7 03:31 user_webdavauth
```
I have cloned them from github into the apps folder and that did the trick. But why are they missing in the first place? Doesn't that mean for most users the most important features are lacking to start with?

Or am I misunderstanding this completely?

**Comment by RealRancor** [comment]
The calendar and contacts app are not shipped with the tarball anymore and needs to be installed from the appstore: https://github.com/owncloud/documentation/issues/826

**Comment by steckerhalter** [comment]
@RealRancor thanks, I wasn't aware of that

**Comment by RealRancor** [comment]
Unfortunately this wasn't communicated properly.

**Comment by ProcyonTheEvil** [comment]
Please note that if you run a minimal Linux install, you have to install the appropriate certificate package. In Debian, you have to install ca-certificates:

apt install ca-certificates

This solved this issue for me.
