### ISSUE TITLE
User did not have the required privileges ({DAV:}read) for path "principals/username”

### ISSUE THREAD

**Issue by oeves** [owncloud/core#14048]
### Actual behaviour
iOS and OS X is unable to sync contacts
OS X Error: The operation couldn’t be completed. (CoreDAVErrorDomain error 2.)
iOS Error: Could not establish SSL Connection

### Server configuration
**Operating system**:
Debian Wheezy 7.8 

**Web server:**
nginx 1.2.1

**Database:**
mysql 14.14
**PHP version:**
PHP 5.4.36-0+deb7u3 (fpm-fcgi)

**ownCloud version:** 
ownCloud 8.0 (stable)

**Updated from an older ownCloud or fresh install:**
Upgraded from previous stable version
moved data directory, saved config.php and placed it into the new owncloud version and set the new data directory. The upgrade worked well, but the clients cant sync contacts and calendars anymore. 

**List of activated apps:**
Activity 1.2.0
Bookmarks 0.4
Calendar 0.6.4
Contacts 0.3.0.18
Deleted files 0.6.2
First Run Wizard 1.1
PDF Viewer 0.7
Pictures 0.6.0
Share Files 0.6.0
Text Editor 0.4
Updater 0.4
Versions 1.0.5
Video Viewer 0.1.3

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => ‘123321’,
  'passwordsalt' => ‘123321’,
  'datadirectory' => '/var/www/owncloud-data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => ‘123321’,
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 4,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'cloud.123321.12’,
    1 => 'cloud.123321.13’,
  ),
  'mail_from_address' => 'no-reply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'cloud.123321.12’,
  'secret' => ‘123321’,
);

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
no

### Client configuration
**Operating system:**
iOS 8.1.3

#### ownCloud log (data/owncloud.log)

{"reqId":"605072fb2dc469836a2f0d235aca1e82","remoteAddr":"123.123.123.123","app":"carddav","message":"Exception: {\"Message\":\"User did not have the required privileges ({DAV:}read) for path \\\"principals\\\/username\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAVACL\\\/Plugin.php(712): Sabre\\\\DAVACL\\\\Plugin->checkPrivileges('principals\\\/username', '{DAV:}read')\\n#1 [internal function]: Sabre\\\\DAVACL\\\\Plugin->beforeMethod('OPTIONS', 'principals\\\/username')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('OPTIONS', 'principals\\\/username')\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAVACL\\\/Plugin.php\",\"Line\":217}","level":4,"time":"2015-02-10T12:47:56+00:00"}username

**Comment by karlitschek** [comment]
are you sure this is not an ssl config error on your server side?

**Comment by oeves** [comment]
Yes pretty sure, the config is identical. The error on iOS is strange, but when i try to test it manually through a browser (https://cloud.123321.12/remote.php/caldav/principals/username/) i get an error like this:

<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>
User did not have the required privileges ({DAV:}read) for path "principals/username”
</s:message>
<s:sabredav-version>1.8.12</s:sabredav-version>
<d:need-privileges>
<d:resource>
<d:href>/remote.php/caldav/principals/username</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>

**Comment by oeves** [comment]
Here is the nginx config which worked on the previous version:

server {
        listen 80;
        listen [::]:80;
        server_name cloud.123321.12;

        return 301 https://$server_name$request_uri;
}

server {
        listen 443 ssl;
	listen [::]:443 ssl;

	server_name cloud.123321.12;

        ssl_certificate /etc/ssl/cloud.123321.12/cloud.123321.12.bundle.crt;
        ssl_certificate_key /etc/ssl/cloud.123321.12/cloud.123321.12.key;

	ssl_session_timeout 10m;
	ssl_session_cache   shared:SSL:10m;
	add_header Strict-Transport-Security max-age=31536000;
	add_header X-Frame-Options DENY;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;
	ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH EDH+aRSA !RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";

        # Path to the root of your installation
        root /var/www/owncloud;

        client_max_body_size 1G; # set max upload size
        fastcgi_buffers 64 4K;

        rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
        rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
        rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;

        index index.php;

        error_page 403 /core/templates/403.php;
        error_page 404 /core/templates/404.php;

        location = /robots.txt {
		return 200 "User-agent: *\nDisallow: /";
		allow all;
		log_not_found off;
		access_log off;
        }

        location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README) {
                deny all;
        }

        location / {
                # The following 2 rules are only needed with webfinger
                rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
                rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

                rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
                rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;

                rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

                try_files $uri $uri/ index.php;
        }

        location ~ \.php(?:$|/) {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param HTTPS on;
                fastcgi_pass php-handler;
        }

        # Optional: set long EXPIRES header on static assets
        location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
                expires 30d;
                # Optional: Don't log access to assets
                access_log off;
        }

}

**Comment by sebhof** [comment]
Same problem here when trying to sync calendars. Running Debian Wheezy and updated package from 7.0.4.1 to 8.0.0.5. In the logs I see nothing related to this problem. Opening the URL within the browser I get the same output as @oeves . Please let me know if I can provode additional informations...

**Comment by oeves** [comment]
Okay, i figured out, that the problem only affects old accounts! 
i just added a test user and with this user i can access /remote.php/carddav/principals/test without the error! i will try to compare the user tables old and new to figure out whats going on there.

**Comment by PlusOne** [comment]
i agree, same problem here (Debian/Jessie) :

<d:error><s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception><s:message>User did not have the required privileges ({DAV:}read) for path "calendars/04F1F4AB-1393-4A71-B757-XXXXXXXXXX/persönlich"</s:message><s:sabredav-version>1.8.12</s:sabredav-version><d:need-privileges><d:resource><d:href>/remote.php/caldav/calendars/04F1F4AB-1393-4A71-B757-XXXXXXXXXX/persönlich</d:href><d:privilege><d:read/></d:privilege></d:resource></d:need-privileges></d:error>

**Comment by rayones** [comment]
Same here. Any solutions?

**Comment by rayones** [comment]
Another trace
Trying to open shared calendar (between new and old user in the same group) returns:
`<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Calendar with name 'xxx' could not be found</s:message>
<s:sabredav-version>1.8.12</s:sabredav-version>
</d:error>`

**Comment by rayones** [comment]
It seems, that sharing between two new users gives the same result. WTH(ell)?!

**Comment by rayones** [comment]
ANOTHER UPDATE: I've downgraded OC to v.7 (from my apt cache) and it seems to work... Just in case ;)

**Comment by PlusOne** [comment]
I was in hurry, so i switched back to 7.0.4. Restored Database and all is working as excepted. Waiting for an solution.

**Comment by rayones** [comment]
I went back to 7.0.4 without resotring the database - I didn't have a backup :)

**Comment by oeves** [comment]
good to know that a rollback is possible. i consider doing it also. 

i was not able to find any irregularities between new and old users within the database. it would be great to get the old users working again.

**Comment by TheBigWave** [comment]
I've got the same Problem on my System. Maybe a Bug caused by nginx ??

**Comment by PlusOne** [comment]
No, i dont think so.

**Comment by BennyLi** [comment]
Same problem here. My setup looks like this:

* ownCloud 8.0 on Raspberry Pi with nginx + php5-fpm (5.4)
* Thunderbird + Sunbird
* Android CalDAV Sync

This configuration works with ownCloud 7.0.4 (rolled back too).
Here is the XML error from the browser:

```xml
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
  <s:message>User did not have the required privileges ({DAV:}read) for path "calendars/af380ef4-d43a-1033-90ab-b1af2e4ed611/persönlich_shared_by_9a7d798e-f2f0-1033-8e2f-8d3ee493c34b"</s:message>
  <s:sabredav-version>1.8.12</s:sabredav-version>
  <d:need-privileges>
    <d:resource>
      <d:href>/owncloud/remote.php/caldav/calendars/af380ef4-d43a-1033-90ab-b1af2e4ed611/persönlich_shared_by_9a7d798e-f2f0-1033-8e2f-8d3ee493c34b</d:href>
      <d:privilege>
        <d:read/>
      </d:privilege>
    </d:resource>
  </d:need-privileges>
</d:error>
```

**Comment by mconsoir** [comment]
Same problem here!!! After upgrading the calendar isn't working.

<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>
User did not have the required privileges ({DAV:}read) for path "calendars/63e88801-d9ad11e3-b2dec8e5-5b2cd30b/persönlich"
</s:message>
<s:sabredav-version>1.8.12</s:sabredav-version>
<d:need-privileges>
<d:resource>
<d:href>
/remote.php/caldav/calendars/63e88801-d9ad11e3-b2dec8e5-5b2cd30b/persönlich
</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>

Tomorrow i will roll back too...

**Comment by Phillinger** [comment]
Seems to be the same problem as mentioned by me in #14104

How can I rollback to version 7? Using Debian 7.0 and installed owncloud via apt-get.

**Comment by bhersent** [comment]
I have the same problem !!! After upgrading,the calendar and contact isn't working.

I have read in other threads that the new user created is working but no !! I have tested a new install  on localhost  but same result -> not working.

I conclude that the problem is Owncloud / Owncloud Core and not my install but the configuration documentation for Nginx is same for Owncloud 7 and 8.

**Comment by m4lvin** [comment]
Observed the same behaviour and am unable to sync my Lightning calendars and Icedove addressbook. When testing the URL with a browser, I got the xml error first, but restarting the browser and logging out of owncloud brought an http authentication dialogue and after passing that the ics files. Also on Android with Davdroid everything works fine.
I have a lot ot these messages:

    {"reqId":"...","remoteAddr":"...","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-02-12T22:47:01+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/ajax\/events.php?calendar_id=shared_events&start=1423436400&end=1424041200&_=1423780550337"}

But they also occur for plain webdav:

    {"reqId":"...","remoteAddr":"...","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-02-12T22:48:28+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

What else would be helpful?

**Comment by nroach44** [comment]
I created my account in owncloud as NRoach44, but normally logging in wasn't case sensitive. If I give DavDroid 'nroach44|password" it will give the errors noted above, but 'NRoach44|password' works perfectly.

So it seems that owncloud's auth system is 'user not case sensitive' but the DAV backends are 'user IS case sensitive'.

**Comment by protist** [comment]
@nroach44 Oh. Wow. Thank you so much! I've spent about 6 hours troubleshooting this. I'm unsure if my problems are identical to others in this thread, but changing my username from lower-case to the "correct" capitalisation fixed all my syncing problems, in both Thunderbird/Lightning/Sogo and DavDroid. Using lower-case had worked perfectly in OwnCloud versions <8. Also, to clarify further, I *can* log into the web interface using lower-case.

(FWIW I had been suffering from 403 errors in Thunderbird/Lightning/Sogo and 404 in DavDroid. I'm not sure why the inconsistency.)

**Comment by TheBigWave** [comment]
yep i can confirm that with a case-sensitive Username the CalDav Authentification works normaly.

**Comment by bhersent** [comment]
I confirm that a case-sensitive Username the CalDav and CardDav Authentification works normaly on iOS ;)

**Comment by oeves** [comment]
Yiha! I tried it on iOS and it works! 
But it seems that you have to delete the wrong spelled account on your sync device and re add it with the right spelled username. On OS X i tried to replace the letter but the client got stuck. Re adding works fine!

**Comment by PlusOne** [comment]
No one is using LDAP Configuration? I want to be happy, too :D There is an option for the case sensitiv windows ldap connection - but it doesnt works for me. Changing login name from case sensitive doesnt solved it :( Any Idea?
![13-02-2015 10-17-16](https://cloud.githubusercontent.com/assets/621860/6185041/c1da962e-b369-11e4-8383-3f5b30e91829.png)

**Comment by Phillinger** [comment]
I'm authenticating against a LDAP. And it doesn't matter if case sensitive or not: It doesn't work.

**Comment by PlusOne** [comment]
@Phillinger i can confirm, i upgraded right now and checked it again - no *.ics data through browser (correct credentials). Again ... downgrade :(

**Comment by Phillinger** [comment]
@PlusOne can you give me a hint, how to downgrade? Using Debian 7.

**Comment by PlusOne** [comment]
Do you got an Backup of the old Database? Just drop the new Database and restore the old Database with mysql cli, copy back the ownCloud 7.0.4 directory and you are good to go.

**Comment by Phillinger** [comment]
Hey, that seems to be easier than I thought. Thank you! :)

**Comment by PlusOne** [comment]
If you need further help, be free to ask (just add me through jabber or any other service) - if you got an backup of the old database and the old www directory it is quite easy to restore.

**Comment by BennyLi** [comment]
> I'm authenticating against a LDAP. And it doesn't matter if case sensitive or not: It doesn't work. 

It's a LDAP backend for me too. Confirm that it does not work with case sensitiv in mind. Using the mail to authenticate the user.

**Comment by PlusOne** [comment]
Jup i tried samAccount and email - either doesnt work. tried uid, too. nothing solves the problem actually.

**Comment by chris-se** [comment]
I had the same problem and found out what it was:

In `lib/private/connector/sabre/auth.php`, line 64
```php
\OC::$server->getSession()->set(self::DAV_AUTHENTICATED, $username);
```
The problem here is that `$username` is the username supplied with HTTP auth, which is NOT necessarily the internal username of Owncloud. The line beforehand reads
```php
OC_Util::setUpFS(OC_User::getUser());
```
where you already have `OC_User::getUser()` instead of `$username`, so it stores Owncloud's internal user instead of using the one given via HTTP.

If you change the corresponding line to:
```php
\OC::$server->getSession()->set(self::DAV_AUTHENTICATED, OC_User::getUser());
```
(and delete all the currently active sessions), then everything works as expected.

**Comment by blizzz** [comment]
@chris-se good finding, the return of OC_User::getUser() is indeed what should be passed to set(). Since it is used in the line before too, you can just call it once and store in a variable that you pass to setupFS() and set(). Do you mind opening a pull request? :)

cc @LukasReschke

**Comment by LukasReschke** [comment]
*sigh*

**Comment by LukasReschke** [comment]
Regression introduced with https://github.com/owncloud/core/pull/13416 then - so master and stable8 only.

**Comment by chris-se** [comment]
Wow, you guys respond really fast.

Anyway, pull request here: https://github.com/owncloud/core/pull/14275

**Comment by wikon** [comment]
I also can confirm this. Luckily, the hack provided by @chris-se works. :+1:

**Comment by wikon** [comment]
Today, there was an update to 8.0.0.6 which reverted the manual changes again so CalDAV stopped working and I've had to change the file again :-1:  This should not happen.

**Comment by turb** [comment]
Be careful with this patch ($username to OC_User::getUser()): I had the bug, and patching solved it. Then I saw that my Calendar app version was 6, and replaced it to the 8 version (It was empty). ...and the problem was back. Reverting the patch solved it.

So it seems you need $username for Calendar =0.8, and OC_User::getUser() for Calendar < 0.8

**Comment by tslben** [comment]
Bug still exists in 8.0.0-8 packages.
Using LDAP (Active Directory) and Apache2 on Wheezy.

**Comment by RealRancor** [comment]
-8 is just the version of the package itself and this issue is also still open. The problem should be fixed with the upcoming 8.0.1

**Comment by swellhead** [comment]
Please see https://forum.owncloud.org/viewtopic.php?f=31&t=26885#p81313 
------------------------------
With the manual patches described here to lib/private/connector/sabre/auth.php, line 64
solved the CalDav sync problem and all of my calendars where synced
I installed OC 8.0.1 - I verified that the patch does now come with the package.
With OC 8.01 the sync process seems to work in general  - but only for one of my calendars(my default one). No response/no sync error is shown for the other 8 calendars

 - as this worked before, I flag this as an issue of release 8.01
There seems to be an implementation issue in OC 8.01.
As  of today no update/no change - a second calendar is synced others are not

**Comment by DeepDiver1975** [comment]
@LukasReschke fixed? Or am I wrong? THX

**Comment by LukasReschke** [comment]
From my PoV: Yes.

> With OC 8.01 the sync process seems to work in general - but only for one of my calendars(my default one). No response/no sync error is shown for the other 8 calendars

That seems like a calendar issue to me. Can you please reopen at owncloud/calendar? THX.

**Comment by jloehel** [comment]
The error is still present. I updated owncloud (7.0.4.2 --> 8.0.2) yesterday. The update failed, because I forgot to deactivate the apps contacts and calendar. I renamed the two app-folders and after these changes I was able to complete the update-process. I installed the latest releases of these apps and now this error occurs, but lib/private/connector/sabre/auth.php is patched. CardDav and CalDav are broken now. WebDav works fine.

```
 Exception: {"Message":"User did not have the required privileges ({DAV:}read) for path \"addressbooks\/phreeek\/kontakte\"","Code":0,"Trace":"#0 \/httpsdocs\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAVACL\/Plugin.php(712): Sabre\\DAVACL\\Plugin->checkPrivileges('addressbooks\/ph...', '{DAV:}read')\n#1 [internal function]: Sabre\\DAVACL\\Plugin->beforeMethod('GET', 'addressbooks\/ph...')\n#2 \/httpsdocs\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(433): call_user_func_array(Array, Array)\n#3 \/httpsdocs\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(455): Sabre\\DAV\\Server->broadcastEvent('beforeMethod', Array)\n#4 \/httpsdocs\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('GET', 'addressbooks\/ph...')\n#5 \/httpsdocs\/apps\/contacts\/appinfo\/remote.php(88): Sabre\\DAV\\Server->exec()\n#6 \/httpsdocs\/remote.php(54): require_once('\/httpsdocs\/apps...')\n#7 {main}","File":"\/httpsdocs\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAVACL\/Plugin.php","Line":217} 
```

Further Information:
- OS: ubuntu-server 12.04
- nginx: 4.6.3
- php-fpm: 5.5.22-1 (chroot)
- owncloud: 8.0.2
- contacts: 0.3.0.18
- calendar: 0.6.4

**Comment by xdajog** [comment]
For me this is not solved unfortunately.. 

I use Ubuntu Trusty and having owncloud 8.0.2-8 installed (upgraded from v7.0). Since I upgraded to v8 calender sync and address book sync stopped working. I re-enabled both apps but still no success.

The mentioned patch here is already applied in Ubuntu's owncloud 8.0.2-8 version and the error is the same for all my calendars:

```xml
<d:error><s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception><s:message>User did not have the required privileges ({DAV:}read) for path "calendars/xxxxxtfi/cloud-privat"</s:message><s:sabredav-version>1.8.12</s:sabredav-version><d:need-privileges><d:resource><d:href>/remote.php/caldav/calendars/owntfi/cloud-privat</d:href><d:privilege><d:read/></d:privilege></d:resource></d:need-privileges></d:error>
```
Absolute the same for all my adressbooks. 
I try to access my own calendar and adresses.

**Comment by OtakuWally** [comment]
Hete is my corrected version of the lib/private/connector/sabre/auth.php, feel free to try it ;-)

        protected function validateUserPass($username, $password) {
                if (OC_User::isLoggedIn() &&
                        $this->isDavAuthenticated(OC_User::getUser())
                ) {
                        OC_Util::setupFS(OC_User::getUser());
                        \OC::$server->getSession()->close();
                        return true;
                } else {
                        OC_Util::setUpFS(); //login hooks may need early access to the filesystem
                        if(OC_User::login($username, $password)) {
                                // make sure we use owncloud's internal username here
                                // and not the HTTP auth supplied one, see issue #14048
                                $ocUser = OC_User::getUser();
                                OC_Util::setUpFS($ocUser);
                                //\OC::$server->getSession()->set(self::DAV_AUTHENTICATED, $ocUser);
                                \OC::$server->getSession()->set(self::DAV_AUTHENTICATED, OC_User::getUser());
                                \OC::$server->getSession()->close();
                                return true;
                        } else {
                                \OC::$server->getSession()->close();
                                return false;
                        }
                }
        }

**Comment by lars-becker** [comment]
Thanks Otanku. That seems to work with my calendar. :)

**Comment by OtakuWally** [comment]
Don't thank me, I just edited a file, thanks the person who ORIGINALLY found the bug (don't ask me where I have read about it ;-) )

**Comment by SpinovEvgeniy** [comment]
I've updated the file as mentioned above and problem still exists. OC 8.0.2, Centos 6, PHP 5.4.39.

**Comment by modk** [comment]
Same problem here, changed the file as descriped but no luck. OC 8.0.2-8, Ubuntu 12.04 LTS, PHP 5.5.23

**Comment by johnwoltman** [comment]
I'm having the same issues, even when using OtakuWally's version of validateUserPass.

Logging in as an LDAP user or as the owncloud administrator account, I cannot view/sync either CardDAV or CalDAV data.  I can use the WebDAV support just fine, but not the Card/CalDAV. 

### Expected behaviour
Should be able to use CardDAV and CalDAV links with iOS and OS X clients or view it with Firefox.

### Actual behaviour
Receive Sabre\DAVACL\Exception\NeedPrivileges exception

### Server configuration
**Operating system**:Centos 7.1 x86_64

**Web server:** Apache 2.4.6

**Database:**  postgresql 9.3.6

**PHP version:** 5.6.7

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** Update from 7

**List of activated apps:**
 - activity          
 - calendar          
 - contacts          
 - files             
 - files_sharing     
 - files_texteditor  
 - files_trashbin    
 - files_versions    
 - files_videoviewer 
 - gallery           
 - news              
 - user_ldap         

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '51d4672e6805c',
  'passwordsalt' => '[redacted]',
  'datadirectory' => '/var/cloud',
  'dbtype' => 'pgsql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => '[redacted]',
  'dbpassword' => '[redacted]',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 2,
  'log_type' => 'syslog',
  'logfile' => '',
  'maintenance' => false,
  'theme' => '',
  'forcessl' => true,
  'appcodechecker' => false,
  'overwritewebroot' => '/cloud',
  'overwrite.cli.url' => '/cloud',
  'trusted_domains' =>
  array (
    0 => '[redacted]',
  ),
  'secret' => '[redacted]',
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Only SSL/TLS, not owncloud file encryption

**Are you using an external user-backend, if yes which one:** LDAP/

#### LDAP configuration (delete this part if not used)

```
   appid   |             configkey             |                 configvalue
-----------+-----------------------------------+---------------------------------------------
 user_ldap | ldap_agent_password               | [redacted]
 user_ldap | ldap_turn_off_cert_check          |
 user_ldap | bgjUpdateGroupsLastRun            | 1386377150
 user_ldap | ldap_quota_attr                   |
 user_ldap | ldap_backup_host                  |
 user_ldap | ldap_attributes_for_group_search  |
 user_ldap | enabled                           | yes
 user_ldap | ldap_group_filter_mode            | 0
 user_ldap | ldap_cache_ttl                    | 600
 user_ldap | ldap_groupfilter_objectclass      | inetOrgPerson
 user_ldap | ldap_user_filter_mode             | 0
 user_ldap | ldap_group_filter                 | (&(|(objectclass=inetOrgPerson)))
 user_ldap | ldap_backup_port                  | 389
 user_ldap | ldap_configuration_active         | 1
 user_ldap | ldap_login_filter                 | (&(|(objectclass=inetOrgPerson))(uid=%uid))
 user_ldap | ldap_base_groups                  | ou=users,dc=[redacted],dc=com
 user_ldap | ldap_attributes_for_user_search   |
 user_ldap | ldap_tls                          |
 user_ldap | ldap_nocase                       |
 user_ldap | ldap_override_main_server         |
 user_ldap | ldap_quota_def                    |
 user_ldap | ldap_display_name                 | cn
 user_ldap | ldap_userfilter_objectclass       | inetOrgPerson
 user_ldap | home_folder_naming_rule           |
 user_ldap | ldap_expert_username_attr         | cn
 user_ldap | ldap_dn                           | cn=[redacted],dc=[redacted],dc=com
 user_ldap | ldap_port                         | 389
 user_ldap | ldap_expert_uuid_attr             |
 user_ldap | ldap_uuid_attribute               | entryuuid
 user_ldap | types                             | authentication
 user_ldap | ldap_host                         | ldap://[redacted]
 user_ldap | ldap_base                         | dc=[redacted],dc=com
 user_ldap | ldap_email_attr                   | mail
 user_ldap | ldap_nested_groups                | 0
 user_ldap | ldap_paging_size                  | 500
 user_ldap | ldap_base_users                   | ou=users,dc=[redacted],dc=com
 user_ldap | ldap_userfilter_groups            |
 user_ldap | ldap_userlist_filter              | (|(objectclass=inetOrgPerson))
 user_ldap | ldap_groupfilter_groups           |
 user_ldap | ldap_group_display_name           | cn
 user_ldap | ldap_group_member_assoc_attribute | uniqueMember
 user_ldap | ldap_login_filter_mode            | 0
 user_ldap | ldap_loginfilter_email            | 0
 user_ldap | ldap_loginfilter_username         | 1
 user_ldap | ldap_loginfilter_attributes       |
 user_ldap | has_memberof_filter_support       |
 user_ldap | ldap_expert_uuid_user_attr        |
 user_ldap | ldap_expert_uuid_group_attr       |
 user_ldap | last_jpegPhoto_lookup             | 0
 user_ldap | ldap_uuid_user_attribute          | entryuuid
 user_ldap | ldap_uuid_group_attribute         | entryuuid
 user_ldap | ocsid                             | 166061
 user_ldap | ldap_experienced_admin            | 0
 user_ldap | installed_version                 | 0.5.0
 user_ldap | cleanUpJobOffset                  | 0
```

### Client configuration
**Browser:** Firefox 36

**Operating system:** Windows 7 64-bit

### Logs
#### Web server & ownCloud error log
```
Apr 15 01:06:20 [redacted] ownCloud[1768]: {news} Configuration value "simplePieCacheDuration" does not exist. Ignored value.
Apr 15 01:06:20 [redacted] ownCloud[1824]: {news} Configuration value "simplePieCacheDuration" does not exist. Ignored value.
Apr 15 01:13:25 [redacted] ownCloud[6242]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:13:29 [redacted] ownCloud[6245]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:13:34 [redacted] ownCloud[6250]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:20:02 [redacted] ownCloud[6360]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:20:02 [redacted] ownCloud[6360]: {news} Configuration value "simplePieCacheDuration" does not exist. Ignored value.
Apr 15 01:35:41 [redacted] ownCloud[5713]: PHP Fatal error:  Class OC_Connector_Sabre_Auth contains 1 abstract method and must therefore be declared abstract or implement the remaApr 15 01:35:41 [redacted] httpd[5713]: {PHP} Class OC_Connector_Sabre_Auth contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Apr 15 01:36:17 [redacted] httpd[6727]: [Wed Apr 15 01:36:17.474944 2015] [so:warn] [pid 6727] AH01574: module wsgi_module is already loaded, skipping
Apr 15 01:36:17 [redacted] httpd[6727]: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/httpd/conf.d/com.conf:1
Apr 15 01:40:02 [redacted] ownCloud[7071]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Apr 15 01:40:02 [redacted] ownCloud[7071]: {news} Configuration value "simplePieCacheDuration" does not exist. Ignored value.
Apr 15 01:40:53 [redacted] ownCloud[6786]: {carddav} Exception: {"Message":"User did not have the required privileges ({DAV:}read) for path \"addressbooks\/john\/contacts\"","CodeApr 15 01:42:01 [redacted] httpd[7161]: [Wed Apr 15 01:42:01.133809 2015] [so:warn] [pid 7161] AH01574: module wsgi_module is already loaded, skipping

Apr 15 01:42:06 [redacted] ownCloud[7165]: {carddav} Exception: {"Message":"User did not have the required privileges ({DAV:}read) for path \"addressbooks\/john\/contacts\"","CodeApr 15 01:46:34 [redacted] ownCloud[7302]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
```

#### Browser log
```
None
```

**Comment by warhog** [comment]
Hi guys,
we are affected by that calendar problem, too. Is there a schedule when this will be fixed?
Regards

**Comment by lennartjuette** [comment]
I stille have this issue with a fresh install of 8.0.2 (sqlite backend). I can't acces my calendar at https://www.juette.eu/owncloud/remote.php/carddav/addressbooks/test/kontakte.

Error:
```
<d:error>
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>User did not have the required privileges ({DAV:}read) for path "addressbooks/test/kontakte"</s:message>
<s:sabredav-version>1.8.12</s:sabredav-version>
<d:need-privileges>
<d:resource>
<d:href>/owncloud/remote.php/carddav/addressbooks/test/kontakte</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>
```

Anything i can do to help?

**Comment by RealRancor** [comment]
Hi,

don't think it will be fixed if no one has reported this in the issue tracker of the calendar app as requested here: https://github.com/owncloud/core/issues/14048#issuecomment-82357261

**Comment by lennartjuette** [comment]
you may be right... i'l post something over there.

**Comment by RealRancor** [comment]
There is also a similar issue for the calendar app available here https://github.com/owncloud/calendar/issues/776 but i don't know if this is the exact same issue.

**Comment by lingfish** [comment]
I don't get why @LukasReschke closed this -- it's not just calendar.

**Comment by OtakuWally** [comment]
Well, then MAYBE SOMEONE should meke an issue about this ;-)

**Comment by LukasReschke** [comment]
Original issue was resolved: File a new one using the issue template. If file syncing works and this only affects calendar / contacts file an issue there.

**Comment by johnwoltman** [comment]
Neither project is taking responsibility for this issue. Very frustrating considering that ownCloud 7 worked perfectly. I haven't tried 8.0.3 yet, but hopefully I'll try it today.

**Comment by lingfish** [comment]
I don't see where this issue was fixed, only that some patch in a forum was mentioned. Which commit fixed it? 

I just upgraded from 7.x to 8.0.3 only a few hours ago, and calendar sync broke. I had to use an upper case first letter in my username when using CalDav via Thunderbird. The upgrade also disabled what seems to me to be non third party apps (calendar, contacts), flashed it briefly on screen, and didn't re-enable them (but I digress).

**Comment by RealRancor** [comment]
The fix for the initial reported issue is here: https://github.com/owncloud/core/issues/14275

**Comment by OtakuWally** [comment]
IMHO someone WITH this issue should simply file a bugreport instead of complaining that no one is taking responsibility? ;-)

**Comment by RealRancor** [comment]
Well spoke :)

**Comment by lennartjuette** [comment]
There is an open issue for the CardDav Backend:
https://github.com/owncloud/contacts/issues/814

**Comment by RealRancor** [comment]
Yes, and also an (probably wrong) closed issue at the CalDAV Backend: https://github.com/owncloud/calendar/issues/712

**Comment by simogeo** [comment]
Same problem here with v 8.1.0. Is there any consistent fix ? thanks

**Comment by mmirwaldt** [comment]
I think, the problem might come from which CalDav-Link you use.
Given two users Michael and Hans.
If Michael shares a calendar to Hans,
you get two different Caldav/CardDav links in Owncloud depending on the user who is logged in!
Michael gets something like 
.../remote.php/caldav/calendars/michael/ourcalendar
while Hans gets 
.../remote.php/caldav/calendars/hans/ourcalendar_shared_by_michael

You cannot access the shared calendar with Hans' link by Michael's login data.
That is something I observed.
Maybe this helps you.

**Comment by simogeo** [comment]
Exactly !
Hans can't get the caldav work neither by using `.../remote.php/caldav/calendars/michael/ourcalendar` (which appear to be normal) 

nor  `.../remote.php/caldav/calendars/michael/ourcalendar` (**which appear to me to be a bug!**)

**Comment by mmirwaldt** [comment]
There is a misunderstanding:
I did not imply "Hans cannot access /remote.php/caldav/calendars/hans/ourcalendar_shared_by_michael with his login data".
It works for me at least.

I wanted to warn you not to fall into this trap.

**Comment by simogeo** [comment]
Thanks for the precision. **It does not work for me !** using owncloud 8.2. Any idea ?

**Comment by lysnin9** [comment]
Did somebody get any further yet? Any ideas?
I get the same XML output for both caldav and carddav, no matter wich link I use.
iOS won't accept the account, says "account verification failed", not because of the self-signed SSL certificate.

**Comment by salfter** [comment]
CardDAV & CalDAV both appear to be broken again in ownCloud 8.2.  The CardDAV URL returns the following; the CalDAV URL returns something similar:

```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>2.1.7</s:sabredav-version>
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>
User did not have the required privileges ({DAV:}read) for path "addressbooks/salfter/contacts"
</s:message>
<d:need-privileges>
<d:resource>
<d:href>
/owncloud/remote.php/carddav/addressbooks/salfter/contacts
</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>
```

**Comment by jfburdet** [comment]
CalDAV urls have also broken when upgraded to 8.2 ! I can provide debug info if it helps to fix this quicker.

**Comment by RealRancor** [comment]
@salfter @jfburdet As pointed out by @LukasReschke in https://github.com/owncloud/core/issues/14048?_pjax=%23js-repo-pjax-container#issuecomment-98476316 a new issue should be created (if not already discussed) as the initial issue in here got fixed.
