### ISSUE TITLE
Dropbox plugin causes endless re-sync in client

### ISSUE THREAD

**Issue by qnxor** [owncloud/core#14873]
As asked by @guruz in #2479 I'm copying here the info initially reported there which causes my owncloud client to sync every 60 seconds and also cause cpu spikes. This is on MacOSX 10.10.2 but it seems server related.

---

@mcnesium I installed 1.8 beta2 and little changed in my case. I still see cpu spikes and high usages ***every minute*** or so. CPU time was 02m04s for owncloud,  compared to 00m19s for dropbox ... both idle, started at the same time, after about 2h. Dropbox handles over 20,000 files, while owncloud only 4 files.

I'll run the `ps` test and terminal logging and post again.

**EDIT:** here's the `ps` graph, notice the multiple spikes that happen every minute
![cpu usage vs time](http://cl.ly/image/18033v1g2Q3Q/oc.png)

**EDIT 2:** Here is the relevant part of the log (sanitized) from running `owncloud --logfile oc1.log` ... everything you see is being repeated every 60 seconds: https://dl.dropbox.com/s/ovw1czxlk3pe2k4/oc1.log

---

> Can you look at the complete log output and say which folder is always re-scheduled and synced? Is it all three folders or only that one?

The complete log consists of repeated blocks of the text I posted here: https://dl.dropbox.com/s/ovw1czxlk3pe2k4/oc1.log ... all of this repeats every 60 seconds. 

Note how is it says `slotEtagPollTimeTimeout` and `slotRunEtagJob: * Trying to check "ownCloud" for changes via Etag check. (time since last sync: 53 s)`. It looks there is a timeout of 53 s which triggers regular checks.

But that aside, the fact that the etags are different doesn't look right (see log): `03-05 04:35:32:250 0x7f91d0614440 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""54f7dca18ee8f"" , received: ""54f7dcdd84d36""`

> Just check for the message `OCC::FolderMan::slotScheduleSync: Schedule folder "???" to sync!`

See the log I posted, line 11: `OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud" to check remote ETag` (that's the main and only folder in MacOSX that the desktop client syncs)

> Is there anything special about the sync folder you have configured (shared folder, external storage, ...) ?

Like I said previously, one of the folders (the one called `Dropbox-Enc` you see in the log) is on Dropbox, via the external storage plugin and is also encrypted by ownCloud via the encryption plugin. Inside that folder there is only one file (ArcSin.pdf). All other folders are the default ones that owncloud created itself. All this is in the log.

> Can you check the owncloud.log on the server for possible errors/warnings?

Good call! There is an error related to external_storage: `{"reqId":"9f70682ab4c7c24aa2c687dd5d288529","remoteAddr":"CLIENT_IP_ADDRESS","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-05T04:35:37+00:00"}` ... where CLIENT_IP_ADDRESS is my home IP, the one on which the ownCloud MacOSX client runs.

But that can't be true ... the external storage sync with the Dropbox-Enc folder works just fine. I just copied another file in "Dropbox-Enc" and it was sync'ed just fine to Dropbox, and I can also see it in the web interface. Something else must be going on.

> Which server version do you use?

I'm using Ubuntu 14.04.2 with Apache 2.4.12 and PHP 5.5 (both from this PPA: https://launchpad.net/~ondrej/+archive/ubuntu/apache2).

The enabled apache modules are: `access_compat actions alias auth_basic auth_digest authn_core authn_file authz_core authz_groupfile authz_host authz_user autoindex cgi cgid dav dav_fs deflate dir env expires filter headers mime mpm_prefork negotiation php5 reqtimeout rewrite setenvif socache_shmcb ssl status`

The enabled php5 modules are (note I have opcode caching enabled via opcache):
```
# grep extension= /etc/php5/apache2/conf.d/*
/etc/php5/apache2/conf.d/05-opcache.ini:zend_extension=opcache.so
/etc/php5/apache2/conf.d/10-pdo.ini:extension=pdo.so
/etc/php5/apache2/conf.d/20-curl.ini:extension=curl.so
/etc/php5/apache2/conf.d/20-gd.ini:extension=gd.so
/etc/php5/apache2/conf.d/20-intl.ini:extension=intl.so
/etc/php5/apache2/conf.d/20-json.ini:extension=json.so
/etc/php5/apache2/conf.d/20-mcrypt.ini:extension=mcrypt.so
/etc/php5/apache2/conf.d/20-mysqli.ini:extension=mysqli.so
/etc/php5/apache2/conf.d/20-mysql.ini:extension=mysql.so
/etc/php5/apache2/conf.d/20-pdo_mysql.ini:extension=pdo_mysql.so
/etc/php5/apache2/conf.d/20-pdo_pgsql.ini:extension=pdo_pgsql.so
/etc/php5/apache2/conf.d/20-pdo_sqlite.ini:extension=pdo_sqlite.so
/etc/php5/apache2/conf.d/20-pgsql.ini:extension=pgsql.so
/etc/php5/apache2/conf.d/20-readline.ini:extension=readline.so
/etc/php5/apache2/conf.d/20-sqlite3.ini:extension=sqlite3.so
```

The apache conf and htaccess are the default ones. The host conf for the site that owncloud is running under is:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>

    ServerAdmin admins@DOMAIN.COM
    ServerName  DOMAIN.COM
    ServerAlias www.DOMAIN.COM

    DocumentRoot        /var/www/DOMAIN.COM
    UseCanonicalName    Off

    <Directory /var/www/DOMAIN.COM>
        Options FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/ssl_error.log
    LogLevel warn
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLEngine on
    SSLCertificateKeyFile    /etc/ssl/private/DOMAIN.COM.key
    ## Apache 2.4 complains about using two directives for this
    #SSLCertificateFile       /etc/ssl/certs/DOMAIN.COM.pem
    #SSLCertificateChainFile  /etc/ssl/certs/DOMAIN.COM.ca-bundle
    ## Just cat the above two files into one file, the one below
    SSLCertificateFile       /etc/ssl/certs/DOMAIN.COM.full.crt

</VirtualHost>
</IfModule>
```

---

@guruz Here's a full (sanitized) log of 5 minutes from the moment the desktop client starts: https://dl.dropbox.com/s/ntla2jgkp7p3mck/oc3.log

I now have bigger problems. I added a file to the "Dropbox-Enc" subfolder to test if it syncs ... and it does. But if I delete it using Finder, the owncloud client puts it back after 5-10 seconds! Here's a full log of me starting owncloud, then deleting the file `fntoggle` from the "Dropbox-Enc" subfolder : https://dl.dropbox.com/s/h6i17n2810uti0c/oc4.log (the deletion happens at 03-06 12:27:00:048, and then the file is restored at 03-06 12:27:06:977)

Deleting a file from another subfolder, or from the main folder, does not bring it back. It feels like one or more components are flaky (encryption plugin, external storage plugin, desktop client). I don't feel safe using it for my regular work. Maybe this should be a different bug report.

> Do I understand it well that the steps to reproduce are as follows:
> 1) Upload a file "test.txt" to "Dropbox-Enc" using the Web UI
> 2) Wait for the sync client to sync it down
> 3) Edit the file using the web UI (or upload+overwrite using the web UI)
> 4) Wait for the sync client to sync it down
>
> But it never syncs it down because the file or folder etag did not change ?

Not quite. Everything is sync'ed correctly (except deletions, see above). The problem is that the desktop client appears to continuously attempt to sync the folder when it should not.

What I did was as follows
- fresh install and created another admin user
- activated the external storage and encryption plugins
- at dropbox.com I created an app restricted to a single folder and got the API key and passcode
- in the owncloud interface I created a Dropbox external storage using the API key and passcode provided by Dropbox ... this is the sub-folder called "Dropbox-Enc" we were speaking of
- added a file to the Dropbox-Enc folder
- the desktop client (at least the MacOSX one) constantly syncs every 60 seconds, causing CPU spikes, see log and my reports in my previous posts here.

However now I have bigger problems (see above).

**Comment by Pantos** [comment]
I get the same errors using OC 8.0.2 with desktop client 1.8.0beta2 on Windows 8.1. My log is flooded every 2-5 seconds with this error:
`{"reqId":"9524a992ab94ab3841599a39107251dd","remoteAddr":"YXZ","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-14T21:56:07+00:00"}`

**Comment by karlitschek** [comment]
@Pantos Sounds like you have an external storage configured but authentication fails? Can you check this please?

**Comment by Pantos** [comment]
I configured Dropbox and it works fine over the OC webinterface. So I think the authentications works correct? The error occurs by using the desktop client only. If I disable the OC desktop client I don't get an error. Hope I understand your question in the right way...

**Comment by karlitschek** [comment]
@icewind1991 any idea where this error comes from? and why does this only happen during syncing?

**Comment by cleocir** [comment]
Same error here with OC 8.0.2

**Comment by karlitschek** [comment]
@DeepDiver1975 @PVince81  any ideas here? thanks

**Comment by PVince81** [comment]
Okay, I see it here too:
```
{"reqId":"62e8a0864d4d2ef202d714bb16bdbd1a","remoteAddr":"127.0.0.1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-17T09:41:12+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/dropbox\/Photos"}
{"reqId":"51216d03e3702c9bdeace3de47b9e32e","remoteAddr":"127.0.0.1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-17T09:41:17+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/dropbox\/Public"}
```

for every PROPFIND. Maybe Dropbox has an API limit and doesn't let us do more than X calls an hour or something.

**Comment by PVince81** [comment]
Okay, it's not the rate-limit, which would return 503: https://www.dropbox.com/developers/core/bestpractices

**Comment by PVince81** [comment]
I found something, seems that the metadata from the root cannot be retrieved with "." any more.
Fix here: https://github.com/owncloud/core/pull/14946

**Comment by PVince81** [comment]
Let me know if that PR solves the issues for you.

**Comment by DeepDiver1975** [comment]
fixed with #14946

**Comment by guruz** [comment]
@qnxor Does it fix your problem too? Thanks..

**Comment by qnxor** [comment]
I'm traveling at the moment. Will test when I get back in a few days.

**Comment by qnxor** [comment]
Nope, I'm still experiencing high CPU usage at idle with spikes every 60 seconds. This is the CPU usage of just the owncloud process (`ps -p <ID> -o etime,%cpu`):

![CPU Usage](https://dl.dropbox.com/s/39o9hjihqopwjia/oc1.png)

Here's a log: https://dl.dropbox.com/s/pfexb6h4hml0ioh/oc5.log

Using the latest client 1.8.0.2139 and the server is 8.0.2-8 (Ubuntu 14.04.2). Same files and folder structure as before (nothing was changed).

The issue is definitely not fixed in my case and I'm not sure it's the Dropbox plugin that causes it. It seems related to owncloud/client#3007 and owncloud/client#2479

I notice that a nightly was posted in owncloud/issues#3007. I could give that a try later.

**Comment by PVince81** [comment]
@qnxor thanks for testing. Do you see any new/different error messages in owncloud.log with the patch applied ?

**Comment by guruz** [comment]
> I notice that a nightly was posted in owncloud/issues#3007. I could give that a try later.

Yes, give this a try please before reporting..

**Comment by qnxor** [comment]
Build 2220 seems much better (note the lower Y axis values, previously 70-80%, now 2-3%):

![CPU usage](https://dl.dropbox.com/s/ty908519f0oa29e/oc7.png)

Log file: https://dl.dropbox.com/s/i9qrtz7a0bnrrzp/oc7.log

**Comment by guruz** [comment]
nice. we could probably make it even nicer by bundling the quota request and the connection validator to schedule somehow together with the other requests (so the CPU doesnt wake up so often)..

...or avoiding more requests in the first place.

**Comment by jgoerzen** [comment]
I am still seeing this endless resync with the latest 8.1.  I don't believe this fixed it.
