### ISSUE TITLE
App installation status is not always recognized correctly

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#14935]
## Expected behavior
ownCloud should recognize the installation status of an app properly.

## Actual behavior
ownCloud didn't always recognize the installation status of an app correctly. Although apps in the category 'installed' are listed correctly, the 'recommended' category shows the same app as not active?
![20150316_172831-oc802_active_apps](https://cloud.githubusercontent.com/assets/2572764/6671170/d877e56e-cc03-11e4-921d-0255d1efce47.jpg)
![20150316_172831-oc802_active_apps-2](https://cloud.githubusercontent.com/assets/2572764/6671171/e0c22a68-cc03-11e4-99d8-53d9c9aecc0e.jpg)

#### Server Configuration
OS: Linux 3.2.54
Web server: Apache2 2.4.10
Database: MySQL 5.1.73
PHP version: 5.4.38
ownCloud version: 8.0.2

#### Client Configuration
Browser: Firefox 36.0.1
Operating system: Windows 7

**Comment by PVince81** [comment]
Hmmm, but this was fixed in 8.0.2 ? @LukasReschke

**Comment by LukasReschke** [comment]
Yes - should be fixed. If you click "activate" and take a look at the request in your browser network console what is the app id that gets sent?

**Comment by karlitschek** [comment]
yes. should be fixed.

**Comment by j-ed** [comment]
@karlitschek Hello Frank, although I've spend most of my live with software developers it is always surprising to see that thinks could not be possible because they have been declared as "not possible" or "solved" or OPP (Yes, I've read the hitchhikers guide to the galaxy).
May I point your attention to the fact that I've installed ownCloud 8.0.2 (**!**) on my server and the problem still appears. Woudn't it be possible that you've fixed something but not everything?

@LukasReschke appid=168708 is displayed if I press the "Activate" button. Additionally the following error message is shown too:
![20150316_183148-oc8_app_activation-1](https://cloud.githubusercontent.com/assets/2572764/6673312/64fff0fe-cc12-11e4-9834-aaeb4cb264c5.jpg)

I found out that the error message comes from the function `checkAppsIntegrity`in ../lib/private/installer.php. It seems that the function tries to find the file info.xml in the path /tmp/oc_tmp_59696868156f725242c31570b6b939bb/appinfo/ although I couldn't find that directory on my server. Any idea how I could provide more valuable into to identify the root cause of the problem?

**Comment by LukasReschke** [comment]
Thanks. Will investigate this one. Can you tell me which distribution you use so I can get a local copy running in a VM? :-)

Sorry that this one got closed this early. - Shit happens when having to triage so many issues :sweat_smile:

**Comment by RealRancor** [comment]
At least the "app don't provide a xml" could be a dup of https://github.com/owncloud/core/issues/14820

**Comment by j-ed** [comment]
@LukasReschke Never mind, I'm using the following distribution: http://www.eisfair.org/home/download/
Let me know if I can provide additional debug information.

**Comment by j-ed** [comment]
**FYI:** I've just tested it with ownCloud 8.0.3 but the result is still the same. Although apps have already been activated the button e.g. in the recommendation section still shows `Activate`. If someone could point me to the right php script I would try to identify whats going wrong here.

## Environment
#### Server Configuration
OS: Linux 3.2.67
Web server: Apache2 2.4.12
Database: MySQL 5.1.73
PHP version: 5.4.39
ownCloud version: 8.0.3

#### Client Configuration
Browser: Firefox 38
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
I can still reproduce this. I guess this is a problem with the OCSIDs. The current contacts app for example specifies in `166044` but in the appstore it is `168708`  https://apps.owncloud.com/content/show.php/Contacts?content=168708

But changing the OCSID in the code also doesn't fix the issue.

@LukasReschke Can you have a look at this?

**Comment by LukasReschke** [comment]
> But changing the OCSID in the code also doesn't fix the issue.

https://github.com/owncloud/core/pull/17689 + backports?

**Comment by Kawohl** [comment]
closed as fixed in https://github.com/owncloud/core/pull/17689
