### ISSUE TITLE
(solved) "The test with getenv(\"PATH\") only returns an empty response" after upgrade to 8.1.0, the clients's sync stopped

### ISSUE THREAD

**Issue by meklon** [owncloud/core#17504]
Update. The issue contained two separate problems:
1) "The test with getenv(\"PATH\") only returns an empty response" error was fixed by uncommenting "env[PATH] = /usr/local/bin:/usr/bin:/bin" in the file "/etc/php5/fpm/pool.d/www.conf" 
2) The problem with clients was because of the deprecated versions in the default Ubuntu repositories. You should use the external repos for it. Read it here: https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-57-generic x86_64)
Nginx+php-fpm

I've upgraded to 8.1.0 using the apt-get. After that the sync process with clients have stopped with error: error downloading ****/owncloud/remote.php/webdav/ - server replied: Forbidden. I haven't change anything in nginx and php-fpm last several versions.

I also get this warning in admin menu:
php does not seem to be setup properly to query system environment variables. The test with getenv("PATH") only returns an empty response.
Please check the installation documentation for php configuration notes and the php configuration of your server, especially when using php-fpm.

Config files:
php-fpm.conf: http://pastebin.com/nwd9MPJN
php.ini: http://pastebin.com/dnpwp17B

**Comment by kas70** [comment]
what's the version of your client?  
release notes say:
"Due to various technical issues, by default desktop sync clients older than 1.7 are not allowed to connect and sync with the ownCloud server."

**Comment by RealRancor** [comment]
This can happen if you don't have the correct permission set on filesystem level like described here:

https://doc.owncloud.org/server/8.1/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions

**Comment by meklon** [comment]
I've got the 1.7.0 client version. It's the fresh one in Kubuntu 15.01. Ok, I'll check the permissions.

**Comment by meklon** [comment]
Nothing happened after applying the script. I've also applied it some versions ago. The problem looks the same as the described below:
http://owncloud.10557.n7.nabble.com/Re-testpilots-Digest-Vol-26-Issue-3-td15115.html

**Comment by Krishath** [comment]
+1. I also tried using the script.

**Comment by meklon** [comment]
Granted full access for test puposes as chmod 777 for /var/www/owncloud. Nothing happened.

**Comment by nazar-pc** [comment]
Same warning here, but everything seems to work fine.

**Comment by RealRancor** [comment]
The warning is very likely unrelated and the documentation how to fix your environment is available here:

**Comment by meklon** [comment]
All clients are down including the android ones((( web-interface is accessible...

**Comment by nazar-pc** [comment]
Thanks, @RealRancor, uncommenting `env[PATH]` did the trick

**Comment by meklon** [comment]
Thanks, @RealRancor. "The test with getenv(\"PATH\") only returns an empty response" was fixed. But still no access from clients. Seems like the problem is elsewhere. Should I create the new issue and look for some logs?

**Comment by meklon** [comment]
Now the error is ****/owncloud/remote.php/status.php - server replied: Service unavailable

**Comment by meklon** [comment]
So, as far as I understand the webdav is unavaliable now after upgrade. My /data folder is on the external server and it is mounted via the /etc/fstab. Everything worked till 8.1.0
What happened in this release that prevents me from using the external storage as default /data?

**Comment by meklon** [comment]
Exception: {"Message":"HTTP\/1.1 403 Unsupported client version.","Code":0,"Trace":"#0 [internal function]: OC\\Connector\\Sabre\\BlockLegacyClientPlugin->beforeHandler(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/blocklegacyclientplugin.php","Line":76}

**Comment by meklon** [comment]
It's the trace after the Dolphin webdav access in Kubuntu.

**Comment by RealRancor** [comment]
8.1 has introduced a min version for the sync client:

https://doc.owncloud.org/server/8.1/admin_manual/release_notes.html#changes-in-8-1

Strange that this also affects Dolphin.

**Comment by meklon** [comment]
"The SabreDAV browser at /remote.php/webdav has been removed."
Could this be a problem? I've tried the latest 1.8.3 client via Windows 7 and got the same Forbidden trouble.

**Comment by RealRancor** [comment]
I don't think so. This just removes the possibility to use a webbrowser on this URL

**Comment by meklon** [comment]
I've reversed to backup with 8.03. Now it works fine. If I can help you to find the reason of this bug - let me know how. I'll do my best in providing you with logs.

**Comment by PVince81** [comment]
Dolphin works for me against OC 8.1. It's dolphin-15.04.2-3.1.x86_64 on openSUSE Factory.
User agent is `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) dolphin/4.14.9 Safari/534.34';` and doesn't contain the string "mirall"

Not sure why the version detection check would fail with your Dolphin version, maybe something is wrong with the regexp here https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/blocklegacyclientplugin.php#L73

**Comment by meklon** [comment]
The main trouble is that fact that none of my clients work after upgrade. I think, I should make the full separate bug report with all the necessary information. I think, we can close the current issue as we've found that "getenv("PATH") only returns an empty response" was not the reason of problem with clients.

**Comment by freekert** [comment]
It is for sure the client. The latest version is 1.8.4 my Lubuntu install also on has 1.7.0 and also stopped working. See this page to get more recent clients on Linux: https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

I also get the getenv("PATH") error but everything works as before (including my Android and Windows client.) So that seems unrelated to your client issues.

**Comment by meklon** [comment]
@freekert, thanks. I'll try.

**Comment by meklon** [comment]
@freekert, thank you very much! That helped. The default client in Ubuntu's repo was too old. Look like everything is ok.

**Comment by tx7** [comment]
Hi guys,

I got this same error message on OC8 too.
I uncommented this line, but it didn't work:
env[PATH] = /usr/local/bin:/usr/bin:/bin" in the file "/etc/php5/fpm/pool.d/www.conf".

Any idea?

**Comment by RealRancor** [comment]
- Remove gentenv from disabled functions in php.ini
- Restart php5-fpm after done the changes
- Use correct pool

**Comment by RealRancor** [comment]
Btw. the issue here is about a nonworking sync client

@meklon Please update the issue description and title. As the original issue is solved by updating your you could also close this issue.

**Comment by tx7** [comment]
I'll do that.
What do you meant 'use correct pool'?
I only have one owncloud installation folder..

**Comment by RealRancor** [comment]
Hi,

please use either the forums, the users mailinglist or the irc channel #owncloud on freenode for further questions. If you think there is a bug within this check create a new issue.

**Comment by RealRancor** [comment]
@meklon If its solved you can also just close this issue.

Maybe also change the title to ```After upgrade to 8.1.0 the clients's sync stopped``` or similar to avoid confusion.

**Comment by tx7** [comment]
I still can't get the message about "the test with getenv(\"PATH\") only returns an empty response" to fixed.

**Comment by RealRancor** [comment]
@tx7 
This issue is not related to this bugreport. Please see my comment above:

> please use either the forums, the users mailinglist or the irc channel #owncloud on freenode for further questions. If you think there is a bug within this check create a new issue.

**Comment by alinaugustin** [comment]
> The warning is very likely unrelated and the documentation how to fix your environment is available here:
> 
> https://doc.owncloud.org/server/8.1/admin_manual/installation/source_installation.html#configuration-notes-to-php-fpm

Your response doesnt help at all!
