### ISSUE TITLE
Sidebar interaction feels clumsy

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18238]
I find it strange having the sidebar open and close depending on the selection.
For example if I select multiple files and the sidebar was open, it will close.

Additionally, it doesn't feel intuitive to have to click in the middle of the row to make the sidebar appear. It isn't easily discoverable.

How about having a button in the top right of the controls bar to toggle the sidebar instead ? Then the sidebar can stay open regardless of what the user does in the file list (whether selecting files or performing actions).

@jancborchardt @owncloud/designers @karlitschek what do you think ?

**Comment by PVince81** [comment]
basically the user can discover that there is a button on the top right and also decide whether the sidebar should stay visible or not.

**Comment by karlitschek** [comment]
I agree. A way to open and close the sidebar independently if a file is selected at the moment or not is a good idea.
I would avoid to have a toolbar button. This is a bit ugly in my opinion. :-) Maybe we could have a small hint on the right side that can be clicked and expands to the full sidebar? Something like a collapsed state of the sidebar which is only 10px wide ?

**Comment by jancborchardt** [comment]
Yeah, this is something to refine. I’m not sure about the toolbar button. The sidebar should probably not hide when it was open and you select multiple files – instead it should show details of those multiple files. Maybe we need to add an action called »Details« to the new action dropdown menu?

> Something like a collapsed state of the sidebar which is only 10px wide ?

This approach specifically will conflict with people just wanting to click the scrollbar to scroll, as mentioned before about the mockup you showed me. :)

**Comment by PVince81** [comment]
If the sidebar can stay open, we also need to decide what to show when multiple files are selected or none at all. Empty sidebar ?

**Comment by PVince81** [comment]
Also another question: should the current row become highlighted when an action is performed on the row ? For example when I click on the favorite icon, should the sidebar highlight move to the current row ? Same when clicking on the actions dropdown ? (see #18210)

**Comment by karlitschek** [comment]
@jancborchardt Yes. I remember :-)
But I'm not sure how bad this really is. Having no option to hide/show is worse. And honestly a toolbar button is also bad. So maybe this is better then the other options? :-) What do you think?

**Comment by karlitschek** [comment]
@PVince81 If the content in the sidebar is context sensitive, which it is, then we have to indicate to which file/folder this belongs. Somehow.

**Comment by PVince81** [comment]
@karlitschek we already do, but it doesn't work properly hence my question. See the screenshot in https://github.com/owncloud/core/issues/18210 to see what I mean with highlight issues. We should consolidate them somehow.

**Comment by karlitschek** [comment]
Yes. This should probably easier to recognize. Somehow.

**Comment by jancborchardt** [comment]
> For example when I click on the favorite icon, should the sidebar highlight move to the current row ?

No.

> Same when clicking on the actions dropdown ?

Here probably yes. Definitely when the sidebar is open, the row should be highlighted.

**Comment by PVince81** [comment]
@jancborchardt how about the "Share" link then ? That one will redirect to the sidebar's share panel later, so it makes sense to highlight the row. Why the exception for the star icon ? (it's also an inline file action)

**Comment by jancborchardt** [comment]
@PVince81 star is an exception because it is a quick action, and does not open the sidebar. Share opens the sidebar, so the appropriate row should be marked because you can scroll up and down.

**Comment by PVince81** [comment]
So:
- [ ] actions menu must move highlight to current row
- [ ] add "Details" action in actions menu to open the sidebar (closing is done with the X icon)
- [ ] sidebar must stay open between file list refreshes / nav to a different folder (basically, never auto-close the sidebar)
- [ ] add "empty" and "multi-select" content for the sidebar when nothing or multiple files are selected

Anything else ?

**Comment by jancborchardt** [comment]
Seems like that’s all. Anything else we have to find out while using it, and iterate on it.

> basically, never auto-close the sidebar

This seems crucial, yeah. Only when the x in the top right is clicked. What do you think @owncloud/designers, also about the points discussed above?

**Comment by PVince81** [comment]
Just had a try and while it is better, it is still not too clear for the user where to click to move the sidebar highlight. Maybe any click on the file row should move the focus ? (regardless whether file action, file name, empty space or any of the size, mtime columns)

**Comment by PVince81** [comment]
Try it out here: https://github.com/owncloud/core/pull/18273

Also make sure to tick the checkboxes and see how it feels. I think we should consolidate the hightlights somehow.

**Comment by oparoz** [comment]
- [ ] BUG: Add ellipsis to filename when the sidebar pushes the icons over it

**Comment by PVince81** [comment]
@oparoz please raise separately.
This ticket is about the interaction for opening/closing the sidebar only.
Thanks.

**Comment by oparoz** [comment]
Done. https://github.com/owncloud/core/issues/18383

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/core/pull/18273

Further refinements can be discussed in separate issues.

**Comment by oparoz** [comment]
I'm guessing the refinements will be for 9.0?

**Comment by jancborchardt** [comment]
Depends on what it is. It’s feature freeze, but bugfixes should still get in.

**Comment by LukasReschke** [comment]
The current behaviour is super annoying. - Can we have "open sidebar on click"?

**Comment by LukasReschke** [comment]
With super annoying I mean really super annoying.

**Comment by nickvergessen** [comment]
The way people will open it now is by abusing the share icon ...

**Comment by LukasReschke** [comment]
> The way people will open it now is by abusing the share icon ...

That's what I do. Yes.

**Comment by PVince81** [comment]
How about this alternative proposal: https://github.com/owncloud/core/issues/18238#issuecomment-130315290, or toolbar button or a vertical bar with an arrow on it, when clicking on the vertical bar, it opens.

**Comment by oparoz** [comment]
The slide-door handle concept should work and you make it work on mobile with a swipe

**Comment by jancborchardt** [comment]
Again – the handle on the right _will_ interfere with scrolling and we will get complaints. I would say restoring the »click on row« behavior to open the sidebar takes care of this. The share action is also on the row so it blends in with the functionality. @PVince81 can you do that?

**Comment by PVince81** [comment]
So should we remove the "Details" file action again ?
In https://github.com/owncloud/core/issues/19120 it was said that the current selection would stay even when clicking outside the table, so the sidebar will open once and never close unless switching folders or clicking the "X".

Is that the new expected behavior ?

**Comment by oparoz** [comment]
What we need is some specs...
* Drag and drop doesn't trigger the side-bar
* Tapping on the row brings up the side-bar
* Tapping on the row selects the current element (tick mark)
* Tapping on the row + shift adds an element to the selection
* Tapping in the side-bar preview launches the slideshow
* Tapping on the side-bar's close button closes the sidebar
* Leaving the folder closes the side-bar

**Comment by PVince81** [comment]
@oparoz thanks. It is not completely accurate and there is still the issue with the multiple highlights, see https://github.com/owncloud/core/issues/18210

We could make a tapping on the row set the tick mark instead of being a separate type of highlight.

One problem though is that if you untick the last row, the highlight would disappear and produce an empty sidebar (https://github.com/owncloud/core/issues/19120). In that case we could still keep the last contents even though nothing is highlighted.

**Comment by oparoz** [comment]
@PVince81 - It's more of a wish list than a representation of the current state ;)

**Comment by oparoz** [comment]
And regarding the empty sidebar, as discussed, remove everything but some basic folder stats. I think it would make things simpler both for devs and for users.

**Comment by PVince81** [comment]
@jancborchardt your call on the final interaction design ?

**Comment by jancborchardt** [comment]
Yeah, @oparoz has a good list already. This here is specifically about that clicking the list should also bring up the sidebar. The »Details« action should stay though.

**Comment by PVince81** [comment]
Regarding dragging, I just noticed that even when using "mouseup", dragging triggers it as soon as dragging starts... will look into a workaround.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19365

@oparoz I followed your spec, but with one difference: selecting a file with checkboxes will also open the sidebar.

**Comment by PVince81** [comment]
Setting to high due to the many complains about the current approach
