### ISSUE TITLE
[8.1.2] password reset over admin account

### ISSUE THREAD

**Issue by andybuchs** [owncloud/core#18926]
If i change the password in the ldap, login as admin, go to the user list, and actualize over the master encrypten key the users key, Owncloud sais it’s correct (except it can’t change the password, what is correct too). Then i logout admin and login as the user, i still get the message, that the key needs to update.
(@schiesbn)

![aktualisierung_key_overadmin_01](https://cloud.githubusercontent.com/assets/14197886/9760787/83336ed6-56f8-11e5-9fe5-4b1ac120d4fa.PNG)
![aktualisierung_key_overadmin_02](https://cloud.githubusercontent.com/assets/14197886/9760790/87268d52-56f8-11e5-905d-1b34c6559cb1.PNG)

**Comment by karlitschek** [comment]
What do you think @schiesbn

**Comment by schiesbn** [comment]
@andybuchs thanks for reporting the issue on github. I could reproduce it. The pull request above should fix it, maybe you can give it a try?

**Comment by schiesbn** [comment]
here is the backport for 8.1: https://github.com/owncloud/core/pull/19011

**Comment by andybuchs** [comment]
﻿Hello Björn,



Thanks for the fast solving of the problem.
I used the link you sent me 2 days ago and replaced the files in my OC 8.1.2 installation.

I will test tomorrow and let you know how it works.



﻿Cheers,

andy




--------------------------------------------------
Buchs Engineering
Internet Solutions

Kanzleistrasse 126
CH-8004 Zürich
Tel.: +41-43-500 5656
Fax: +41-43-500 5657

E-Mail: info@buchs.ch
Internet: http://www.buchs.ch
--------------------------------------------------







-----Ursprüngliche Nachricht-----
Von: Björn Schießle <notifications@github.com>
Gesendet: Mon 14 September 2015 12:51
An: owncloud/core <core@noreply.github.com>
CC: andybuchs <andy.buchs@buchs.ch>
Betreff: Re: [core] [8.1.2] password reset over admin account (#18926)

here is the backport for 8.1: #19011

**Comment by andybuchs** [comment]
Hello Björn



We testet the new 8.1.3 and 8.2.0 of Owncloud, and still the same issue with password change in LDAP and encrypten.

In which version will it be fixed?



Best regards,
andy﻿





-----Ursprüngliche Nachricht-----
Von: Björn Schießle <notifications@github.com>
Gesendet: Fre 11 September 2015 21:25
An: owncloud/core <core@noreply.github.com>
CC: andybuchs <andy.buchs@buchs.ch>
Betreff: Re: [core] [8.1.2] password reset over admin account (#18926)

@andybuchs thanks for reporting the issue on github. I could reproduce it. The pull request above should fix it, maybe you can give it a try?
