### ISSUE TITLE
stable8.1 nightly tar has syntax error in verson.php

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#19237]
````
{"reqId":"tT7gTg9xjA48OiBYXOt+","remoteAddr":"172.17.42.1","app":"PHP","message":"syntax error, unexpected ',', expecting ')' at \/opt\/owncloud\/version.php#6","level":3,"time":"2015-09-22T07:54:00+00:00"}
````

````
# more version.php 
<?php 
$OC_Version = array(8,1,3,0);
$OC_VersionString = '8.1.3';
$OC_Edition = '';
$OC_Channel = 'daily';
$OC_VersionCanBeUpgradedFrom = array(,);
$OC_Build = '2015-09-22T03:40:59+00:00 876266f0ce2f811ea1ad98363c879960e6bbe1ca';

**Comment by DeepDiver1975** [comment]
@karlitschek build script issue???

**Comment by PVince81** [comment]
Merging this backport PR might help: https://github.com/owncloud/core/pull/19149
It will actually set a value for this variable.

Note: need to make sure that the build script only except this value for 8.1 and 8.2, not previous versions.

**Comment by PVince81** [comment]
Ok I merged it...

**Comment by DeepDiver1975** [comment]
lets keep this open until the tar got recreated once again and we can run smashbox on stable8.1

**Comment by karlitschek** [comment]
i manually generated the nightly builds again. please check

**Comment by DeepDiver1975** [comment]
> i manually generated the nightly builds again. please check

thx

**Comment by DeepDiver1975** [comment]
hmmm ... looks still broken ....


````
root@e38b06effc32:~# more /opt/owncloud/version.php 
<?php 
$OC_Version = array(8,1,3,0);
$OC_VersionString = '8.1.3';
$OC_Edition = '';
$OC_Channel = 'daily';
$OC_VersionCanBeUpgradedFrom = array(,);
$OC_Build = '2015-09-22T03:40:59+00:00 876266f0ce2f811ea1ad98363c879960e6bbe1ca';

**Comment by DeepDiver1975** [comment]
> $OC_Build = '2015-09-22T03:40:59+00:00 876266f0ce2f811ea1ad98363c879960e6bbe1ca';

same build time?

**Comment by karlitschek** [comment]
arg. This is for 8.1!  I canceled it before the 8.1 builds were executed. Please check again now.

**Comment by PVince81** [comment]
@jvillafanez reported that the build script also fails for previous versions. As stated above https://github.com/owncloud/core/issues/19237#issuecomment-142241783 please make sure the scripts only expect the new variable for OC >= 8.1

**Comment by jvillafanez** [comment]
Confirming stable7 and stable8 daily tarballs are affected by this issue

**Comment by jvillafanez** [comment]
stable8.1 tarball isn't crashing now (I haven't checked the built time though)

**Comment by karlitschek** [comment]
argh. Please check again. should be fixed.
