### ISSUE TITLE
Creating new share within another shared folder shows admin user multiple times

### ISSUE THREAD

**Issue by amc2002** [owncloud/core#19517]
### Steps to reproduce
1. Share a folder with groups configured in ownCloud
2. Go into shared folder and share another (nested) folder (say, via shared link)
3. Expected inherited groups/users are shown, but admin user shows up 100 times or so as well

### Expected behaviour
Only inherited groups and users should show, and only show once

### Actual behaviour
Inherited groups and users are shown, but then admin is shown multiple times as well. This issue doesn't seem to happen with other users, only with local admin.

### Server configuration
**Operating system**: CentOS 7

**Web server:** httpd-2.4.6-31

**Database:** mariadb-5.5.44-1

**PHP version:** php-5.4.16-36

**ownCloud version:** 8.1.3 (stable)

**Updated from an older ownCloud or fresh install:** updated from 7

**List of activated apps:** 

Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - user_ldap: 0.6.1
Disabled:
 - encryption
 - external
 - user_external
 - user_webdavauth

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'XXXXXXX',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXX',
  'secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' =>
  array (
    0 => 'xxxxxx.xx.com',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'ownCloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ownCloud',
  'dbpassword' => 'XXXXXX',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'mail_from_address' => 'webmaster',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'xxxx.xxx.com',
  'loglevel' => 2,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxxxx.xxxxx.com',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'sendmail@xxxx.xxxx.com',
  'mail_smtppassword' => 'xxxxxxx',
  'mail_smtpsecure' => 'ssl',
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

+-------------------------------+----------------------------------------------------+
| Configuration                 | s01                                                |
+-------------------------------+----------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                  |
| hasPagedResultSupport         |                                                    |
| homeFolderNamingRule          |                                                    |
| lastJpegPhotoLookup           | 0                                                  |
| ldapAgentName                 | CN=ownCloud,CN=Users,DC=xxxx,DC=xx,DC=xxxxxx        |
| ldapAgentPassword             | ***                                                |
| ldapAttributesForGroupSearch  |                                                    |
| ldapAttributesForUserSearch   |                                                    |
| ldapBackupHost                |                                                    |
| ldapBackupPort                |                                                    |
| ldapBase                      | DC=xxxxx,DC=xx,DC=xxxx                             |
| ldapBaseGroups                | DC=xxxx,DC=xx,DC=xxxx                             |
| ldapBaseUsers                 | DC=xxxx,DC=xx,DC=xxxx                             |
| ldapCacheTTL                  | 600                                                |
| ldapConfigurationActive       | 1                                                  |
| ldapEmailAttribute            | mail                                               |
| ldapExperiencedAdmin          | 0                                                  |
| ldapExpertUUIDGroupAttr       |                                                    |
| ldapExpertUUIDUserAttr        |                                                    |
| ldapExpertUsernameAttr        |                                                    |
| ldapGroupDisplayName          | cn                                                 |
| ldapGroupFilter               |                                                    |
| ldapGroupFilterGroups         |                                                    |
| ldapGroupFilterMode           | 0                                                  |
| ldapGroupFilterObjectclass    |                                                    |
| ldapGroupMemberAssocAttr      | uniqueMember                                       |
| ldapHost                      | xxxx.xxxx.xxxxx                                      |
| ldapIgnoreNamingRules         |                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                    |
| ldapLoginFilterEmail          | 0                                                  |
| ldapLoginFilterMode           | 1                                                  |
| ldapLoginFilterUsername       | 1                                                  |
| ldapNestedGroups              | 0                                                  |
| ldapNoCase                    | 0                                                  |
| ldapOverrideMainServer        | 0                                                  |
| ldapPagingSize                | 500                                                |
| ldapPort                      | 389                                                |
| ldapQuotaAttribute            |                                                    |
| ldapQuotaDefault              |                                                    |
| ldapTLS                       | 0                                                  |
| ldapUserDisplayName           | displayname                                        |
| ldapUserFilter                | (&(|(objectclass=person)))                         |
| ldapUserFilterGroups          |                                                    |
| ldapUserFilterMode            | 1                                                  |
| ldapUserFilterObjectclass     | person                                             |
| ldapUuidGroupAttribute        | auto                                               |
| ldapUuidUserAttribute         | auto                                               |
| turnOffCertCheck              | 0                                                  |
| useMemberOfToDetectMembership | 0                                                  |
+-------------------------------+----------------------------------------------------+

### Client configuration
**Browser:** Chrome Version 45.0.2454.101 m

**Operating system:** Windows 10

#### Web server error log

No errors related to ownCloud

#### ownCloud log (data/owncloud.log)

No errors related to ownCloud

#### Screenshot of issue

![untitled-1](https://cloud.githubusercontent.com/assets/14333663/10228872/20efc5ec-6843-11e5-9c1b-9315c64ea8a8.jpg)

**Comment by karlitschek** [comment]
@schiesbn

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/17560 which has a smaller reproducible test case.

**Comment by PVince81** [comment]
Nothing to do with LDAP btw

**Comment by PVince81** [comment]
Let's reopen, there is a slight discrepancy with https://github.com/owncloud/core/issues/17560.
Once https://github.com/owncloud/core/issues/17560 is fixed, this one here should be retested.

**Comment by amc2002** [comment]
Will retest as soon as the other is fixed. Thanks.

**Comment by amc2002** [comment]
The fix in #19730 (and #17560 ) worked for my case AFTER I share the item. Once I share the item with any user or allow external sharing and enter a password, the list is correct.

Before I share the sub-folder, however, I still get the full list of repeating names.

Just thought it might be helpful.

**Comment by amc2002** [comment]
Tested with fix from #17560 (added single line 1917 in lib/private/share/share.php) - did not change behavior.

**Comment by PVince81** [comment]
Maybe it's a different issue then @rullzer ^

**Comment by amc2002** [comment]
I would imagine. Which is why this issue is still open I guess. I cannot update to 8.2 to check if that fixed anything since there is a missing library in CentOS7 that's keeping me from upgrading at the moment.

**Comment by amc2002** [comment]
Finally was able to update to v8.2.3 and this issue does not occur anymore. I'm closing the ticket. Thanks guys.
