### ISSUE TITLE
File list in infinite loop

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#20727]
Sometimes the files app refreshes the page infinitly.

Happened to me and @MorrisJobke starting since today (worked yesterday).
Happens on master

Steps to reproduce
1. Magic
2. ???
3. Problem

It's hard to see if the ajax requests fail or whatever, because the network tab is refreshed every 0.5 seconds.

I see a little yellow thing in the topbar which looks like an empty OC.notification to me

@PVince81 @DeepDiver1975 JS or webdav mostlikely

**Comment by MorrisJobke** [comment]
```


{"reqId":"haFWl6kNIHUaUZmvoyk8","remoteAddr":"::1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/remote.php(137): require_once('\\\/Users\\\/morrisjo...')\\n#7 {main}\",\"File\":\"\\\/Users\\\/morrisjobke\\\/Projects\\\/owncloud\\\/master\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-25T10:17:13+00:00","method":"PROPFIND","url":"\/master\/remote.php\/webdav\/"}
```

My steps:

* setup a fresh owncloud (Sqlite)
* on redirect after the setup I see following:

![bildschirmfoto 2015-11-25 um 11 21 46](https://cloud.githubusercontent.com/assets/245432/11394660/bff036ec-9366-11e5-93ce-8b4eb5445012.png)

**Comment by MorrisJobke** [comment]
It is indeed the webdav request:

![bildschirmfoto 2015-11-25 um 11 29 22](https://cloud.githubusercontent.com/assets/245432/11394843/d8fa9096-9367-11e5-937b-8ba0665ab678.png)

(I somehow managed to expand the webdev console fast enough to have this done before the popup appears)

**Comment by PVince81** [comment]
Hmmm strange, but we did try the session timeout case and it was properly redirecting to the login page ? https://github.com/owncloud/core/pull/20609

**Comment by MorrisJobke** [comment]
Looks empty:

![bildschirmfoto 2015-11-25 um 11 31 17](https://cloud.githubusercontent.com/assets/245432/11394883/15b3ba30-9368-11e5-8d1f-96287c5253de.png)

**Comment by PVince81** [comment]
Since yesterday you say, might be the Sabre 3 update which got merged.
Maybe the auth part needs some tweaking.

**Comment by MorrisJobke** [comment]
> Since yesterday you say, might be the Sabre 3 update which got merged.

Yep. I also think that this is related, but on the sabe3.0 branch everything worked.

**Comment by PVince81** [comment]
Hmmm, but then it got rebased, maybe that's when it broken.

**Comment by PVince81** [comment]
Works for me in Chrome and Firefox.

My steps:

1. Create a folder
1. Delete all PHP session files in /var/lib/php5/
1. Enter the folder
1. OC redirects to login page
1. Enter credentials
1. Back to OC, works again

**Comment by MorrisJobke** [comment]
I can't test your steps, because I can't run the setup properly.

**Comment by MorrisJobke** [comment]
Okay. I just had the saber branch checked out from yesterdays testing. Then I switched today to master and somehow forget to update the submodule to the masters version (yes...blame me). Now everything works. So this is maybe just because of some old submodule version at @nickvergessen instance, too? 


From my side this is fixed.

**Comment by nickvergessen** [comment]
I redid the submodule already multiple times already, it works in the beginning, but after some deleting and restoring it breaks again

**Comment by PVince81** [comment]
It just happened to me now when switching users.

Also found this in the log, might be related, possibly introduced during the sabre upgrade:
```
Interface 'Sabre\\Xml\\Element' not found at \/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/connector\/sabre\/taglist.php#34
```

**Comment by nickvergessen** [comment]
Yeah I had the same, but only once. After I pulled master and 3rdparty again it went away, but the problem (loop) still exists

**Comment by PVince81** [comment]
Hmmm, problem disappeared again. Weeeeird.

Next time I have it I'll dive in directly.
Also I don't see the interface issue any more.

**Comment by PVince81** [comment]
Did some debugging on an instance on @nickvergessen's machine and we found out that whenever "DAV_AUTHENTICATED" is set, the 401 exception is wrongly triggered.
See https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/sabre/auth.php#L153

AFAIK there is no JS core that authenticates directly against the DAV backend. But just in case we should probably recheck `isLoggedIn()` in the if below.

**Comment by PVince81** [comment]
Tentative fix here https://github.com/owncloud/core/pull/20760

**Comment by oparoz** [comment]
Just pulled master and got the same problem, so the fix doesn't seem to work.

1. Open some bookmarked URL
2. Landed in "Shared with others"
3. Clicked on "All files"
4. Got the auth request

Now I'm stuck. Can't log out, can't see files

**Comment by oparoz** [comment]
If I type the password, I see a notification telling me that the dir doesn't exist. I guess it's a standard error message and not related to the problem at hand.

**Comment by oparoz** [comment]
Never mind... the 3rd party folder was on another branch...

**Comment by MorrisJobke** [comment]
> Never mind... the 3rd party folder was on another branch...

Yep. This was also the reason on my side.

**Comment by MorrisJobke** [comment]
@nickvergessen Are you really sure that you checked out the correct 3rdparty directory content? Otherwise I would like to close this because it didn't happened again since then.

**Comment by nickvergessen** [comment]
Well @PVince81 and I found the issue, it is when you checked out a branch that is based on master between two of three fixes from vincent for this. The first fix caused to set a flag in some cases which then together with a second fix causes the problem. But #20760 makes the problem go away. And the issue should not be triggered anymore, cause users of master will have the new complete new code which never sets the flag causing the problem.

Right @PVince81 ? If so, please close

**Comment by PVince81** [comment]
Yes, correct.
