### ISSUE TITLE
It's impossible to copy the public link from the share dialogue on iOS

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#22336]
For this test to work, you need a generated link which is longer than the field. I've tested on an iPad, on iOS9
1. Share a folder
2. Tap on _Share link_
3. Try to copy the generated link

I've tried on both Safari and Chrome and was never able to copy the link. The handle on the right never manages to go to the end of the URL. There is no _Select all_.
It's probably a problem with the platform, but I'm sure a tap could be detected and the entire URL selected for the user, ready to be copied.

@jancborchardt @Henni @raghunayyar @tomneedham @PVince81 @MorrisJobke

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by PVince81** [comment]
Yeah, I think auto-select the whole field should be implemented.
Maybe this got lost when porting the dialog.

@rullzer @blizzz

**Comment by PVince81** [comment]
Hint: check how it's done for the webdav URL in the files setting at the bottom of the navigation bar

**Comment by rullzer** [comment]
I'll look into this

**Comment by oparoz** [comment]
>Yeah, I think auto-select the whole field should be implemented.
Maybe this got lost when porting the dialog.

It's working on the desktop, just not on that OS. It's as if there is a conflict between the natural action and the one implemented in the dialogue.

**Comment by oparoz** [comment]
BTW, this has been broken for a while. Just tested 8.1 and it's the same deal.

**Comment by rullzer** [comment]
Then I'm out of ideas. Somebody with an mobile IOS device please take over. Since this is alsmost impossible for me to fix without testing device.

**Comment by oparoz** [comment]
As mentioned in the PR, using textarea instead of input solves the problem, but it would be good for some iOS experts to voice in their opinion.

**Comment by PVince81** [comment]
Switching to textarea might be risky, some things like placeholder might not work properly any more (IE9 and co...) so need to be careful.

**Comment by rullzer** [comment]
Also using a textarea is just asking for trouble. They have very different use cases. So other visual stuff might break as well since textareas can do line wrapping etc.

I can't belive we  are the only ones that have this issue with IOS so there must be some solution to make it work properly.

**Comment by PVince81** [comment]
Maybe there is some magic touch-specific CSS stuff to tell it to behave differently ?

**Comment by oparoz** [comment]
>So other visual stuff might break as well since textareas can do line wrapping 

You can limit it to 1 row and x columns.

`<textarea id="share" rows="1" cols="x"></textarea>`

but there might be a styling problem (not in my tests).

**Comment by jancborchardt** [comment]
I thought we solved this for the Calendar CalDAV link some time ago. @georgehrke @raghunayyar @Henni do you remember how?

**Comment by jancborchardt** [comment]
@oparoz can you test if copying links works in other places?

- the link on the bottom of a single-file sharing page
- the CalDAV links in the Calendar app, bottom left settings area
- the CardDAV links in the Contacts app, bottom left settings area as well

**Comment by georgehrke** [comment]
> I thought we solved this for the Calendar CalDAV link some time ago.

No, I just checked and it's not working there either :confused:

**Comment by cmonteroluque** [comment]
@Henni can this be resolved by tomorrow? Otherwise it will have to go to 9.1

**Comment by MorrisJobke** [comment]
> @Henni can this be resolved by tomorrow? Otherwise it will have to go to 9.1

I don't think so. @Henni is heavily involved into contacts or calendar rework (I don't remind this properly).

**Comment by Henni** [comment]
I tried to fix it in https://github.com/owncloud/core/issues/22415, but it didn't work.
As I don't have an iOS device someone else should try.

**Comment by PVince81** [comment]
Do we have any other fields in any other app that work properly for copy/paste in iOS ?
Do the Webdav URL in the files app and calendar/contact apps work ?

**Comment by cmonteroluque** [comment]
@rperezb can someone in mobile have a look?

**Comment by cmonteroluque** [comment]
@jesmrec

**Comment by rperezb** [comment]
checked, ownCloud Enterprise Edition 9.1.0 pre alpha (daily) Build:2016-04-11T03:04:42+00:00 f9683aaf3d23d02cccdd65843bfd6c01f2e2bdad it does not work on the share link dialog
Sometimes, the copy menu is shown after long press, however, the options shown are: Copy, Define and Share , I missed the select all one, otherwise it's impossible to select the whole link

@PVince81 to your question, the menu to rename a file/folder name works

**Comment by PVince81** [comment]
@felixheidecke can you help with this ?

**Comment by DeepDiver1975** [comment]
with 9.2 we have the copy to clipboard functionality - this should work on ios as well

@nasli can you help testing this quickly? THX

**Comment by nasli** [comment]
@DeepDiver1975 I can not test it, appears empty, some notes added here https://central.owncloud.org/t/contacts-1-5-0-is-about-to-arrive/4259

**Comment by nasli** [comment]
Fixed, it was a misconfiguring server setting,

New copy button works with iphone 6 

👍

**Comment by DeepDiver1975** [comment]
@PVince81 case closed?

**Comment by nasli** [comment]
Sorry @DeepDiver1975, I misunderstanding this issue, I thought it was the same as the contact one. :(

The share link text field is the same as with the contact, we should add there a copy button too.

Checking this things I noticed some more issues. The UI is not prepared for touch devices. Tomorrow I will open some.

**Comment by PVince81** [comment]
@nasli do you mean the copy share link in the files app still does not work on master ?

**Comment by nasli** [comment]
Yes @PVince81, tested over {"installed":true,"maintenance":false,"version":"9.1.3.0","versionstring":"9.1.3 RC1","edition":""}

**Comment by DeepDiver1975** [comment]
> Yes @PVince81, tested over {"installed":true,"maintenance":false,"version":"9.1.3.0","versionstring":"9.1.3 RC1","edition":""}

9.1.3 != master

The copy clipboard button is only available on master - see https://github.com/owncloud/core/pull/25418

**Comment by nasli** [comment]
Ok, with {"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"9.2.0.3","versionstring":"9.2.0 pre alpha","edition":"Enterprise","productname":"ownCloud"}
there are a new copy button and works. We can close this :)
