### ISSUE TITLE
Owncloud 8.2.2 manual upgrade to version 9.0.0 fails

### ISSUE THREAD

**Issue by samuelstein** [owncloud/core#22968]
### Steps to reproduce
1. Owncloud 8.2.2 with addressbook needs to be installed
2. Manual upgrade installation to 9.0.0 (See: https://doc.owncloud.org/server/9.0/admin_manual/maintenance/manual_upgrade.html)
3. Open index.php

### Expected behaviour
Owncloud and apps should be upgraded

### Actual behaviour
owncloud.log shows following error:
```json
{
  "reqId": "wQzVLIALlhFjT6ci8uiC",
  "remoteAddr": "10.30.7.137",
  "app": "core",
  "message": "Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes\",\"Code\":0,\"Trace\":\"#0 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'CREATE TABLE `o...')\\n#2 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/lib\\/private\\/db\\/mdb2schemamanager.php(167): Doctrine\\\\DBAL\\\\Connection->query('CREATE TABLE `o...')\\n#3 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/lib\\/private\\/db\\/mdb2schemamanager.php(70): OC\\\\DB\\\\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#4 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/lib\\/private\\/db.php(172): OC\\\\DB\\\\MDB2SchemaManager->createDbFromStructure('\\/is\\/htdocs\\/wp10...')\\n#5 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/lib\\/private\\/installer.php(567): OC_DB::createDbFromStructure('\\/is\\/htdocs\\/wp10...')\\n#6 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/lib\\/private\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#7 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/lib\\/private\\/updater.php(336): OC_Installer::installShippedApps()\\n#8 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/lib\\/private\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.0.19', '8.2.2.2')\\n#9 \\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/core\\/ajax\\/update.php(120): OC\\\\Updater->upgrade()\\n#10 {main}\",\"File\":\"\\/is\\/htdocs\\/wp10838123_LGOL2QNNTD\\/www\\/samuelstein.de\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractMySQLDriver.php\",\"Line\":115}",
  "level": 3,
  "time": "2016-03-08T20:07:11+00:00",
  "method": "GET",
  "url": "/core/ajax/update.php?requesttoken=WRxtLlhgIlocD3IGPCssBj0sXBgyNhgkUSQrXz0c%3Ak%2F%2BM75thUXA1tOtseI0BTYBEfgj6ZjBRLS9nXn8d"
}
```

### Server configuration
**Operating system**: shared space at hosteurope

**Web server:** apache

**Database:** mysql

**PHP version:** latest 5

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here:
```
`ownCloud wird auf Version 9.0.0 aktualisiert. Das könnte eine Weile dauern.

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet 
Prüft, ob das Datenbankschema aktualisiert werden kann (dies kann je nach Datenbankgröße sehr lange dauern)
Datenbankschema-Aktualisierung überprüft
Es wird nach Updates für die Apps gesucht
Datenbankschema-Aktualisierung für Apps überprüft
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes`
```

**List of activated apps:**

**Are you using external storage:** no

**Are you using encryption:** no

**Are you using an external user-backend:** no

### Client configuration
**Browser:** 48.0.2564.116 m (64-bit)

**Operating system:** windows 7

#### Browser log
Insert your browser log here, this could for example include:

a) The javascript console log: 'https://ssl.webpack.de/cloud.samuelstein.de/core/js/oc.js?v=d78eff885055a5dff1258825d52763d5 Failed to load resource: the server responded with a status of 500 (Internal Server Error)'

**Comment by LukasReschke** [comment]
>  Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

@DeepDiver1975

**Comment by autrui** [comment]
I've experienced something similar after (manually) updating: always got an **internal server error (500)** when calling the login page.
In my case it was caused by the new/updated **.htaccess**, or more specifically the new rules after 'Rewrite rules for front_controller_active'.
The only way for me to get OC 9.0.0 to work was to edit the .htaccess-file and live with the code integrity check warning. 
In the end it came down to one line I had to disable:  
`    #RewriteRule .* index.php [PT,E=PATH_INFO:$1]`

**Comment by Bernd1978** [comment]
Disable helps nothing to me :-( Still got the same error:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

All hints welcome, because I don't want to reinstall owncloud.

**Comment by nickvergessen** [comment]
Delete those lines for the time being:
https://github.com/owncloud/core/blob/master/apps/dav/appinfo/database.xml#L54-L63

**Comment by nickvergessen** [comment]
Text field without a set length are always heros on keys.

@PVince81 should have a QA task to test install/enable of all apps on innodb

**Comment by samuelstein** [comment]
@nickvergessen if i delete the lines then i get this error:
```
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists ```

**Comment by nickvergessen** [comment]
Yeah before attempting a second update, you need to wipe your database and restore a backup.

**Comment by PVince81** [comment]
@nickvergessen can you make a ticket in owncloud/QA with the details ?

**Comment by nickvergessen** [comment]
Done

**Comment by joni1993** [comment]
Another error that occurred while upgrading to 9.0.0 from 8.2.3.

```
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_clndr_objects` (`id` INT UNSIGNED AUTO_INCREMENT NOT NULL, `calendarid` INT UNSIGNED DEFAULT 0 NOT NULL, `objecttype` VARCHAR(40) DEFAULT '' NOT NULL, `startdate` DATETIME DEFAULT '1970-01-01 00:00:00', `enddate` DATETIME DEFAULT '1970-01-01 00:00:00', `repeating` INT DEFAULT 0, `summary` VARCHAR(255) DEFAULT NULL, `calendardata` LONGTEXT DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `lastmodified` INT DEFAULT 0, PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_clndr_objects' already exists
```

**Comment by DeepDiver1975** [comment]
> Text field without a set length are always heros on keys.

:panda_face: why is there no length? :scream:

**Comment by s24195** [comment]
Same here with me:

Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists

Running on debian with update from the repository and then failing the automatic update (as always).

Then I tried the shell occ upgrade etc. and after it stalled for a few minutes I killed the process.
Starting the upgrade once more gave me the failure message.

Let me know what information might be usefull for you. It is running on a KVM machine that can be easily reverted.

**Comment by Eridania** [comment]
This also happened to me after upgrading 8.2.2 to 9.0 with Softalocous. "Server error 500".

Even after i restored the backup of the previous installation, the error persists. Do I need to wipe and restore a backup of the database?

**Comment by nickvergessen** [comment]
> Between two upgrade attempts you have to reset your DB to the 8.2.2 version.
That means delete all tables and then restore the backup.

The error message looks like you didn't remove tables that have been created on the first update attempt.

**Comment by sterius** [comment]
Started manuaI upgrade process with all 3rd party apps deactivated, too. I skipped upgrade-process manually after about an hour at state "Updated <files_versions> to 1.2.0". After I restarted upgrade-process, I had error "SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbook' already exists". I deleted that table and started again, next error was the same but now for Table 'oc_cards'.
In the end I had to delete the following Tables and then the upgrade-process finished successfully after about 25 minutes (~110MB DB).
oc_addressbookchanges, oc_addressbooks, oc_calendarchanges, oc_calendarobjects, oc_calendars, oc_calendarsubscriptions, oc_cards, oc_cards_proerties, oc_dav_shares, oc_schedulingobjects
There was no need of restoring 8.2.2 database.

**Comment by nickvergessen** [comment]
I just tried it:
```sql
CREATE TABLE `oc_addressbooks` (
`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
`principaluri` VARCHAR(255) DEFAULT NULL,
`displayname` VARCHAR(255) DEFAULT NULL,
`uri` VARCHAR(255) DEFAULT NULL,
`description` VARCHAR(255) DEFAULT NULL,
`synctoken` INT UNSIGNED DEFAULT 1 NOT NULL,

UNIQUE INDEX addressbook_index (`principaluri`, `uri`),
PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB
```

```sql
SELECT * FROM oc_addressbooks
```
Works fine for mysql [5.6](http://sqlfiddle.com/#!9) and [5.5](http://sqlfiddle.com/#!2)

So you either need to give more information (exact php `php --version` and mysql versions `mysql --version`) about your system or we have no idea.

**Comment by samuelstein** [comment]
i have mysql 5.5.46-0 and php 5.5. now the table oc_calendars is the problem. i get the error `Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes`

**Comment by arno01** [comment]
I've just encountered the same issue upgrading from the ownCloud 8.2.2 to the v9.0.0.
php-fpm v5.6
mariadb v10.0.23


##### 1) Enable InnoDB.
/etc/mysql/my.cnf:
comment 
```sh
#skip-innodb
```

##### 2) Enable InnoDB large prefix to have index key prefixes up to 3072 bytes.
/etc/mysql/my.cnf:
```sh
innodb_large_prefix=1
```

##### 3) Convert MyISAM to InnoDB tables.
```sh
mysql -u root -p dbName -e "show table status where Engine='MyISAM';" | awk 'NR>1 {print "ALTER TABLE "$1" ENGINE = InnoDB;"}' | mysql -u root -p dbName
```

##### 4) Create missing table to see if it works now.
```
MariaDB [dbowncloud]> CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB;
Query OK, 0 rows affected (0.01 sec)
```

##### 5) Remove that table as the ownCloud upgrade should take care of it.
```
MariaDB [dbowncloud]> DROP TABLE `oc_addressbooks`;
Query OK, 0 rows affected (0.01 sec)
```

##### 6) Continue upgrading the ownCloud to v9.0.0
```
owncloud# php occ upgrade
```
Success!

**Comment by samuelstein** [comment]
the problem is that i only have a shared webspace where i don't have root access. 
my other idea was removing the problematic too long indices (principaluri) but then i got 500 error and in the logfile lots of migration errors because of missing indices.
for now i restore latest owncloud 8 release.
sad that the update is always such a horror.

**Comment by owncube** [comment]
Hello people.
@autrui @Eridania : about your "RewriteRule" issue. Its not related to ownCloud. Its webserver/php issue. We had the 500errors on many testsystems. You are right that remove this "#RewriteRule .* index.php [PT,E=PATH_INFO:$1]"  from the htaccess will fix it BUT. the code integrity check will fail because of wrong hash as you wrote. We have updated php+apache+mysql,.. to the latest stable version and no 500 error anymore on systems where we recieved it before. The error is that the RewriteRule does "too many" redirects and so apache/nginx deny this.
If you are on shared hosting you can contact the provider to get this fixed.

Topic "1071 Specified key was too long; max key length is 1000 bytes"
we got this fixed by upgrade to latest mysql version. Tested on ~ 1200 clouds from 8.x --> 9
Maybe this helps someone.

Regards
OwnCube

**Comment by autrui** [comment]
@owncube @DeepDiver1975 
I think I finally got to the bottom of it and it seems it had nothing to do with the version of apache, mysql or php installed.
I did a clean install on a new shared server account using the web installer (setup-owncloud.php). I chose to install it in the web root of my subdomain (I don't want/need a subfolder called owncloud).
 
The problem was: the .htaccess that the installer created was not correct. At the bottom of the .htaccess I had this part:

    #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
    ErrorDocument 403 /owncloud/core/templates/403.php
    ErrorDocument 404 /owncloud/core/templates/404.php
    <IfModule mod_rewrite.c>
      RewriteBase /owncloud
      <IfModule mod_env.c>
        SetEnv front_controller_active true
        <IfModule mod_dir.c>
          DirectorySlash off
        </IfModule>
      </IfModule>
    </IfModule>

As you can see it features `RewriteBase /owncloud` where it should be `RewriteBase /` (as it does in the path for the Error documents).
If I correct it I don't need to comment `RewriteRule .* index.php [PT,E=PATH_INFO:$1]` anymore to get owncloud working.
Of course, since I had to correct the .htaccess it still complains about the code integrity check.

So in the end it seems the problem is the .htaccess that's created. It doesn't reflect my choice to use the web root of my subdomain instead of a subfolder called owncloud.
I hope this can be fixed and I hope the code integrity check will never get more strict than this - in case I need to fix stuff myself. Thank you.

**Comment by PVince81** [comment]
@LukasReschke https://github.com/owncloud/core/issues/22968#issuecomment-200886438

maybe .htaccess was created too early, before the "overwrite" values in the config.php could be read/used/set ?

**Comment by owncube** [comment]
Hello @autrui 
From our view its not related to the htaccess, we use already a few thousand of clouds with V9 and no issue since we use newest php,apache and mysql version.
We tested to get back to an older version of web,php,.. and then the internal error was there again.
Updated again to stable versions and no internal error anymore
its not related to the htaccess from our view and our experience with a few thousand updates we have done in the last weeks.
of course you can edit the htaccess to get this fixed too, but thats not needed if apache,php is up2date and configured correct.
I also dont see any entry with "/owncloud" in the owncloud V9 package available here: https://download.owncloud.org/community/owncloud-9.0.0.zip
But i see you used the webinstaller php file. We dont use it so maybe there its the issue. 
A "real" update via latest stable package does not cause any issues from our view and no /owncloud/ path in the htaccess.
Regards

**Comment by autrui** [comment]
Hello @owncube 
so if you switched back and forth between different versions of apache, mysql, php… you probably have an idea about the version of each needed to get rid of this error, right? 
I'm also on shared hosting so I'd be glad for this info so I could request an update, if necessary. 
Right now it's PHP 5.6.18, mySQL Ver 14.14 Distrib 5.1.73, Apache 2.2.15 .
Thank you.

**Comment by DeepDiver1975** [comment]
the column length issue is fixed from my pov with #23508 - for any other remaining issues - please open a new issue - THX

**Comment by Messa1** [comment]
@samuelstein - I got the same problem with oc_addressbooks table `Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes`. So i try everything that i found to fix that problem :) But no one works for me.

### **So i did it this way.**

_**First a full backup of your data and SQL!**_

**1.** I have a lokal MAMP Server so i install OC 9.x.x and check the SQL.
**2.** I open my other SQL were my active system has.
**3.** I compare both SQL - and only export the missing one. (Cause the adjustments of the DB were done before / At the first try of the update)
**4.** Import the missing one in my active SQL 
**5.** Set in config/config.php 'installed' => true, 'maintenance' => false,
**6.** Check your System.

At my system everything works fine. I have made a deep test. Also the Mac and Windows client works finde with the new system.

Best Regards
Matthias
