### ISSUE TITLE
Installation owncloud 9 on debian 8 fails

### ISSUE THREAD

**Issue by itsharrie** [owncloud/core#23878]
### Steps to reproduce
wget -nv https://download.owncloud.org/download/repositories/stable/Debian_8.0/Release.key -O Release.key
apt-key add - < Release.key 
sh -c "echo 'deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /' >> /etc/apt/sources.list.d/owncloud.list"
apt-get update
apt-get install owncloud

### Expected behaviour
End up with correctly installed owncloud 9.

### Actual behaviour
...
Setting up owncloud-deps-php5 (9.0.1-1.1) ...
cp: cannot stat '/usr/share/doc/owncloud*/owncloud-config-apache.conf.default': No such file or directory
chown: cannot access '/etc/apache2/conf-available/owncloud.conf': No such file or directory
chmod: cannot access '/etc/apache2/conf-available/owncloud.conf': No such file or directory
installing new /etc/apache2/conf-available/owncloud.conf
ERROR: Conf owncloud does not exist!
apache2_invoke: Enable module rewrite
...

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache2 (automatically installed from the owncloud package)
**Database:**
mysql

**PHP version:**
php5  (automatically installed from the owncloud package)

**ownCloud version:** (see ownCloud admin page)
9.0.1-1.1

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by enoch85** [comment]
@itsharrie Hey, you have to do like this: https://github.com/enoch85/ownCloud-VM/blob/master/debian/owncloud_install.sh#L176-L180

**Comment by enoch85** [comment]
@itsharrie Please confirm that it worked.

**Comment by Xenopathic** [comment]
@jnweiger From a quick look at the packages, it looks like owncloud-deps-php* packages don't list owncloud-files in Depends, so apt can install them before owncloud-files, but the required owncloud-config-apache.conf.default file is provided by owncloud-files. Adding owncloud-files to the Depends field on both owncloud-deps-php* packages should fix this?

**Comment by itsharrie** [comment]
Daniel,
I do not get the error message anymore.
The owncloud.conf file is still missing.
I'm missing out on the dependencies (because I installed owncloud-files 
rather than the meta package owncloud) :-(

**Comment by enoch85** [comment]
@itsharrie Yes, that's because you have to install the dependencies. To make it easy for yourself, just use the scripts and install it on Debian with them. Just use a clean system (Debian 8) and wget `owncloud_install.sh` from my Debian repo and then run it as root with `bash`. The script will setup everything for you. 

@jnweiger Still, this is an isse as @Xenopathic mentions. It's almost the same with the Ubuntu packages. I reported that in another issue.

**Comment by enoch85** [comment]
@itsharrie To be more specific: `wget https://raw.githubusercontent.com/enoch85/ownCloud-VM/master/debian/owncloud_install.sh` (as root): `bash owncloud_install.sh`

**Comment by jnweiger** [comment]
Is is a documented feature that we can influence installation order with Depends: statements? 
From RPM I learned that installation order is always unreliable.

**Comment by Xenopathic** [comment]
@jnweiger The failing command is running during the postinst phase, which is after all packages are extracted to the filesystem, so in this case adding a Depends would solve the problem (I think).

**Comment by jnweiger** [comment]
http://download.owncloud.org/download/repositories/testing/owncloud/ has the suggested Depends.

**Comment by itsharrie** [comment]
Thank you for the update of package Debian_8.0 owncloud-9.0.1-2.1

Unfortunately the original error remains.
This is the output I get:

...
**Creating config file /etc/php5/mods-available/pdo_pgsql.ini with new 
version
php5_invoke: Enable module pdo_pgsql for apache2 SAPI
php5_invoke: Enable module pdo_pgsql for cli SAPI
Setting up owncloud-deps-php5 (9.0.1-2.1) ...
cp: cannot stat 
'/usr/share/doc/owncloud*/owncloud-config-apache.conf.default': No such 
file or directory
chown: cannot access '/etc/apache2/conf-available/owncloud.conf': No 
such file or directory
chmod: cannot access '/etc/apache2/conf-available/owncloud.conf': No 
such file or directory
installing new /etc/apache2/conf-available/owncloud.conf
ERROR: Conf owncloud does not exist!
apache2_invoke: Enable module rewrite
Setting up owncloud (9.0.1-2.1) ...
Processing triggers for libc-bin (2.19-18) ...
Processing triggers for systemd (215-17+deb8u1) ...
Processing triggers for libapache2-mod-php5 (5.6.19+dfsg-2) ...

Being a newbie, I wander what the meaning of the asterisk in 
*/usr/share/doc/owncloud*/owncloud-config-apache.conf.default. *Could 
that be the cause of the problem?

I'm trying to install owncloud 9 on my Olimex Olinuxino Lime2 Linux 8 
server. Owncloud 6, 7 and 8 have done a great job sofar...

Thank you for your effort!

Harrie Guikers

**Comment by PVince81** [comment]
@jnweiger any update ?

**Comment by jnweiger** [comment]
The dependency trick apparently did not solve the issue. 
With DEB packaging the owncloud-config-apache.conf.default is part of the *.deps* package. I probably should do that for RPM too. checking options.

**Comment by itsharrie** [comment]
Hi Juergen,

In my last response I mentioned this weird path for the config file that 
is missing.
The output I got while the package was installed looked like this:

...
Creating config file /etc/php5/mods-available/pdo_pgsql.ini with new version
php5_invoke: Enable module pdo_pgsql for apache2 SAPI
php5_invoke: Enable module pdo_pgsql for cli SAPI
Setting up owncloud-deps-php5 (9.0.1-2.1) ...
cp: cannot stat 
'/usr/share/doc/owncloud*/owncloud-config-apache.conf.default': No such 
file or directory
chown: cannot access '/etc/apache2/conf-available/owncloud.conf': No 
such file or directory
chmod: cannot access '/etc/apache2/conf-available/owncloud.conf': No 
such file or directory
installing new /etc/apache2/conf-available/owncloud.conf
ERROR: Conf owncloud does not exist!
apache2_invoke: Enable module rewrite
Setting up owncloud (9.0.1-2.1) ...
Processing triggers for libc-bin (2.19-18) ...
Processing triggers for systemd (215-17+deb8u1) ...
Processing triggers for libapache2-mod-php5 (5.6.19+dfsg-2) ...

It appears to me that the path 
/usr/share/doc/owncloud*/owncloud-config-apache.conf.default is 
malformed. The asterisk in the middle of the path seems erroneous to me. 
Could you let me know what the meaning of this asterisk would be and 
whether it could be the cause of the missing config file?

Thank you!

Regards,

Harrie Guikers

**Comment by jnweiger** [comment]
The asterisk is fine. The copy code is run in a shell script, where the asterisk is a wildcard globbing. This makes us independant of the exact package name owncloud, or owncloud-enterprise or owncloud-files ...

**Comment by itsharrie** [comment]
Thank you for the quick response.
Looking forward to being able to install 9

**Comment by jnweiger** [comment]
Only pushed to http://download.owncloud.org/download/repositories/9.0:/testing/owncloud
Please test if this fixes the issue. For me it appears to do so. I had to manually remove the /usr/share/doc/owncloud*/owncloud-config-apache.conf.default file to trigger the issue. Maybe that make my test invalid.

**Comment by itsharrie** [comment]
Installation works withour error messages.

I tested 9.0.2~rc1-1.1

Thanks a lot!
