### ISSUE TITLE
settings/personal: new password always marked very weak

### ISSUE THREAD

**Issue by andreas-p** [owncloud/core#24422]
When changing the password on the personal settings page, password strength indication isn't updated properly:
After typing the first letter, the strength bar is one segment long and red, the tooltip displays "Very weak password" which is expected.
While further typing more characters, the strength bar gets longer and turns green, while the tooltip remains on "Very weak". No messages on the browser error console.

Observing Firefox Debugger, the strengthify-wrapper title actually changes to "Strong password", but the displayed tooltip isn't updated. Poking around, I found that the tooltip text is updated from data-original-title, not from title.

V9.0.1, tested on latest OSX Firefox and Safari.

**Comment by andreas-p** [comment]
I've been digging down jquery.strengthify and found that this problem is probably fixed in newer versions. Just replacing strengthify with the newer 0.5.0. version won't work, but adding a .tooltip('fixTitle') will trigger re-reading the title, so line 93ff should look like
	$wrapper.attr('title',options.titles[result.score]	)
			.tooltip({ placement: 'bottom',trigger: 'manual' })
			.tooltip('fixTitle') // trigger re-reading title to data-original-title
			.tooltip('show');

**Comment by jonathancross** [comment]
Saw this today when selecting the Admin password during setup.
Platform: `Chrome v50, Mac OSX`

**Comment by PVince81** [comment]
The approach proposed here https://github.com/owncloud/core/issues/24422#issuecomment-216579411 could help fix it.

If someone has time please submit a PR with it.

**Comment by tfrdidi** [comment]
I use version 9.1.0 and its still present... Maybe you adjust your milestone planning.

**Comment by PVince81** [comment]
Requires jquery.strengthify update. If after that it still doesn't work, then the library itself might need fixing.

**Comment by cdamken** [comment]
@PVince81 not only the email is shown as weak, while you try to change the email it display `invalid mail address`

**Comment by alieneby** [comment]
REASON: Wrong js include.
MY FIX for 'ownCloud 9.2.0 pre alpha (git)'
FILE: core/settings/js/personal.js
LINE: 339
CHANGE TO: 	zxcvbn: OC.linkTo('core','vendor/zxcvbn/dist/zxcvbn.js'),

**Comment by PVince81** [comment]
Reopening due to the tooltip issue

**Comment by Prakharsvnit** [comment]
I faced this issue when i installed owncloud version 9.1.4.2 on ubuntu 16.04.
I tried to login with firefox 51.0.1 for first time and password strength meter always showed "very weak password" although password included alphabets,numbers,special characters too.
I'm also attaching screenshots for the purpose.

![screenshot from 2017-01-29 00-52-10](https://cloud.githubusercontent.com/assets/19989448/23039291/16998224-f4b3-11e6-8214-6b40fff4e3ae.png)
![screenshot from 2017-01-29 02-46-43](https://cloud.githubusercontent.com/assets/19989448/23039290/1698c0dc-f4b3-11e6-9c81-cbb6ffd41fb9.png)

**Comment by PVince81** [comment]
@Prakharsvnit please try with 10.0 / master, the problem should be fixed there. Required a library update.

**Comment by Prakharsvnit** [comment]
@PVince81 i encountered this issue only once at time of logging into owncloud,no issues now.

**Comment by Prakharsvnit** [comment]
@PVince81 i needed to reinstall owncloud.I encountered following error:
![screenshot from 2017-02-19 01-23-09](https://cloud.githubusercontent.com/assets/19989448/23096445/75bfdbb4-f642-11e6-83b5-c5a6cdf7672c.png)
I tried to solve it by following instructions given @ [https://doc.owncloud.org/server/9.0/admin_manual/maintenance/upgrade.html](url).but it keeps throwing error:"This version of ownCloud is not compatible with PHP 7.1.<br/>You are currently running 7.1.2-2+deb.sury.org~xenial+1. Please use at least ownCloud 10.0.0" .I'm attaching screenshot for reference:
![screenshot from 2017-02-19 01-27-41](https://cloud.githubusercontent.com/assets/19989448/23096471/09660dc0-f643-11e6-87f1-cf5b2f228b4a.png)
Please help me in pointing out problem.THX
