### ISSUE TITLE
Cron can get into a deadlock

### ISSUE THREAD

**Issue by Raydiation** [owncloud/core#3221]
Just happened to me and also others http://apps.owncloud.com/content/show.php/News?content=158434

The cron service generates a lockfile in data/cron.lock. This log file is not removed in certain cases which leads to a deadlock. The file exists and no cronjobs will be executed for that period.

My suggestion: set a maximum timeout for the cronjob lockfile and remove the lock file after that.

cc @zimba12 @jakobsack @icewind1991

**Comment by Akhenaton** [comment]
[ownCloud 7.0.4]
[Apache/2.4.10 (Ubuntu), PHP Version 5.6.5-1, mysql  Ver 14.14 Distrib 5.5.41]
"cron.php" process, called by my linux system every 15 minutes.
Still getting that problem quite often... really annoying...

**Comment by Killer1337** [comment]
I am just seeing the same error right now on 8.0.

**Comment by simontretter** [comment]
Same here on 8.0

**Comment by Killer1337** [comment]
It seems to happen rather regularly on 8.0 now. Usually the server has higher load when the error occurs. 
I didn't have the problem at 7.x

**Comment by prilly** [comment]
Just got the same issues on a debian 7 system. cron lock up.:Another instance of cron.php is still running.

this error is only occuring with OC8

**Comment by DeepDiver1975** [comment]
> Just got the same issues on a debian 7 system. cron lock up.:Another instance of cron.php is still running.

well - this alone is not a problem but a protection to avoid that the same job is executed twice.

The problem only exists in case the first cron process dies and leaves the lock file behind.

**Comment by DeepDiver1975** [comment]
@icewind1991 can we leverage the jobs entries in oc_jobs in a way to allow parallel execution?
I'm thinking about some kind of status.

In this case we could basically allow true parallel execution - just an idea.
Worst case we need to wait until laravel queues have been incorporated.

**Comment by DeepDiver1975** [comment]
> Worst case we need to wait until laravel queues have been incorporated.

and they know how to do it https://github.com/laravel/framework/blob/5.0/src/Illuminate/Queue/DatabaseQueue.php#L195

**Comment by prilly** [comment]
Ok i understand that, do you know where the lock file is located on debian 7, i belive its should be just to delete it and restart cron.

Thank you

-------- Opprinnelig melding --------
Fra: Thomas Müller <notifications@github.com> 
Dato:18.02.2015  18:02  (GMT+01:00) 
Til: owncloud/core <core@noreply.github.com> 
Ko: Prilly <prilly@speedbox.me> 
Emne: Re: [core] Cron can get into a deadlock (#3221) 

Just got the same issues on a debian 7 system. cron lock up.:Another instance of cron.php is still running.

well - this alone is not a problem but a protection to avoid that the same job is executed twice.

The problem only exists in case the first cron process dies and leaves the lock file behind.

**Comment by giogp** [comment]
cron.lock in your /owncloud/data/ folder

Von meinem iPhone gesendet

**Comment by jakobsack** [comment]
@DeepDiver1975 After doing a quick check it seems like cron.php still deletes the row for queued jobs before actually executing them. Executing those jobs in parallel shouldn't be a problem.

If I'm not mistaken the timestamp for timed jobs is updated before executing them so it should be possible to execute them in parallel as well.

**Comment by Killer1337** [comment]
Until this is fixed I am using a workaround at the moment that works for me:

I created a simple bash script that checks for an existing cron.lock file before executing cron.php the next time. If cron.lock exists it will not start a new one. If it still exists the next time, it will delete cron.lock and start cron.php afterwards.

So in my crontab I now call this script instead of cron.php.

Is there something wrong with my workaround approach? Please enlighten me!
At least it seams to work for me...

**Comment by Raydiation** [comment]
@Killer1337 should be fine until your cronjob takes longer than your setting. Then your system will go down because of the possible high load being produced ;D

**Comment by Killer1337** [comment]
Sounds reasonable. So maybe extending the time between cron jobs until this is fixed might be a good Idea :).

Out of curiosity: What is executed by cron.php? I conciously only use it to update my owncloud news feeds. What else am I executing "unconciously" every 10 minutes? Other than news I only manually enabled calendar and contacts. The rest is stock.

**Comment by Raydiation** [comment]
I think theres a job for files cache cleanup

**Comment by Raydiation** [comment]
I've created a PR to fix this.

**Comment by Killer1337** [comment]
Could the search app be the bad guy?

`PHP Fatal error:  Maximum execution time of 3600 seconds exceeded in /var/www/owncloud/apps/search_lucene/3rdparty/zendframework/zendsearch/library/ZendSearch/Lucene/Analysis/Analyzer/Common/Utf8Num.php on line 85`

I'll try disabling it for now.

**Comment by LukasReschke** [comment]
That looks indeed related @Killer1337.

Mind to open an issue about that at https://github.com/owncloud/search_lucene/ and backlink to here? Thanks!

**Comment by Raydiation** [comment]
Fix is merged in master, please test and comment on the pull request if further issues arise https://github.com/owncloud/core/issues/14400

**Comment by mbeil** [comment]
Hi,
since I updated to OC8.x I have this problem. I'm more a java programmer, so I might miss something, but I had a look at the cron.php code.

The only code which deletes the 'cron.lock' file is in

      // We use this function to handle (unexpected) shutdowns
      function handleUnexpectedShutdown() {} 

function. IMHO this function is only called, when there is an unexpected shutdown. When the code terminates normally, there is no deletion of the 'cron.lock' file.

I added 

        // Delete lockfile
        if (!TemporaryCronClass::$keeplock && file_exists(TemporaryCronClass::$lockfile)) {
                unlink(TemporaryCronClass::$lockfile);
        }
        exit();

before the 'exit()' call. This seems to solve the problem.

My2Cents.

**Comment by Raydiation** [comment]
@mbeil there is already a fix in master (8.1) that will also work in other error cases. Scroll up to see the PR

**Comment by mbeil** [comment]
THX, that are good news. Actual I have just now updated to OC8.0.2, and still the error persist. 
Waiting for the fix, as it this error is very angry. What is the schedule of OC8.1?

**Comment by RealRancor** [comment]
@mbeil: https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule
