### ISSUE TITLE
OwnCloud 7 database update causing crashes in PHP (running on Fedora 20)

### ISSUE THREAD

**Issue by AdamWill** [owncloud/core#9885]
So I'm working on updating Fedora's packaged OwnCloud to OwnCloud 7. The packages are at https://www.happyassassin.net/temp/oc7_repo/ .

While testing on my own OC deployment, running on Fedora 20, I've found that accessing OC 7 often seems to cause crashes in PHP, I think in the Zend opcache.

The symptom is that I browse to www.server.foo/owncloud and get a white page. In the Apache error logs will either be a note that an httpd child process crashed, or this error:

    zend_mm_heap corrupted

I have saved the coredump from one of the crashes and traced it out. I'll post the backtrace as a comment.

Right now, when the crash doesn't happen, what I actually see is the database upgrade page (for an upgrade from 7.0.0RC3 to 7.0.0 final), but I've seen the same thing happen *during* the database upgrade process (from 6.0.4 to 7.0.0 RC1). I thought I'd also seen it outside of the 'upgrade' workflow, but that may not actually be true (see later comment).

Setting PHP's output_buffering to 32768 (up from 4096) mitigated this problem to some extent with the RCs, I think - it let me do the upgrade from 6.0.4 to RC1 and from RC1 to RC3, leastways - but even at 32768 I'm getting crashes with final.

The PHP in use is Fedora's packaged PHP, which is 5.5.14. I can provide php_info() and whatever php.ini settings might be interesting upon request.

I asked in ##php about this and the response was basically that OwnCloud is doing something wrong, so report it to you. I have Wordpress and tt-rss deployments on the same server using the exact same PHP config and they aren't crashing, and OwnCloud 6 in the same environment didn't do this.

**Comment by LukasReschke** [comment]
I guess this has been fixed while merging https://github.com/owncloud/core/pull/11056 and can be closed?

Backport consideration is at https://github.com/owncloud/core/issues/14175#issuecomment-74152155

**Comment by AdamWill** [comment]
I'd certainly expect so - I haven't tested it specifically in a while, but I've been carrying the patch in the Fedora packages all along and haven't seen or had this crash reported, and I can't think of any reason it *wouldn't* be fixed.

It'd be good to know if backporting it helps any of those reporters, though of course they'd need to have a backup available, or be willing to reproduce things...

**Comment by oparoz** [comment]
It's a problem when using occ on 8.0.2. Might also be a problem when using the GUI, but the error is silenced.

**Comment by autumnwalker** [comment]
opcache.ini is located at /usr/share/php5/common/opcache.ini in Ubuntu 14.04.

I have added the directive opcache.fast_shutdown=0 to my php.ini file. I'll see if that fixes the issue I'm having in #15450.

**Comment by autumnwalker** [comment]
FYI - issue persists; however, the server did not continue crashing in a loop until the remaining Apache2 processes were killed and restarted.

**Comment by Morganlej** [comment]
Better than a workaround would be a real fix in opcache. Is there a known upstream bug report on it?
We have found similar or same issue with zend opcache also on mageia even without owncloud.
( https://bugs.mageia.org/show_bug.cgi?id=12995 )

**Comment by AdamWill** [comment]
@Morganlej as I wrote above, "I think it's still a bug in the opcache that it crashes when OC tries to reset it - and I've filed that upstream":

https://bugs.php.net/bug.php?id=67687
